# -*- coding: utf-8 -*-
from PyQt4 import QtGui
import sys, datetime

def on_clicked():
    print(calendar.sD..().toPyDate())

app = QtGui.QApplication(sys.argv)
window = QtGui.QWidget()
window.setWindowTitle("Класс QCalendarWidget")
window.resize(300, 400)
calendar = QtGui.QCalendarWidget()
calendar.setSelectedDate(datetime.date.today())
button = QtGui.QPushButton("Вывести значение")
button.clicked.connect(on_clicked)
button1 = QtGui.QPushButton("К выбранной дате")
button1.clicked.connect(calendar.showSelectedDate)
button2 = QtGui.QPushButton("К текущей дате")
button2.clicked.connect(calendar.showToday)
button3 = QtGui.QPushButton("Предыдущий месяц")
button3.clicked.connect(calendar.showPreviousMonth)
button4 = QtGui.QPushButton("Следующий месяц")
button4.clicked.connect(calendar.showNextMonth)
button5 = QtGui.QPushButton("Предыдущий год")
button5.clicked.connect(calendar.showPreviousYear)
button6 = QtGui.QPushButton("Следующий год")
button6.clicked.connect(calendar.showNextYear)
box = QtGui.QVBoxLayout()
box.addWidget(calendar)
box.addWidget(button)
box.addWidget(button1)
box.addWidget(button2)
box.addWidget(button3)
box.addWidget(button4)
box.addWidget(button5)
box.addWidget(button6)
window.setLayout(box)
window.show()
sys.exit(app.exec_())