# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created: Fri Jul 26 06:49:55 2013
#      by: PyQt5 UI code generator 5.0.1-snapshot-2a99e59669ee
#
# WARNING! All changes made in this file will be lost!

____ ? ______ ?C.., ?G.., ?W..

c_ Ui_MainWindow(object):
    ___ setupUi  MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(400, 413)
        self.centralwidget _ ?W...QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.vboxlayout _ ?W...QVBoxLayout(self.centralwidget)
        self.vboxlayout.setContentsMargins(9, 9, 9, 9)
        self.vboxlayout.setSpacing(6)
        self.vboxlayout.setObjectName("vboxlayout")
        self.mainFrame _ ?W...QFrame(self.centralwidget)
        self.mainFrame.setFrameShape(?W...QFrame.StyledPanel)
        self.mainFrame.setFrameShadow(?W...QFrame.Raised)
        self.mainFrame.setObjectName("mainFrame")
        self.gridlayout _ ?W...QGridLayout(self.mainFrame)
        self.gridlayout.setContentsMargins(9, 9, 9, 9)
        self.gridlayout.setSpacing(6)
        self.gridlayout.setObjectName("gridlayout")
        self.agreeCheckBox _ ?W...QCheckBox(self.mainFrame)
        self.agreeCheckBox.setObjectName("agreeCheckBox")
        self.gridlayout.aW..(self.agreeCheckBox, 6, 0, 1, 5)
        self.label _ ?W...QLabel(self.mainFrame)
        self.label.setAlignment(?C...__.AlignRight|?C...__.AlignTop|?C...__.AlignTrailing)
        self.label.setObjectName("label")
        self.gridlayout.aW..(self.label, 5, 0, 1, 1)
        self.nameLabel _ ?W...QLabel(self.mainFrame)
        self.nameLabel.setAlignment(?C...__.AlignRight|?C...__.AlignTrailing|?C...__.AlignVCenter)
        self.nameLabel.setObjectName("nameLabel")
        self.gridlayout.aW..(self.nameLabel, 0, 0, 1, 1)
        self.maleRadioButton _ ?W...QRadioButton(self.mainFrame)
        self.maleRadioButton.setObjectName("maleRadioButton")
        self.gridlayout.aW..(self.maleRadioButton, 1, 1, 1, 1)
        self.passwordLabel _ ?W...QLabel(self.mainFrame)
        self.passwordLabel.setAlignment(?C...__.AlignRight|?C...__.AlignTrailing|?C...__.AlignVCenter)
        self.passwordLabel.setObjectName("passwordLabel")
        self.gridlayout.aW..(self.passwordLabel, 3, 0, 1, 1)
        self.countryCombo _ ?W...QComboBox(self.mainFrame)
        self.countryCombo.setObjectName("countryCombo")
        self.countryCombo.addItem("")
        self.countryCombo.addItem("")
        self.countryCombo.addItem("")
        self.countryCombo.addItem("")
        self.countryCombo.addItem("")
        self.countryCombo.addItem("")
        self.countryCombo.addItem("")
        self.gridlayout.aW..(self.countryCombo, 4, 1, 1, 4)
        self.ageLabel _ ?W...QLabel(self.mainFrame)
        self.ageLabel.setAlignment(?C...__.AlignRight|?C...__.AlignTrailing|?C...__.AlignVCenter)
        self.ageLabel.setObjectName("ageLabel")
        self.gridlayout.aW..(self.ageLabel, 2, 0, 1, 1)
        self.countryLabel _ ?W...QLabel(self.mainFrame)
        self.countryLabel.setAlignment(?C...__.AlignRight|?C...__.AlignTrailing|?C...__.AlignVCenter)
        self.countryLabel.setObjectName("countryLabel")
        self.gridlayout.aW..(self.countryLabel, 4, 0, 1, 1)
        self.genderLabel _ ?W...QLabel(self.mainFrame)
        self.genderLabel.setAlignment(?C...__.AlignRight|?C...__.AlignTrailing|?C...__.AlignVCenter)
        self.genderLabel.setObjectName("genderLabel")
        self.gridlayout.aW..(self.genderLabel, 1, 0, 1, 1)
        self.passwordEdit _ ?W...QLineEdit(self.mainFrame)
        self.passwordEdit.setEchoMode(?W...QLineEdit.Password)
        self.passwordEdit.setObjectName("passwordEdit")
        self.gridlayout.aW..(self.passwordEdit, 3, 1, 1, 4)
        self.femaleRadioButton _ ?W...QRadioButton(self.mainFrame)
        self.femaleRadioButton.setObjectName("femaleRadioButton")
        self.gridlayout.aW..(self.femaleRadioButton, 1, 2, 1, 2)
        self.ageSpinBox _ ?W...QSpinBox(self.mainFrame)
        self.ageSpinBox.setMinimum(12)
        self.ageSpinBox.setProperty("value", 22)
        self.ageSpinBox.setObjectName("ageSpinBox")
        self.gridlayout.aW..(self.ageSpinBox, 2, 1, 1, 2)
        self.nameCombo _ ?W...QComboBox(self.mainFrame)
        self.nameCombo.setEditable(True)
        self.nameCombo.setObjectName("nameCombo")
        self.gridlayout.aW..(self.nameCombo, 0, 1, 1, 4)
        spacerItem _ ?W...QSpacerItem(40, 20, ?W...QSizePolicy.Expanding, ?W...QSizePolicy.Minimum)
        self.gridlayout.addItem(spacerItem, 1, 4, 1, 1)
        spacerItem1 _ ?W...QSpacerItem(61, 20, ?W...QSizePolicy.Expanding, ?W...QSizePolicy.Minimum)
        self.gridlayout.addItem(spacerItem1, 2, 3, 1, 2)
        self.buttonBox _ ?W...QDialogButtonBox(self.mainFrame)
        self.buttonBox.setOrientation(?C...__.Horizontal)
        self.buttonBox.setStandardButtons(?W...QDialogButtonBox.Cancel|?W...QDialogButtonBox.NoButton|?W...QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridlayout.aW..(self.buttonBox, 7, 3, 1, 2)
        self.professionList _ ?W...QListWidget(self.mainFrame)
        self.professionList.setObjectName("professionList")
        item _ ?W...QListWidgetItem()
        self.professionList.addItem(item)
        item _ ?W...QListWidgetItem()
        self.professionList.addItem(item)
        item _ ?W...QListWidgetItem()
        self.professionList.addItem(item)
        self.gridlayout.aW..(self.professionList, 5, 1, 1, 4)
        self.vboxlayout.aW..(self.mainFrame)
        MainWindow.sCW..(self.centralwidget)
        self.menubar _ ?W...QMenuBar(MainWindow)
        self.menubar.setGeometry(?C...QRect(0, 0, 400, 29))
        self.menubar.setObjectName("menubar")
        self.menu_File _ ?W...QMenu(self.menubar)
        self.menu_File.setObjectName("menu_File")
        self.menu_Help _ ?W...QMenu(self.menubar)
        self.menu_Help.setObjectName("menu_Help")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar _ ?W...QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.exitAction _ ?W...?A..(MainWindow)
        self.exitAction.setObjectName("exitAction")
        self.aboutQtAction _ ?W...?A..(MainWindow)
        self.aboutQtAction.setObjectName("aboutQtAction")
        self.editStyleAction _ ?W...?A..(MainWindow)
        self.editStyleAction.setObjectName("editStyleAction")
        self.aboutAction _ ?W...?A..(MainWindow)
        self.aboutAction.setObjectName("aboutAction")
        self.menu_File.aA..(self.editStyleAction)
        self.menu_File.addSeparator()
        self.menu_File.aA..(self.exitAction)
        self.menu_Help.aA..(self.aboutAction)
        self.menu_Help.aA..(self.aboutQtAction)
        self.menubar.aA..(self.menu_File.menuAction())
        self.menubar.aA..(self.menu_Help.menuAction())
        self.label.setBuddy(self.professionList)
        self.nameLabel.setBuddy(self.nameCombo)
        self.passwordLabel.setBuddy(self.passwordEdit)
        self.ageLabel.setBuddy(self.ageSpinBox)
        self.countryLabel.setBuddy(self.countryCombo)

        self.retranslateUi(MainWindow)
        self.countryCombo.setCurrentIndex(6)
        self.professionList.setCurrentRow(0)
        ?C...QMetaObject.connectSlotsByName(MainWindow)

    ___ retranslateUi  MainWindow):
        _translate _ ?C...QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Style Sheet"))
        self.agreeCheckBox.setToolTip(_translate("MainWindow", "Please read the LICENSE file before checking"))
        self.agreeCheckBox.sT..(_translate("MainWindow", "I accept the terms and &conditions"))
        self.label.sT..(_translate("MainWindow", "Profession:"))
        self.nameLabel.sT..(_translate("MainWindow", "&Name:"))
        self.maleRadioButton.setToolTip(_translate("MainWindow", "Check this if you are male"))
        self.maleRadioButton.sT..(_translate("MainWindow", "&Male"))
        self.passwordLabel.sT..(_translate("MainWindow", "&Password:"))
        self.countryCombo.setToolTip(_translate("MainWindow", "Specify country of origin"))
        self.countryCombo.setStatusTip(_translate("MainWindow", "Specify country of origin"))
        self.countryCombo.setItemText(0, _translate("MainWindow", "Egypt"))
        self.countryCombo.setItemText(1, _translate("MainWindow", "France"))
        self.countryCombo.setItemText(2, _translate("MainWindow", "Germany"))
        self.countryCombo.setItemText(3, _translate("MainWindow", "India"))
        self.countryCombo.setItemText(4, _translate("MainWindow", "Italy"))
        self.countryCombo.setItemText(5, _translate("MainWindow", "Norway"))
        self.countryCombo.setItemText(6, _translate("MainWindow", "Pakistan"))
        self.ageLabel.sT..(_translate("MainWindow", "&Age:"))
        self.countryLabel.sT..(_translate("MainWindow", "Country:"))
        self.genderLabel.sT..(_translate("MainWindow", "Gender:"))
        self.passwordEdit.setToolTip(_translate("MainWindow", "Specify your password"))
        self.passwordEdit.setStatusTip(_translate("MainWindow", "Specify your password"))
        self.passwordEdit.sT..(_translate("MainWindow", "Password"))
        self.femaleRadioButton.setToolTip(_translate("MainWindow", "Check this if you are female"))
        self.femaleRadioButton.sT..(_translate("MainWindow", "&Female"))
        self.ageSpinBox.setToolTip(_translate("MainWindow", "Specify your age"))
        self.ageSpinBox.setStatusTip(_translate("MainWindow", "Specify your age"))
        self.nameCombo.setToolTip(_translate("MainWindow", "Specify your name"))
        self.professionList.setToolTip(_translate("MainWindow", "Select your profession"))
        self.professionList.setStatusTip(_translate("MainWindow", "Specify your name here"))
        self.professionList.setWhatsThis(_translate("MainWindow", "Specify your name here"))
        __sortingEnabled _ self.professionList.isSortingEnabled()
        self.professionList.setSortingEnabled F..
        item _ self.professionList.item(0)
        item.sT..(_translate("MainWindow", "Developer"))
        item _ self.professionList.item(1)
        item.sT..(_translate("MainWindow", "Student"))
        item _ self.professionList.item(2)
        item.sT..(_translate("MainWindow", "Fisherman"))
        self.professionList.setSortingEnabled(__sortingEnabled)
        self.menu_File.setTitle(_translate("MainWindow", "&File"))
        self.menu_Help.setTitle(_translate("MainWindow", "&Help"))
        self.exitAction.sT..(_translate("MainWindow", "&Exit"))
        self.aboutQtAction.sT..(_translate("MainWindow", "About Qt"))
        self.editStyleAction.sT..(_translate("MainWindow", "Edit &Style..."))
        self.aboutAction.sT..(_translate("MainWindow", "About"))

