# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'G:\projects\pyqt\week7\styleSheet\widgets\window.ui'
#
# Created: Wed Nov 12 22:08:44 2014
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

____ PySide _____ ?C.., QtGui

c_ Ui_MainWindow(object
    ___ setupUi , MainWindow
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(356, 411)
        centralwidget = QtGui.?W..(MainWindow)
        centralwidget.setObjectName("centralwidget")
        verticalLayout = QtGui.QVBoxLayout(centralwidget)
        verticalLayout.setObjectName("verticalLayout")
        lineEdit = QtGui.QLineEdit(centralwidget)
        lineEdit.setObjectName("lineEdit")
        verticalLayout.addWidget(lineEdit)
        pushButton = QtGui.?PB..(centralwidget)
        pushButton.setObjectName("pushButton")
        verticalLayout.addWidget(pushButton)
        horizontalSlider = QtGui.QSlider(centralwidget)
        horizontalSlider.setMaximum(100)
        horizontalSlider.setOrientation(?C...Qt.Horizontal)
        horizontalSlider.setObjectName("horizontalSlider")
        verticalLayout.addWidget(horizontalSlider)
        checkBox = QtGui.QCheckBox(centralwidget)
        checkBox.setObjectName("checkBox")
        verticalLayout.addWidget(checkBox)
        horizontalLayout_2 = QtGui.QHBoxLayout()
        horizontalLayout_2.setObjectName("horizontalLayout_2")
        radioButton_2 = QtGui.QRadioButton(centralwidget)
        radioButton_2.setChecked(T..)
        radioButton_2.setObjectName("radioButton_2")
        horizontalLayout_2.addWidget(radioButton_2)
        radioButton = QtGui.QRadioButton(centralwidget)
        radioButton.setObjectName("radioButton")
        horizontalLayout_2.addWidget(radioButton)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        horizontalLayout_2.addItem(spacerItem)
        verticalLayout.addLayout(horizontalLayout_2)
        treeWidget = QtGui.QTreeWidget(centralwidget)
        treeWidget.setObjectName("treeWidget")
        item_0 = QtGui.QTreeWidgetItem(treeWidget)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_3 = QtGui.QTreeWidgetItem(item_2)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        item_0 = QtGui.QTreeWidgetItem(treeWidget)
        item_0 = QtGui.QTreeWidgetItem(treeWidget)
        item_0 = QtGui.QTreeWidgetItem(treeWidget)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        verticalLayout.addWidget(treeWidget)
        comboBox = QtGui.QComboBox(centralwidget)
        comboBox.setObjectName("comboBox")
        comboBox.addItem("")
        comboBox.addItem("")
        comboBox.addItem("")
        comboBox.addItem("")
        comboBox.addItem("")
        verticalLayout.addWidget(comboBox)
        horizontalLayout = QtGui.QHBoxLayout()
        horizontalLayout.setObjectName("horizontalLayout")
        spinBox = QtGui.QSpinBox(centralwidget)
        spinBox.setMaximum(100)
        spinBox.setObjectName("spinBox")
        horizontalLayout.addWidget(spinBox)
        progressBar = QtGui.QProgressBar(centralwidget)
        progressBar.setProperty("value", 24)
        progressBar.setObjectName("progressBar")
        horizontalLayout.addWidget(progressBar)
        verticalLayout.addLayout(horizontalLayout)
        MainWindow.setCentralWidget(centralwidget)
        menubar = QtGui.QMenuBar(MainWindow)
        menubar.setGeometry(?C...QRect(0, 0, 356, 21))
        menubar.setObjectName("menubar")
        menuFile = QtGui.QMenu(menubar)
        menuFile.setObjectName("menuFile")
        menuOpen = QtGui.QMenu(menuFile)
        menuOpen.setObjectName("menuOpen")
        menuHelop = QtGui.QMenu(menubar)
        menuHelop.setObjectName("menuHelop")
        MainWindow.setMenuBar(menubar)
        actionClose = QtGui.QAction(MainWindow)
        actionClose.setObjectName("actionClose")
        actionExit = QtGui.QAction(MainWindow)
        actionExit.setObjectName("actionExit")
        actionAbout = QtGui.QAction(MainWindow)
        actionAbout.setObjectName("actionAbout")
        actionFile = QtGui.QAction(MainWindow)
        actionFile.setObjectName("actionFile")
        actionProject = QtGui.QAction(MainWindow)
        actionProject.setObjectName("actionProject")
        menuOpen.addAction(actionFile)
        menuOpen.addAction(actionProject)
        menuFile.addAction(menuOpen.menuAction())
        menuFile.addAction(actionClose)
        menuFile.addAction(actionExit)
        menuHelop.addAction(actionAbout)
        menubar.addAction(menuFile.menuAction())
        menubar.addAction(menuHelop.menuAction())

        retranslateUi(MainWindow)
        ?C...QObject.c..(horizontalSlider, ?C...SIGNAL("valueChanged(int)"), progressBar.setValue)
        ?C...QObject.c..(horizontalSlider, ?C...SIGNAL("valueChanged(int)"), spinBox.setValue)
        ?C...QObject.c..(spinBox, ?C...SIGNAL("valueChanged(int)"), horizontalSlider.setValue)
        ?C...QObject.c..(spinBox, ?C...SIGNAL("valueChanged(int)"), progressBar.setValue)
        ?C...QObject.c..(radioButton_2, ?C...SIGNAL("toggled(bool)"), treeWidget.setEnabled)
        ?C...QMetaObject.connectSlotsByName(MainWindow)

    ___ retranslateUi , MainWindow
        MainWindow.setWindowTitle(QtGui.?A...translate("MainWindow", "MainWindow", None, QtGui.?A...UnicodeUTF8))
        pushButton.sT..(QtGui.?A...translate("MainWindow", "Start", None, QtGui.?A...UnicodeUTF8))
        checkBox.sT..(QtGui.?A...translate("MainWindow", "Show", None, QtGui.?A...UnicodeUTF8))
        radioButton_2.sT..(QtGui.?A...translate("MainWindow", "Enable", None, QtGui.?A...UnicodeUTF8))
        radioButton.sT..(QtGui.?A...translate("MainWindow", "Disable", None, QtGui.?A...UnicodeUTF8))
        treeWidget.headerItem().sT..(0, QtGui.?A...translate("MainWindow", "1", None, QtGui.?A...UnicodeUTF8))
        __sortingEnabled = treeWidget.isSortingEnabled()
        treeWidget.setSortingEnabled(False)
        treeWidget.topLevelItem(0).sT..(0, QtGui.?A...translate("MainWindow", "New Item", None, QtGui.?A...UnicodeUTF8))
        treeWidget.topLevelItem(0).child(0).sT..(0, QtGui.?A...translate("MainWindow", "New Subitem", None, QtGui.?A...UnicodeUTF8))
        treeWidget.topLevelItem(0).child(0).child(0).sT..(0, QtGui.?A...translate("MainWindow", "New Subitem", None, QtGui.?A...UnicodeUTF8))
        treeWidget.topLevelItem(0).child(0).child(0).child(0).sT..(0, QtGui.?A...translate("MainWindow", "New Subitem", None, QtGui.?A...UnicodeUTF8))
        treeWidget.topLevelItem(0).child(1).sT..(0, QtGui.?A...translate("MainWindow", "New Subitem", None, QtGui.?A...UnicodeUTF8))
        treeWidget.topLevelItem(0).child(2).sT..(0, QtGui.?A...translate("MainWindow", "New Subitem", None, QtGui.?A...UnicodeUTF8))
        treeWidget.topLevelItem(1).sT..(0, QtGui.?A...translate("MainWindow", "New Item", None, QtGui.?A...UnicodeUTF8))
        treeWidget.topLevelItem(2).sT..(0, QtGui.?A...translate("MainWindow", "New Item", None, QtGui.?A...UnicodeUTF8))
        treeWidget.topLevelItem(3).sT..(0, QtGui.?A...translate("MainWindow", "New Item", None, QtGui.?A...UnicodeUTF8))
        treeWidget.topLevelItem(3).child(0).sT..(0, QtGui.?A...translate("MainWindow", "New Subitem", None, QtGui.?A...UnicodeUTF8))
        treeWidget.setSortingEnabled(__sortingEnabled)
        comboBox.setItemText(0, QtGui.?A...translate("MainWindow", "New Item", None, QtGui.?A...UnicodeUTF8))
        comboBox.setItemText(1, QtGui.?A...translate("MainWindow", "New Item", None, QtGui.?A...UnicodeUTF8))
        comboBox.setItemText(2, QtGui.?A...translate("MainWindow", "New Item", None, QtGui.?A...UnicodeUTF8))
        comboBox.setItemText(3, QtGui.?A...translate("MainWindow", "New Item", None, QtGui.?A...UnicodeUTF8))
        comboBox.setItemText(4, QtGui.?A...translate("MainWindow", "New Item", None, QtGui.?A...UnicodeUTF8))
        menuFile.setTitle(QtGui.?A...translate("MainWindow", "File", None, QtGui.?A...UnicodeUTF8))
        menuOpen.setTitle(QtGui.?A...translate("MainWindow", "Open", None, QtGui.?A...UnicodeUTF8))
        menuHelop.setTitle(QtGui.?A...translate("MainWindow", "Help", None, QtGui.?A...UnicodeUTF8))
        actionClose.sT..(QtGui.?A...translate("MainWindow", "Close", None, QtGui.?A...UnicodeUTF8))
        actionExit.sT..(QtGui.?A...translate("MainWindow", "Exit", None, QtGui.?A...UnicodeUTF8))
        actionAbout.sT..(QtGui.?A...translate("MainWindow", "About", None, QtGui.?A...UnicodeUTF8))
        actionFile.sT..(QtGui.?A...translate("MainWindow", "File", None, QtGui.?A...UnicodeUTF8))
        actionProject.sT..(QtGui.?A...translate("MainWindow", "Project", None, QtGui.?A...UnicodeUTF8))

