# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'G:\projects\pyqt\week7\styleSheet\widgets\window.ui'
#
# Created: Wed Nov 12 22:08:44 2014
#      by: PyQt4 UI code generator 4.11.2
#
# WARNING! All changes made in this file will be lost!

____ PyQt4 _____ ?C.., QtGui

try:
    _fromUtf8 = ?C...QString.fromUtf8
except AttributeError:
    ___ _fromUtf8(s
        return s

try:
    _encoding = QtGui.?A...UnicodeUTF8
    ___ _translate(context, text, disambig
        return QtGui.?A...translate(context, text, disambig, _encoding)
except AttributeError:
    ___ _translate(context, text, disambig
        return QtGui.?A...translate(context, text, disambig)

c_ Ui_MainWindow(object
    ___ setupUi , MainWindow
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(356, 411)
        centralwidget = QtGui.?W..(MainWindow)
        centralwidget.setObjectName(_fromUtf8("centralwidget"))
        verticalLayout = QtGui.QVBoxLayout(centralwidget)
        verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        lineEdit = QtGui.QLineEdit(centralwidget)
        lineEdit.setObjectName(_fromUtf8("lineEdit"))
        verticalLayout.addWidget(lineEdit)
        pushButton = QtGui.?PB..(centralwidget)
        pushButton.setObjectName(_fromUtf8("pushButton"))
        verticalLayout.addWidget(pushButton)
        horizontalSlider = QtGui.QSlider(centralwidget)
        horizontalSlider.setMaximum(100)
        horizontalSlider.setOrientation(?C...Qt.Horizontal)
        horizontalSlider.setObjectName(_fromUtf8("horizontalSlider"))
        verticalLayout.addWidget(horizontalSlider)
        checkBox = QtGui.QCheckBox(centralwidget)
        checkBox.setObjectName(_fromUtf8("checkBox"))
        verticalLayout.addWidget(checkBox)
        horizontalLayout_2 = QtGui.QHBoxLayout()
        horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        radioButton_2 = QtGui.QRadioButton(centralwidget)
        radioButton_2.setChecked(T..)
        radioButton_2.setObjectName(_fromUtf8("radioButton_2"))
        horizontalLayout_2.addWidget(radioButton_2)
        radioButton = QtGui.QRadioButton(centralwidget)
        radioButton.setObjectName(_fromUtf8("radioButton"))
        horizontalLayout_2.addWidget(radioButton)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        horizontalLayout_2.addItem(spacerItem)
        verticalLayout.addLayout(horizontalLayout_2)
        treeWidget = QtGui.QTreeWidget(centralwidget)
        treeWidget.setObjectName(_fromUtf8("treeWidget"))
        item_0 = QtGui.QTreeWidgetItem(treeWidget)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_3 = QtGui.QTreeWidgetItem(item_2)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        item_0 = QtGui.QTreeWidgetItem(treeWidget)
        item_0 = QtGui.QTreeWidgetItem(treeWidget)
        item_0 = QtGui.QTreeWidgetItem(treeWidget)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        verticalLayout.addWidget(treeWidget)
        comboBox = QtGui.QComboBox(centralwidget)
        comboBox.setObjectName(_fromUtf8("comboBox"))
        comboBox.addItem(_fromUtf8(""))
        comboBox.addItem(_fromUtf8(""))
        comboBox.addItem(_fromUtf8(""))
        comboBox.addItem(_fromUtf8(""))
        comboBox.addItem(_fromUtf8(""))
        verticalLayout.addWidget(comboBox)
        horizontalLayout = QtGui.QHBoxLayout()
        horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        spinBox = QtGui.QSpinBox(centralwidget)
        spinBox.setMaximum(100)
        spinBox.setObjectName(_fromUtf8("spinBox"))
        horizontalLayout.addWidget(spinBox)
        progressBar = QtGui.QProgressBar(centralwidget)
        progressBar.setProperty("value", 24)
        progressBar.setObjectName(_fromUtf8("progressBar"))
        horizontalLayout.addWidget(progressBar)
        verticalLayout.addLayout(horizontalLayout)
        MainWindow.setCentralWidget(centralwidget)
        menubar = QtGui.QMenuBar(MainWindow)
        menubar.setGeometry(?C...QRect(0, 0, 356, 21))
        menubar.setObjectName(_fromUtf8("menubar"))
        menuFile = QtGui.QMenu(menubar)
        menuFile.setObjectName(_fromUtf8("menuFile"))
        menuOpen = QtGui.QMenu(menuFile)
        menuOpen.setObjectName(_fromUtf8("menuOpen"))
        menuHelop = QtGui.QMenu(menubar)
        menuHelop.setObjectName(_fromUtf8("menuHelop"))
        MainWindow.setMenuBar(menubar)
        actionClose = QtGui.QAction(MainWindow)
        actionClose.setObjectName(_fromUtf8("actionClose"))
        actionExit = QtGui.QAction(MainWindow)
        actionExit.setObjectName(_fromUtf8("actionExit"))
        actionAbout = QtGui.QAction(MainWindow)
        actionAbout.setObjectName(_fromUtf8("actionAbout"))
        actionFile = QtGui.QAction(MainWindow)
        actionFile.setObjectName(_fromUtf8("actionFile"))
        actionProject = QtGui.QAction(MainWindow)
        actionProject.setObjectName(_fromUtf8("actionProject"))
        menuOpen.addAction(actionFile)
        menuOpen.addAction(actionProject)
        menuFile.addAction(menuOpen.menuAction())
        menuFile.addAction(actionClose)
        menuFile.addAction(actionExit)
        menuHelop.addAction(actionAbout)
        menubar.addAction(menuFile.menuAction())
        menubar.addAction(menuHelop.menuAction())

        retranslateUi(MainWindow)
        ?C...QObject.c..(horizontalSlider, ?C...SIGNAL(_fromUtf8("valueChanged(int)")), progressBar.setValue)
        ?C...QObject.c..(horizontalSlider, ?C...SIGNAL(_fromUtf8("valueChanged(int)")), spinBox.setValue)
        ?C...QObject.c..(spinBox, ?C...SIGNAL(_fromUtf8("valueChanged(int)")), horizontalSlider.setValue)
        ?C...QObject.c..(spinBox, ?C...SIGNAL(_fromUtf8("valueChanged(int)")), progressBar.setValue)
        ?C...QObject.c..(radioButton_2, ?C...SIGNAL(_fromUtf8("toggled(bool)")), treeWidget.setEnabled)
        ?C...QMetaObject.connectSlotsByName(MainWindow)

    ___ retranslateUi , MainWindow
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        pushButton.sT..(_translate("MainWindow", "Start", None))
        checkBox.sT..(_translate("MainWindow", "Show", None))
        radioButton_2.sT..(_translate("MainWindow", "Enable", None))
        radioButton.sT..(_translate("MainWindow", "Disable", None))
        treeWidget.headerItem().sT..(0, _translate("MainWindow", "1", None))
        __sortingEnabled = treeWidget.isSortingEnabled()
        treeWidget.setSortingEnabled(False)
        treeWidget.topLevelItem(0).sT..(0, _translate("MainWindow", "New Item", None))
        treeWidget.topLevelItem(0).child(0).sT..(0, _translate("MainWindow", "New Subitem", None))
        treeWidget.topLevelItem(0).child(0).child(0).sT..(0, _translate("MainWindow", "New Subitem", None))
        treeWidget.topLevelItem(0).child(0).child(0).child(0).sT..(0, _translate("MainWindow", "New Subitem", None))
        treeWidget.topLevelItem(0).child(1).sT..(0, _translate("MainWindow", "New Subitem", None))
        treeWidget.topLevelItem(0).child(2).sT..(0, _translate("MainWindow", "New Subitem", None))
        treeWidget.topLevelItem(1).sT..(0, _translate("MainWindow", "New Item", None))
        treeWidget.topLevelItem(2).sT..(0, _translate("MainWindow", "New Item", None))
        treeWidget.topLevelItem(3).sT..(0, _translate("MainWindow", "New Item", None))
        treeWidget.topLevelItem(3).child(0).sT..(0, _translate("MainWindow", "New Subitem", None))
        treeWidget.setSortingEnabled(__sortingEnabled)
        comboBox.setItemText(0, _translate("MainWindow", "New Item", None))
        comboBox.setItemText(1, _translate("MainWindow", "New Item", None))
        comboBox.setItemText(2, _translate("MainWindow", "New Item", None))
        comboBox.setItemText(3, _translate("MainWindow", "New Item", None))
        comboBox.setItemText(4, _translate("MainWindow", "New Item", None))
        menuFile.setTitle(_translate("MainWindow", "File", None))
        menuOpen.setTitle(_translate("MainWindow", "Open", None))
        menuHelop.setTitle(_translate("MainWindow", "Help", None))
        actionClose.sT..(_translate("MainWindow", "Close", None))
        actionExit.sT..(_translate("MainWindow", "Exit", None))
        actionAbout.sT..(_translate("MainWindow", "About", None))
        actionFile.sT..(_translate("MainWindow", "File", None))
        actionProject.sT..(_translate("MainWindow", "Project", None))

