# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\serge\Dropbox\nuke\compileUI\window.ui'
#
# Created: Fri Dec 15 07:09:00 2017
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

____ PySide _____ ?C.., QtGui

c_ Ui_MainWindow(object
    ___ setupUi , MainWindow
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(478, 496)
        centralwidget _ QtGui.?W..(MainWindow)
        centralwidget.setObjectName("centralwidget")
        verticalLayout _ QtGui.QVBoxLayout(centralwidget)
        verticalLayout.setObjectName("verticalLayout")
        lineEdit _ QtGui.QLineEdit(centralwidget)
        lineEdit.setObjectName("lineEdit")
        verticalLayout.addWidget(lineEdit)
        pushButton _ QtGui.?PB..(centralwidget)
        pushButton.setObjectName("pushButton")
        verticalLayout.addWidget(pushButton)
        horizontalSlider _ QtGui.QSlider(centralwidget)
        horizontalSlider.setOrientation(?C...Qt.Horizontal)
        horizontalSlider.setObjectName("horizontalSlider")
        verticalLayout.addWidget(horizontalSlider)
        checkBox _ QtGui.QCheckBox(centralwidget)
        checkBox.setObjectName("checkBox")
        verticalLayout.addWidget(checkBox)
        horizontalLayout_2 _ QtGui.QHBoxLayout()
        horizontalLayout_2.setObjectName("horizontalLayout_2")
        radioButton _ QtGui.QRadioButton(centralwidget)
        radioButton.setObjectName("radioButton")
        horizontalLayout_2.addWidget(radioButton)
        radioButton_2 _ QtGui.QRadioButton(centralwidget)
        radioButton_2.setObjectName("radioButton_2")
        horizontalLayout_2.addWidget(radioButton_2)
        verticalLayout.addLayout(horizontalLayout_2)
        treeWidget _ QtGui.QTreeWidget(centralwidget)
        treeWidget.setObjectName("treeWidget")
        item_0 _ QtGui.QTreeWidgetItem(treeWidget)
        item_1 _ QtGui.QTreeWidgetItem(item_0)
        item_2 _ QtGui.QTreeWidgetItem(item_1)
        item_3 _ QtGui.QTreeWidgetItem(item_2)
        item_3 _ QtGui.QTreeWidgetItem(item_2)
        item_3 _ QtGui.QTreeWidgetItem(item_2)
        item_2 _ QtGui.QTreeWidgetItem(item_1)
        item_1 _ QtGui.QTreeWidgetItem(item_0)
        item_1 _ QtGui.QTreeWidgetItem(item_0)
        item_0 _ QtGui.QTreeWidgetItem(treeWidget)
        item_1 _ QtGui.QTreeWidgetItem(item_0)
        verticalLayout.addWidget(treeWidget)
        comboBox _ QtGui.QComboBox(centralwidget)
        comboBox.setObjectName("comboBox")
        comboBox.addItem("")
        comboBox.addItem("")
        comboBox.addItem("")
        comboBox.addItem("")
        comboBox.addItem("")
        comboBox.addItem("")
        comboBox.addItem("")
        comboBox.addItem("")
        comboBox.addItem("")
        comboBox.addItem("")
        comboBox.addItem("")
        comboBox.addItem("")
        comboBox.addItem("")
        comboBox.addItem("")
        comboBox.addItem("")
        comboBox.addItem("")
        verticalLayout.addWidget(comboBox)
        horizontalLayout _ QtGui.QHBoxLayout()
        horizontalLayout.setObjectName("horizontalLayout")
        spinBox _ QtGui.QSpinBox(centralwidget)
        spinBox.setObjectName("spinBox")
        horizontalLayout.addWidget(spinBox)
        progressBar _ QtGui.QProgressBar(centralwidget)
        progressBar.setProperty("value", 24)
        progressBar.setObjectName("progressBar")
        horizontalLayout.addWidget(progressBar)
        verticalLayout.addLayout(horizontalLayout)
        MainWindow.setCentralWidget(centralwidget)
        menubar _ QtGui.QMenuBar(MainWindow)
        menubar.setGeometry(?C...QRect(0, 0, 478, 21))
        menubar.setObjectName("menubar")
        menuFile _ QtGui.QMenu(menubar)
        menuFile.setObjectName("menuFile")
        menuHelp _ QtGui.QMenu(menubar)
        menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(menubar)
        actionOpen _ QtGui.QAction(MainWindow)
        actionOpen.setObjectName("actionOpen")
        actionClose _ QtGui.QAction(MainWindow)
        actionClose.setObjectName("actionClose")
        actionExit _ QtGui.QAction(MainWindow)
        actionExit.setObjectName("actionExit")
        actionAbout _ QtGui.QAction(MainWindow)
        actionAbout.setObjectName("actionAbout")
        menuFile.addAction(actionOpen)
        menuFile.addAction(actionClose)
        menuFile.addAction(actionExit)
        menuHelp.addAction(actionAbout)
        menubar.addAction(menuFile.menuAction())
        menubar.addAction(menuHelp.menuAction())

        retranslateUi(MainWindow)
        ?C...QMetaObject.connectSlotsByName(MainWindow)

    ___ retranslateUi , MainWindow
        MainWindow.setWindowTitle(QtGui.?A...translate("MainWindow", "MainWindow", None, QtGui.?A...UnicodeUTF8))
        pushButton.sT..(QtGui.?A...translate("MainWindow", "PushButton", None, QtGui.?A...UnicodeUTF8))
        checkBox.sT..(QtGui.?A...translate("MainWindow", "Show", None, QtGui.?A...UnicodeUTF8))
        radioButton.sT..(QtGui.?A...translate("MainWindow", "Enable", None, QtGui.?A...UnicodeUTF8))
        radioButton_2.sT..(QtGui.?A...translate("MainWindow", "Disable", None, QtGui.?A...UnicodeUTF8))
        treeWidget.headerItem().sT..(0, QtGui.?A...translate("MainWindow", "1", None, QtGui.?A...UnicodeUTF8))
        __sortingEnabled _ treeWidget.isSortingEnabled()
        treeWidget.setSortingEnabled(False)
        treeWidget.topLevelItem(0).sT..(0, QtGui.?A...translate("MainWindow", "New Item", None, QtGui.?A...UnicodeUTF8))
        treeWidget.topLevelItem(0).child(0).sT..(0, QtGui.?A...translate("MainWindow", "New Subitem", None, QtGui.?A...UnicodeUTF8))
        treeWidget.topLevelItem(0).child(0).child(0).sT..(0, QtGui.?A...translate("MainWindow", "New Subitem", None, QtGui.?A...UnicodeUTF8))
        treeWidget.topLevelItem(0).child(0).child(0).child(0).sT..(0, QtGui.?A...translate("MainWindow", "New Subitem", None, QtGui.?A...UnicodeUTF8))
        treeWidget.topLevelItem(0).child(0).child(0).child(1).sT..(0, QtGui.?A...translate("MainWindow", "New Item", None, QtGui.?A...UnicodeUTF8))
        treeWidget.topLevelItem(0).child(0).child(0).child(2).sT..(0, QtGui.?A...translate("MainWindow", "New Item", None, QtGui.?A...UnicodeUTF8))
        treeWidget.topLevelItem(0).child(0).child(1).sT..(0, QtGui.?A...translate("MainWindow", "New Subitem", None, QtGui.?A...UnicodeUTF8))
        treeWidget.topLevelItem(0).child(1).sT..(0, QtGui.?A...translate("MainWindow", "New Subitem", None, QtGui.?A...UnicodeUTF8))
        treeWidget.topLevelItem(0).child(2).sT..(0, QtGui.?A...translate("MainWindow", "New Subitem", None, QtGui.?A...UnicodeUTF8))
        treeWidget.topLevelItem(1).sT..(0, QtGui.?A...translate("MainWindow", "New Item", None, QtGui.?A...UnicodeUTF8))
        treeWidget.topLevelItem(1).child(0).sT..(0, QtGui.?A...translate("MainWindow", "New Subitem", None, QtGui.?A...UnicodeUTF8))
        treeWidget.setSortingEnabled(__sortingEnabled)
        comboBox.setItemText(0, QtGui.?A...translate("MainWindow", "New Item", None, QtGui.?A...UnicodeUTF8))
        comboBox.setItemText(1, QtGui.?A...translate("MainWindow", "New Item", None, QtGui.?A...UnicodeUTF8))
        comboBox.setItemText(2, QtGui.?A...translate("MainWindow", "New Item", None, QtGui.?A...UnicodeUTF8))
        comboBox.setItemText(3, QtGui.?A...translate("MainWindow", "New Item", None, QtGui.?A...UnicodeUTF8))
        comboBox.setItemText(4, QtGui.?A...translate("MainWindow", "New Item", None, QtGui.?A...UnicodeUTF8))
        comboBox.setItemText(5, QtGui.?A...translate("MainWindow", "New Item", None, QtGui.?A...UnicodeUTF8))
        comboBox.setItemText(6, QtGui.?A...translate("MainWindow", "New Item", None, QtGui.?A...UnicodeUTF8))
        comboBox.setItemText(7, QtGui.?A...translate("MainWindow", "New Item", None, QtGui.?A...UnicodeUTF8))
        comboBox.setItemText(8, QtGui.?A...translate("MainWindow", "New Item", None, QtGui.?A...UnicodeUTF8))
        comboBox.setItemText(9, QtGui.?A...translate("MainWindow", "New Item", None, QtGui.?A...UnicodeUTF8))
        comboBox.setItemText(10, QtGui.?A...translate("MainWindow", "New Item", None, QtGui.?A...UnicodeUTF8))
        comboBox.setItemText(11, QtGui.?A...translate("MainWindow", "New Item", None, QtGui.?A...UnicodeUTF8))
        comboBox.setItemText(12, QtGui.?A...translate("MainWindow", "New Item", None, QtGui.?A...UnicodeUTF8))
        comboBox.setItemText(13, QtGui.?A...translate("MainWindow", "New Item", None, QtGui.?A...UnicodeUTF8))
        comboBox.setItemText(14, QtGui.?A...translate("MainWindow", "New Item", None, QtGui.?A...UnicodeUTF8))
        comboBox.setItemText(15, QtGui.?A...translate("MainWindow", "New Item", None, QtGui.?A...UnicodeUTF8))
        menuFile.setTitle(QtGui.?A...translate("MainWindow", "File", None, QtGui.?A...UnicodeUTF8))
        menuHelp.setTitle(QtGui.?A...translate("MainWindow", "Help", None, QtGui.?A...UnicodeUTF8))
        actionOpen.sT..(QtGui.?A...translate("MainWindow", "Open", None, QtGui.?A...UnicodeUTF8))
        actionClose.sT..(QtGui.?A...translate("MainWindow", "Close", None, QtGui.?A...UnicodeUTF8))
        actionExit.sT..(QtGui.?A...translate("MainWindow", "Exit", None, QtGui.?A...UnicodeUTF8))
        actionAbout.sT..(QtGui.?A...translate("MainWindow", "About", None, QtGui.?A...UnicodeUTF8))

