# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\serge\Dropbox\nuke\compileUI\window.ui'
#
# Created: Fri Dec 15 07:09:00 2017
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

____ ? _____ ?C.., ?G..

c_ Ui_MainWindow(object
    ___ setupUi , MainWindow
        MainWindow.setObjectName("MainWindow")
        MainWindow.r..(478, 496)
        centralwidget _ ?G...?W..(MainWindow)
        centralwidget.setObjectName("centralwidget")
        verticalLayout _ ?G...QVBoxLayout(centralwidget)
        verticalLayout.setObjectName("verticalLayout")
        lineEdit _ ?G...QLineEdit(centralwidget)
        lE...setObjectName("lineEdit")
        verticalLayout.addWidget(lE..)
        pB__ _ ?G...?PB..(centralwidget)
        pB__.setObjectName("pushButton")
        verticalLayout.addWidget(pB__)
        horizontalSlider _ ?G...QSlider(centralwidget)
        horizontalSlider.setOrientation(?C...__.Horizontal)
        horizontalSlider.setObjectName("horizontalSlider")
        verticalLayout.addWidget(horizontalSlider)
        checkBox _ ?G...QCheckBox(centralwidget)
        checkBox.setObjectName("checkBox")
        verticalLayout.addWidget(checkBox)
        horizontalLayout_2 _ ?G...QHBoxLayout
        horizontalLayout_2.setObjectName("horizontalLayout_2")
        radioButton _ ?G...QRadioButton(centralwidget)
        radioButton.setObjectName("radioButton")
        horizontalLayout_2.addWidget(radioButton)
        radioButton_2 _ ?G...QRadioButton(centralwidget)
        radioButton_2.setObjectName("radioButton_2")
        horizontalLayout_2.addWidget(radioButton_2)
        verticalLayout.addLayout(horizontalLayout_2)
        treeWidget _ ?G...QTreeWidget(centralwidget)
        treeWidget.setObjectName("treeWidget")
        item_0 _ ?G...QTreeWidgetItem(treeWidget)
        item_1 _ ?G...QTreeWidgetItem(item_0)
        item_2 _ ?G...QTreeWidgetItem(item_1)
        item_3 _ ?G...QTreeWidgetItem(item_2)
        item_3 _ ?G...QTreeWidgetItem(item_2)
        item_3 _ ?G...QTreeWidgetItem(item_2)
        item_2 _ ?G...QTreeWidgetItem(item_1)
        item_1 _ ?G...QTreeWidgetItem(item_0)
        item_1 _ ?G...QTreeWidgetItem(item_0)
        item_0 _ ?G...QTreeWidgetItem(treeWidget)
        item_1 _ ?G...QTreeWidgetItem(item_0)
        verticalLayout.addWidget(treeWidget)
        cB__ _ ?G...QComboBox(centralwidget)
        cB__.setObjectName("comboBox")
        cB__.aI..("")
        cB__.aI..("")
        cB__.aI..("")
        cB__.aI..("")
        cB__.aI..("")
        cB__.aI..("")
        cB__.aI..("")
        cB__.aI..("")
        cB__.aI..("")
        cB__.aI..("")
        cB__.aI..("")
        cB__.aI..("")
        cB__.aI..("")
        cB__.aI..("")
        cB__.aI..("")
        cB__.aI..("")
        verticalLayout.addWidget(cB__)
        horizontalLayout _ ?G...QHBoxLayout
        horizontalLayout.setObjectName("horizontalLayout")
        spinBox _ ?G...QSpinBox(centralwidget)
        sP__.setObjectName("spinBox")
        horizontalLayout.addWidget(sP__)
        progressBar _ ?G...QProgressBar(centralwidget)
        pB__.setProperty("value", 24)
        pB__.setObjectName("progressBar")
        horizontalLayout.addWidget(pB__)
        verticalLayout.addLayout(horizontalLayout)
        MainWindow.setCentralWidget(centralwidget)
        menubar _ ?G...QMenuBar(MainWindow)
        menubar.setGeometry(?C...?R..(0, 0, 478, 21))
        menubar.setObjectName("menubar")
        menuFile _ ?G...QMenu(menubar)
        menuFile.setObjectName("menuFile")
        menuHelp _ ?G...QMenu(menubar)
        menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(menubar)
        actionOpen _ ?G...?A__(MainWindow)
        aO__.setObjectName("actionOpen")
        actionClose _ ?G...?A__(MainWindow)
        actionClose.setObjectName("actionClose")
        actionExit _ ?G...?A__(MainWindow)
        actionExit.setObjectName("actionExit")
        actionAbout _ ?G...?A__(MainWindow)
        actionAbout.setObjectName("actionAbout")
        menuFile.addAction(aO__)
        menuFile.addAction(actionClose)
        menuFile.addAction(actionExit)
        menuHelp.addAction(actionAbout)
        menubar.addAction(menuFile.menuAction())
        menubar.addAction(menuHelp.menuAction())

        retranslateUi(MainWindow)
        ?C...QMetaObject.connectSlotsByName(MainWindow)

    ___ retranslateUi , MainWindow
        MainWindow.setWindowTitle(?G...?A...translate("MainWindow", "MainWindow", N.., ?G...?A...UnicodeUTF8))
        pB__.sT..(?G...?A...translate("MainWindow", "PushButton", N.., ?G...?A...UnicodeUTF8))
        checkBox.sT..(?G...?A...translate("MainWindow", "Show", N.., ?G...?A...UnicodeUTF8))
        radioButton.sT..(?G...?A...translate("MainWindow", "Enable", N.., ?G...?A...UnicodeUTF8))
        radioButton_2.sT..(?G...?A...translate("MainWindow", "Disable", N.., ?G...?A...UnicodeUTF8))
        treeWidget.headerItem.sT..(0, ?G...?A...translate("MainWindow", "1", N.., ?G...?A...UnicodeUTF8))
        __sortingEnabled _ treeWidget.isSortingEnabled
        treeWidget.setSortingEnabled(F..)
        treeWidget.topLevelItem(0).sT..(0, ?G...?A...translate("MainWindow", "New Item", N.., ?G...?A...UnicodeUTF8))
        treeWidget.topLevelItem(0).child(0).sT..(0, ?G...?A...translate("MainWindow", "New Subitem", N.., ?G...?A...UnicodeUTF8))
        treeWidget.topLevelItem(0).child(0).child(0).sT..(0, ?G...?A...translate("MainWindow", "New Subitem", N.., ?G...?A...UnicodeUTF8))
        treeWidget.topLevelItem(0).child(0).child(0).child(0).sT..(0, ?G...?A...translate("MainWindow", "New Subitem", N.., ?G...?A...UnicodeUTF8))
        treeWidget.topLevelItem(0).child(0).child(0).child(1).sT..(0, ?G...?A...translate("MainWindow", "New Item", N.., ?G...?A...UnicodeUTF8))
        treeWidget.topLevelItem(0).child(0).child(0).child(2).sT..(0, ?G...?A...translate("MainWindow", "New Item", N.., ?G...?A...UnicodeUTF8))
        treeWidget.topLevelItem(0).child(0).child(1).sT..(0, ?G...?A...translate("MainWindow", "New Subitem", N.., ?G...?A...UnicodeUTF8))
        treeWidget.topLevelItem(0).child(1).sT..(0, ?G...?A...translate("MainWindow", "New Subitem", N.., ?G...?A...UnicodeUTF8))
        treeWidget.topLevelItem(0).child(2).sT..(0, ?G...?A...translate("MainWindow", "New Subitem", N.., ?G...?A...UnicodeUTF8))
        treeWidget.topLevelItem(1).sT..(0, ?G...?A...translate("MainWindow", "New Item", N.., ?G...?A...UnicodeUTF8))
        treeWidget.topLevelItem(1).child(0).sT..(0, ?G...?A...translate("MainWindow", "New Subitem", N.., ?G...?A...UnicodeUTF8))
        treeWidget.setSortingEnabled(__sortingEnabled)
        cB__.setItemText(0, ?G...?A...translate("MainWindow", "New Item", N.., ?G...?A...UnicodeUTF8))
        cB__.setItemText(1, ?G...?A...translate("MainWindow", "New Item", N.., ?G...?A...UnicodeUTF8))
        cB__.setItemText(2, ?G...?A...translate("MainWindow", "New Item", N.., ?G...?A...UnicodeUTF8))
        cB__.setItemText(3, ?G...?A...translate("MainWindow", "New Item", N.., ?G...?A...UnicodeUTF8))
        cB__.setItemText(4, ?G...?A...translate("MainWindow", "New Item", N.., ?G...?A...UnicodeUTF8))
        cB__.setItemText(5, ?G...?A...translate("MainWindow", "New Item", N.., ?G...?A...UnicodeUTF8))
        cB__.setItemText(6, ?G...?A...translate("MainWindow", "New Item", N.., ?G...?A...UnicodeUTF8))
        cB__.setItemText(7, ?G...?A...translate("MainWindow", "New Item", N.., ?G...?A...UnicodeUTF8))
        cB__.setItemText(8, ?G...?A...translate("MainWindow", "New Item", N.., ?G...?A...UnicodeUTF8))
        cB__.setItemText(9, ?G...?A...translate("MainWindow", "New Item", N.., ?G...?A...UnicodeUTF8))
        cB__.setItemText(10, ?G...?A...translate("MainWindow", "New Item", N.., ?G...?A...UnicodeUTF8))
        cB__.setItemText(11, ?G...?A...translate("MainWindow", "New Item", N.., ?G...?A...UnicodeUTF8))
        cB__.setItemText(12, ?G...?A...translate("MainWindow", "New Item", N.., ?G...?A...UnicodeUTF8))
        cB__.setItemText(13, ?G...?A...translate("MainWindow", "New Item", N.., ?G...?A...UnicodeUTF8))
        cB__.setItemText(14, ?G...?A...translate("MainWindow", "New Item", N.., ?G...?A...UnicodeUTF8))
        cB__.setItemText(15, ?G...?A...translate("MainWindow", "New Item", N.., ?G...?A...UnicodeUTF8))
        menuFile.setTitle(?G...?A...translate("MainWindow", "File", N.., ?G...?A...UnicodeUTF8))
        menuHelp.setTitle(?G...?A...translate("MainWindow", "Help", N.., ?G...?A...UnicodeUTF8))
        aO__.sT..(?G...?A...translate("MainWindow", "Open", N.., ?G...?A...UnicodeUTF8))
        actionClose.sT..(?G...?A...translate("MainWindow", "Close", N.., ?G...?A...UnicodeUTF8))
        actionExit.sT..(?G...?A...translate("MainWindow", "Exit", N.., ?G...?A...UnicodeUTF8))
        actionAbout.sT..(?G...?A...translate("MainWindow", "About", N.., ?G...?A...UnicodeUTF8))

