# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\serge\Dropbox\nuke\compileUI\window.ui'
#
# Created: Fri Dec 15 07:09:00 2017
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

____ PySide _____ ?C.., ?G..

c_ Ui_MainWindow(object
    ___ setupUi , MainWindow
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(478, 496)
        centralwidget _ ?G...?W..(MainWindow)
        centralwidget.setObjectName("centralwidget")
        verticalLayout _ ?G...QVBoxLayout(centralwidget)
        verticalLayout.setObjectName("verticalLayout")
        lineEdit _ ?G...QLineEdit(centralwidget)
        lineEdit.setObjectName("lineEdit")
        verticalLayout.addWidget(lineEdit)
        pushButton _ ?G...?PB..(centralwidget)
        pushButton.setObjectName("pushButton")
        verticalLayout.addWidget(pushButton)
        horizontalSlider _ ?G...QSlider(centralwidget)
        horizontalSlider.setOrientation(?C...Qt.Horizontal)
        horizontalSlider.setObjectName("horizontalSlider")
        verticalLayout.addWidget(horizontalSlider)
        checkBox _ ?G...QCheckBox(centralwidget)
        checkBox.setObjectName("checkBox")
        verticalLayout.addWidget(checkBox)
        horizontalLayout_2 _ ?G...QHBoxLayout()
        horizontalLayout_2.setObjectName("horizontalLayout_2")
        radioButton _ ?G...QRadioButton(centralwidget)
        radioButton.setObjectName("radioButton")
        horizontalLayout_2.addWidget(radioButton)
        radioButton_2 _ ?G...QRadioButton(centralwidget)
        radioButton_2.setObjectName("radioButton_2")
        horizontalLayout_2.addWidget(radioButton_2)
        verticalLayout.addLayout(horizontalLayout_2)
        treeWidget _ ?G...QTreeWidget(centralwidget)
        treeWidget.setObjectName("treeWidget")
        item_0 _ ?G...QTreeWidgetItem(treeWidget)
        item_1 _ ?G...QTreeWidgetItem(item_0)
        item_2 _ ?G...QTreeWidgetItem(item_1)
        item_3 _ ?G...QTreeWidgetItem(item_2)
        item_3 _ ?G...QTreeWidgetItem(item_2)
        item_3 _ ?G...QTreeWidgetItem(item_2)
        item_2 _ ?G...QTreeWidgetItem(item_1)
        item_1 _ ?G...QTreeWidgetItem(item_0)
        item_1 _ ?G...QTreeWidgetItem(item_0)
        item_0 _ ?G...QTreeWidgetItem(treeWidget)
        item_1 _ ?G...QTreeWidgetItem(item_0)
        verticalLayout.addWidget(treeWidget)
        comboBox _ ?G...QComboBox(centralwidget)
        comboBox.setObjectName("comboBox")
        comboBox.addItem("")
        comboBox.addItem("")
        comboBox.addItem("")
        comboBox.addItem("")
        comboBox.addItem("")
        comboBox.addItem("")
        comboBox.addItem("")
        comboBox.addItem("")
        comboBox.addItem("")
        comboBox.addItem("")
        comboBox.addItem("")
        comboBox.addItem("")
        comboBox.addItem("")
        comboBox.addItem("")
        comboBox.addItem("")
        comboBox.addItem("")
        verticalLayout.addWidget(comboBox)
        horizontalLayout _ ?G...QHBoxLayout()
        horizontalLayout.setObjectName("horizontalLayout")
        spinBox _ ?G...QSpinBox(centralwidget)
        spinBox.setObjectName("spinBox")
        horizontalLayout.addWidget(spinBox)
        progressBar _ ?G...QProgressBar(centralwidget)
        progressBar.setProperty("value", 24)
        progressBar.setObjectName("progressBar")
        horizontalLayout.addWidget(progressBar)
        verticalLayout.addLayout(horizontalLayout)
        MainWindow.setCentralWidget(centralwidget)
        menubar _ ?G...QMenuBar(MainWindow)
        menubar.setGeometry(?C...QRect(0, 0, 478, 21))
        menubar.setObjectName("menubar")
        menuFile _ ?G...QMenu(menubar)
        menuFile.setObjectName("menuFile")
        menuHelp _ ?G...QMenu(menubar)
        menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(menubar)
        actionOpen _ ?G...QAction(MainWindow)
        actionOpen.setObjectName("actionOpen")
        actionClose _ ?G...QAction(MainWindow)
        actionClose.setObjectName("actionClose")
        actionExit _ ?G...QAction(MainWindow)
        actionExit.setObjectName("actionExit")
        actionAbout _ ?G...QAction(MainWindow)
        actionAbout.setObjectName("actionAbout")
        menuFile.addAction(actionOpen)
        menuFile.addAction(actionClose)
        menuFile.addAction(actionExit)
        menuHelp.addAction(actionAbout)
        menubar.addAction(menuFile.menuAction())
        menubar.addAction(menuHelp.menuAction())

        retranslateUi(MainWindow)
        ?C...QMetaObject.connectSlotsByName(MainWindow)

    ___ retranslateUi , MainWindow
        MainWindow.setWindowTitle(?G...?A...translate("MainWindow", "MainWindow", None, ?G...?A...UnicodeUTF8))
        pushButton.sT..(?G...?A...translate("MainWindow", "PushButton", None, ?G...?A...UnicodeUTF8))
        checkBox.sT..(?G...?A...translate("MainWindow", "Show", None, ?G...?A...UnicodeUTF8))
        radioButton.sT..(?G...?A...translate("MainWindow", "Enable", None, ?G...?A...UnicodeUTF8))
        radioButton_2.sT..(?G...?A...translate("MainWindow", "Disable", None, ?G...?A...UnicodeUTF8))
        treeWidget.headerItem().sT..(0, ?G...?A...translate("MainWindow", "1", None, ?G...?A...UnicodeUTF8))
        __sortingEnabled _ treeWidget.isSortingEnabled()
        treeWidget.setSortingEnabled(False)
        treeWidget.topLevelItem(0).sT..(0, ?G...?A...translate("MainWindow", "New Item", None, ?G...?A...UnicodeUTF8))
        treeWidget.topLevelItem(0).child(0).sT..(0, ?G...?A...translate("MainWindow", "New Subitem", None, ?G...?A...UnicodeUTF8))
        treeWidget.topLevelItem(0).child(0).child(0).sT..(0, ?G...?A...translate("MainWindow", "New Subitem", None, ?G...?A...UnicodeUTF8))
        treeWidget.topLevelItem(0).child(0).child(0).child(0).sT..(0, ?G...?A...translate("MainWindow", "New Subitem", None, ?G...?A...UnicodeUTF8))
        treeWidget.topLevelItem(0).child(0).child(0).child(1).sT..(0, ?G...?A...translate("MainWindow", "New Item", None, ?G...?A...UnicodeUTF8))
        treeWidget.topLevelItem(0).child(0).child(0).child(2).sT..(0, ?G...?A...translate("MainWindow", "New Item", None, ?G...?A...UnicodeUTF8))
        treeWidget.topLevelItem(0).child(0).child(1).sT..(0, ?G...?A...translate("MainWindow", "New Subitem", None, ?G...?A...UnicodeUTF8))
        treeWidget.topLevelItem(0).child(1).sT..(0, ?G...?A...translate("MainWindow", "New Subitem", None, ?G...?A...UnicodeUTF8))
        treeWidget.topLevelItem(0).child(2).sT..(0, ?G...?A...translate("MainWindow", "New Subitem", None, ?G...?A...UnicodeUTF8))
        treeWidget.topLevelItem(1).sT..(0, ?G...?A...translate("MainWindow", "New Item", None, ?G...?A...UnicodeUTF8))
        treeWidget.topLevelItem(1).child(0).sT..(0, ?G...?A...translate("MainWindow", "New Subitem", None, ?G...?A...UnicodeUTF8))
        treeWidget.setSortingEnabled(__sortingEnabled)
        comboBox.setItemText(0, ?G...?A...translate("MainWindow", "New Item", None, ?G...?A...UnicodeUTF8))
        comboBox.setItemText(1, ?G...?A...translate("MainWindow", "New Item", None, ?G...?A...UnicodeUTF8))
        comboBox.setItemText(2, ?G...?A...translate("MainWindow", "New Item", None, ?G...?A...UnicodeUTF8))
        comboBox.setItemText(3, ?G...?A...translate("MainWindow", "New Item", None, ?G...?A...UnicodeUTF8))
        comboBox.setItemText(4, ?G...?A...translate("MainWindow", "New Item", None, ?G...?A...UnicodeUTF8))
        comboBox.setItemText(5, ?G...?A...translate("MainWindow", "New Item", None, ?G...?A...UnicodeUTF8))
        comboBox.setItemText(6, ?G...?A...translate("MainWindow", "New Item", None, ?G...?A...UnicodeUTF8))
        comboBox.setItemText(7, ?G...?A...translate("MainWindow", "New Item", None, ?G...?A...UnicodeUTF8))
        comboBox.setItemText(8, ?G...?A...translate("MainWindow", "New Item", None, ?G...?A...UnicodeUTF8))
        comboBox.setItemText(9, ?G...?A...translate("MainWindow", "New Item", None, ?G...?A...UnicodeUTF8))
        comboBox.setItemText(10, ?G...?A...translate("MainWindow", "New Item", None, ?G...?A...UnicodeUTF8))
        comboBox.setItemText(11, ?G...?A...translate("MainWindow", "New Item", None, ?G...?A...UnicodeUTF8))
        comboBox.setItemText(12, ?G...?A...translate("MainWindow", "New Item", None, ?G...?A...UnicodeUTF8))
        comboBox.setItemText(13, ?G...?A...translate("MainWindow", "New Item", None, ?G...?A...UnicodeUTF8))
        comboBox.setItemText(14, ?G...?A...translate("MainWindow", "New Item", None, ?G...?A...UnicodeUTF8))
        comboBox.setItemText(15, ?G...?A...translate("MainWindow", "New Item", None, ?G...?A...UnicodeUTF8))
        menuFile.setTitle(?G...?A...translate("MainWindow", "File", None, ?G...?A...UnicodeUTF8))
        menuHelp.setTitle(?G...?A...translate("MainWindow", "Help", None, ?G...?A...UnicodeUTF8))
        actionOpen.sT..(?G...?A...translate("MainWindow", "Open", None, ?G...?A...UnicodeUTF8))
        actionClose.sT..(?G...?A...translate("MainWindow", "Close", None, ?G...?A...UnicodeUTF8))
        actionExit.sT..(?G...?A...translate("MainWindow", "Exit", None, ?G...?A...UnicodeUTF8))
        actionAbout.sT..(?G...?A...translate("MainWindow", "About", None, ?G...?A...UnicodeUTF8))

