# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\serge\Dropbox\nuke\compileUI\window.ui'
#
# Created: Fri Dec 15 07:08:59 2017
#      by: PyQt4 UI code generator 4.10.1
#
# WARNING! All changes made in this file will be lost!

____ PyQt4 _____ ?C.., QtGui

try:
    _fromUtf8 = ?C...QString.fromUtf8
except AttributeError:
    ___ _fromUtf8(s
        return s

try:
    _encoding = QtGui.?A...UnicodeUTF8
    ___ _translate(context, text, disambig
        return QtGui.?A...translate(context, text, disambig, _encoding)
except AttributeError:
    ___ _translate(context, text, disambig
        return QtGui.?A...translate(context, text, disambig)

c_ Ui_MainWindow(object
    ___ setupUi , MainWindow
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(478, 496)
        centralwidget = QtGui.?W..(MainWindow)
        centralwidget.setObjectName(_fromUtf8("centralwidget"))
        verticalLayout = QtGui.QVBoxLayout(centralwidget)
        verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        lineEdit = QtGui.QLineEdit(centralwidget)
        lineEdit.setObjectName(_fromUtf8("lineEdit"))
        verticalLayout.addWidget(lineEdit)
        pushButton = QtGui.?PB..(centralwidget)
        pushButton.setObjectName(_fromUtf8("pushButton"))
        verticalLayout.addWidget(pushButton)
        horizontalSlider = QtGui.QSlider(centralwidget)
        horizontalSlider.setOrientation(?C...Qt.Horizontal)
        horizontalSlider.setObjectName(_fromUtf8("horizontalSlider"))
        verticalLayout.addWidget(horizontalSlider)
        checkBox = QtGui.QCheckBox(centralwidget)
        checkBox.setObjectName(_fromUtf8("checkBox"))
        verticalLayout.addWidget(checkBox)
        horizontalLayout_2 = QtGui.QHBoxLayout()
        horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        radioButton = QtGui.QRadioButton(centralwidget)
        radioButton.setObjectName(_fromUtf8("radioButton"))
        horizontalLayout_2.addWidget(radioButton)
        radioButton_2 = QtGui.QRadioButton(centralwidget)
        radioButton_2.setObjectName(_fromUtf8("radioButton_2"))
        horizontalLayout_2.addWidget(radioButton_2)
        verticalLayout.addLayout(horizontalLayout_2)
        treeWidget = QtGui.QTreeWidget(centralwidget)
        treeWidget.setObjectName(_fromUtf8("treeWidget"))
        item_0 = QtGui.QTreeWidgetItem(treeWidget)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_3 = QtGui.QTreeWidgetItem(item_2)
        item_3 = QtGui.QTreeWidgetItem(item_2)
        item_3 = QtGui.QTreeWidgetItem(item_2)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        item_0 = QtGui.QTreeWidgetItem(treeWidget)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        verticalLayout.addWidget(treeWidget)
        comboBox = QtGui.QComboBox(centralwidget)
        comboBox.setObjectName(_fromUtf8("comboBox"))
        comboBox.addItem(_fromUtf8(""))
        comboBox.addItem(_fromUtf8(""))
        comboBox.addItem(_fromUtf8(""))
        comboBox.addItem(_fromUtf8(""))
        comboBox.addItem(_fromUtf8(""))
        comboBox.addItem(_fromUtf8(""))
        comboBox.addItem(_fromUtf8(""))
        comboBox.addItem(_fromUtf8(""))
        comboBox.addItem(_fromUtf8(""))
        comboBox.addItem(_fromUtf8(""))
        comboBox.addItem(_fromUtf8(""))
        comboBox.addItem(_fromUtf8(""))
        comboBox.addItem(_fromUtf8(""))
        comboBox.addItem(_fromUtf8(""))
        comboBox.addItem(_fromUtf8(""))
        comboBox.addItem(_fromUtf8(""))
        verticalLayout.addWidget(comboBox)
        horizontalLayout = QtGui.QHBoxLayout()
        horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        spinBox = QtGui.QSpinBox(centralwidget)
        spinBox.setObjectName(_fromUtf8("spinBox"))
        horizontalLayout.addWidget(spinBox)
        progressBar = QtGui.QProgressBar(centralwidget)
        progressBar.setProperty("value", 24)
        progressBar.setObjectName(_fromUtf8("progressBar"))
        horizontalLayout.addWidget(progressBar)
        verticalLayout.addLayout(horizontalLayout)
        MainWindow.setCentralWidget(centralwidget)
        menubar = QtGui.QMenuBar(MainWindow)
        menubar.setGeometry(?C...QRect(0, 0, 478, 21))
        menubar.setObjectName(_fromUtf8("menubar"))
        menuFile = QtGui.QMenu(menubar)
        menuFile.setObjectName(_fromUtf8("menuFile"))
        menuHelp = QtGui.QMenu(menubar)
        menuHelp.setObjectName(_fromUtf8("menuHelp"))
        MainWindow.setMenuBar(menubar)
        actionOpen = QtGui.QAction(MainWindow)
        actionOpen.setObjectName(_fromUtf8("actionOpen"))
        actionClose = QtGui.QAction(MainWindow)
        actionClose.setObjectName(_fromUtf8("actionClose"))
        actionExit = QtGui.QAction(MainWindow)
        actionExit.setObjectName(_fromUtf8("actionExit"))
        actionAbout = QtGui.QAction(MainWindow)
        actionAbout.setObjectName(_fromUtf8("actionAbout"))
        menuFile.addAction(actionOpen)
        menuFile.addAction(actionClose)
        menuFile.addAction(actionExit)
        menuHelp.addAction(actionAbout)
        menubar.addAction(menuFile.menuAction())
        menubar.addAction(menuHelp.menuAction())

        retranslateUi(MainWindow)
        ?C...QMetaObject.connectSlotsByName(MainWindow)

    ___ retranslateUi , MainWindow
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        pushButton.sT..(_translate("MainWindow", "PushButton", None))
        checkBox.sT..(_translate("MainWindow", "Show", None))
        radioButton.sT..(_translate("MainWindow", "Enable", None))
        radioButton_2.sT..(_translate("MainWindow", "Disable", None))
        treeWidget.headerItem().sT..(0, _translate("MainWindow", "1", None))
        __sortingEnabled = treeWidget.isSortingEnabled()
        treeWidget.setSortingEnabled(False)
        treeWidget.topLevelItem(0).sT..(0, _translate("MainWindow", "New Item", None))
        treeWidget.topLevelItem(0).child(0).sT..(0, _translate("MainWindow", "New Subitem", None))
        treeWidget.topLevelItem(0).child(0).child(0).sT..(0, _translate("MainWindow", "New Subitem", None))
        treeWidget.topLevelItem(0).child(0).child(0).child(0).sT..(0, _translate("MainWindow", "New Subitem", None))
        treeWidget.topLevelItem(0).child(0).child(0).child(1).sT..(0, _translate("MainWindow", "New Item", None))
        treeWidget.topLevelItem(0).child(0).child(0).child(2).sT..(0, _translate("MainWindow", "New Item", None))
        treeWidget.topLevelItem(0).child(0).child(1).sT..(0, _translate("MainWindow", "New Subitem", None))
        treeWidget.topLevelItem(0).child(1).sT..(0, _translate("MainWindow", "New Subitem", None))
        treeWidget.topLevelItem(0).child(2).sT..(0, _translate("MainWindow", "New Subitem", None))
        treeWidget.topLevelItem(1).sT..(0, _translate("MainWindow", "New Item", None))
        treeWidget.topLevelItem(1).child(0).sT..(0, _translate("MainWindow", "New Subitem", None))
        treeWidget.setSortingEnabled(__sortingEnabled)
        comboBox.setItemText(0, _translate("MainWindow", "New Item", None))
        comboBox.setItemText(1, _translate("MainWindow", "New Item", None))
        comboBox.setItemText(2, _translate("MainWindow", "New Item", None))
        comboBox.setItemText(3, _translate("MainWindow", "New Item", None))
        comboBox.setItemText(4, _translate("MainWindow", "New Item", None))
        comboBox.setItemText(5, _translate("MainWindow", "New Item", None))
        comboBox.setItemText(6, _translate("MainWindow", "New Item", None))
        comboBox.setItemText(7, _translate("MainWindow", "New Item", None))
        comboBox.setItemText(8, _translate("MainWindow", "New Item", None))
        comboBox.setItemText(9, _translate("MainWindow", "New Item", None))
        comboBox.setItemText(10, _translate("MainWindow", "New Item", None))
        comboBox.setItemText(11, _translate("MainWindow", "New Item", None))
        comboBox.setItemText(12, _translate("MainWindow", "New Item", None))
        comboBox.setItemText(13, _translate("MainWindow", "New Item", None))
        comboBox.setItemText(14, _translate("MainWindow", "New Item", None))
        comboBox.setItemText(15, _translate("MainWindow", "New Item", None))
        menuFile.setTitle(_translate("MainWindow", "File", None))
        menuHelp.setTitle(_translate("MainWindow", "Help", None))
        actionOpen.sT..(_translate("MainWindow", "Open", None))
        actionClose.sT..(_translate("MainWindow", "Close", None))
        actionExit.sT..(_translate("MainWindow", "Exit", None))
        actionAbout.sT..(_translate("MainWindow", "About", None))

