# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'camera.ui'
#
# Created: Fri Jun 28 12:10:56 2013
#      by: PyQt5 UI code generator 5.0-snapshot-478d7f271b71
#
# WARNING! All changes made in this file will be lost!

____ ? ______ ?C.., ?G.., ?W..

c_ Ui_Camera o..
    ___ setupUi  Camera):
        Camera.setObjectName("Camera")
        Camera.r..(668, 422)
        centralwidget _ ?W...?W..(Camera)
        centralwidget.setObjectName("centralwidget")
        gridLayout_3 _ ?W...QGridLayout(centralwidget)
        gridLayout_3.setObjectName("gridLayout_3")
        stackedWidget _ ?W...?SW..(centralwidget)
        sizePolicy _ ?W...?SP..(?W...?SP...Preferred, ?W...?SP...Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(stackedWidget.sizePolicy().hasHeightForWidth())
        stackedWidget.sSP..(sizePolicy)
        palette _ ?G...?P..()
        brush _ ?G...?B..(?G...?C..(255, 255, 255))
        brush.sS..(?C...__.SolidPattern)
        palette.sB..(?G...?P...Active, ?G...?P...Base, brush)
        brush _ ?G...?B..(?G...?C..(145, 145, 145))
        brush.sS..(?C...__.SolidPattern)
        palette.sB..(?G...?P...Active, ?G...?P...Window, brush)
        brush _ ?G...?B..(?G...?C..(255, 255, 255))
        brush.sS..(?C...__.SolidPattern)
        palette.sB..(?G...?P...Inactive, ?G...?P...Base, brush)
        brush _ ?G...?B..(?G...?C..(145, 145, 145))
        brush.sS..(?C...__.SolidPattern)
        palette.sB..(?G...?P...Inactive, ?G...?P...Window, brush)
        brush _ ?G...?B..(?G...?C..(145, 145, 145))
        brush.sS..(?C...__.SolidPattern)
        palette.sB..(?G...?P...Disabled, ?G...?P...Base, brush)
        brush _ ?G...?B..(?G...?C..(145, 145, 145))
        brush.sS..(?C...__.SolidPattern)
        palette.sB..(?G...?P...Disabled, ?G...?P...Window, brush)
        stackedWidget.sP..(palette)
        stackedWidget.setObjectName("stackedWidget")
        viewfinderPage _ ?W...?W..
        viewfinderPage.setObjectName("viewfinderPage")
        gridLayout_5 _ ?W...QGridLayout(viewfinderPage)
        gridLayout_5.setObjectName("gridLayout_5")
        viewfinder _ QCameraViewfinder(viewfinderPage)
        viewfinder.setObjectName("viewfinder")
        gridLayout_5.aW..(viewfinder, 0, 0, 1, 1)
        stackedWidget.aW..(viewfinderPage)
        previewPage _ ?W...?W..
        previewPage.setObjectName("previewPage")
        gridLayout_4 _ ?W...QGridLayout(previewPage)
        gridLayout_4.setObjectName("gridLayout_4")
        lastImagePreviewLabel _ ?W...?L..(previewPage)
        sizePolicy _ ?W...?SP..(?W...?SP...Preferred, ?W...?SP...ME..)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(lastImagePreviewLabel.sizePolicy().hasHeightForWidth())
        lastImagePreviewLabel.sSP..(sizePolicy)
        lastImagePreviewLabel.setFrameShape(?W...QFrame.Box)
        lastImagePreviewLabel.sT..("")
        lastImagePreviewLabel.setObjectName("lastImagePreviewLabel")
        gridLayout_4.aW..(lastImagePreviewLabel, 0, 0, 1, 1)
        stackedWidget.aW..(previewPage)
        gridLayout_3.aW..(stackedWidget, 0, 0, 3, 1)
        lockButton _ ?W...?PB..(centralwidget)
        lockButton.setObjectName("lockButton")
        gridLayout_3.aW..(lockButton, 1, 1, 1, 2)
        captureWidget _ ?W...?TW..(centralwidget)
        captureWidget.setObjectName("captureWidget")
        tab_2 _ ?W...?W..
        tab_2.setObjectName("tab_2")
        gridLayout _ ?W...QGridLayout(tab_2)
        gridLayout.setObjectName("gridLayout")
        takeImageButton _ ?W...?PB..(tab_2)
        takeImageButton.setObjectName("takeImageButton")
        gridLayout.aW..(takeImageButton, 0, 0, 1, 1)
        spacerItem _ ?W...?SI..(20, 161, ?W...?SP...Minimum, ?W...?SP...E..)
        gridLayout.aI..(spacerItem, 1, 0, 1, 1)
        label _ ?W...?L..(tab_2)
        label.setObjectName("label")
        gridLayout.aW..(label, 2, 0, 1, 1)
        exposureCompensation _ ?W...?S..(tab_2)
        exposureCompensation.setMinimum(-4)
        exposureCompensation.sM..(4)
        exposureCompensation.setPageStep(2)
        exposureCompensation.setOrientation(?C...__.H..)
        exposureCompensation.setTickPosition(?W...?S...TicksAbove)
        exposureCompensation.setObjectName("exposureCompensation")
        gridLayout.aW..(exposureCompensation, 3, 0, 1, 1)
        captureWidget.aT..(tab_2, "")
        tab _ ?W...?W..
        tab.setObjectName("tab")
        gridLayout_2 _ ?W...QGridLayout(tab)
        gridLayout_2.setObjectName("gridLayout_2")
        recordButton _ ?W...?PB..(tab)
        recordButton.setObjectName("recordButton")
        gridLayout_2.aW..(recordButton, 0, 0, 1, 1)
        pauseButton _ ?W...?PB..(tab)
        pauseButton.setObjectName("pauseButton")
        gridLayout_2.aW..(pauseButton, 1, 0, 1, 1)
        stopButton _ ?W...?PB..(tab)
        stopButton.setObjectName("stopButton")
        gridLayout_2.aW..(stopButton, 2, 0, 1, 1)
        spacerItem1 _ ?W...?SI..(20, 76, ?W...?SP...Minimum, ?W...?SP...E..)
        gridLayout_2.aI..(spacerItem1, 3, 0, 1, 1)
        muteButton _ ?W...?PB..(tab)
        muteButton.setCheckable( st.
        muteButton.setObjectName("muteButton")
        gridLayout_2.aW..(muteButton, 4, 0, 1, 1)
        captureWidget.aT..(tab, "")
        gridLayout_3.aW..(captureWidget, 2, 1, 1, 2)
        Camera.sCW..(centralwidget)
        menubar _ ?W...QMenuBar(Camera)
        menubar.setGeometry(?C...QRect(0, 0, 668, 29))
        menubar.setObjectName("menubar")
        menuFile _ ?W...?M..(menubar)
        menuFile.setObjectName("menuFile")
        menuDevices _ ?W...?M..(menubar)
        menuDevices.setObjectName("menuDevices")
        Camera.setMenuBar(menubar)
        statusbar _ ?W...QStatusBar(Camera)
        statusbar.setObjectName("statusbar")
        Camera.sSB..(statusbar)
        actionExit _ ?W...?A..(Camera)
        actionExit.setObjectName("actionExit")
        actionStartCamera _ ?W...?A..(Camera)
        actionStartCamera.setObjectName("actionStartCamera")
        actionStopCamera _ ?W...?A..(Camera)
        actionStopCamera.setObjectName("actionStopCamera")
        actionSettings _ ?W...?A..(Camera)
        actionSettings.setObjectName("actionSettings")
        menuFile.aA..(actionStartCamera)
        menuFile.aA..(actionStopCamera)
        menuFile.aS..)
        menuFile.aA..(actionSettings)
        menuFile.aS..)
        menuFile.aA..(actionExit)
        menubar.aA..(menuFile.menuAction())
        menubar.aA..(menuDevices.menuAction())

        retranslateUi(Camera)
        stackedWidget.sCI..(0)
        captureWidget.sCI..(0)
        recordButton.c__.c..(Camera.record)
        stopButton.c__.c..(Camera.stop)
        pauseButton.c__.c..(Camera.pause)
        actionExit.t__.c..(Camera.close)
        takeImageButton.c__.c..(Camera.takeImage)
        lockButton.c__.c..(Camera.toggleLock)
        muteButton.t__['bool'].c..(Camera.setMuted)
        exposureCompensation.valueChanged['int'].c..(Camera.setExposureCompensation)
        actionSettings.t__.c..(Camera.configureCaptureSettings)
        actionStartCamera.t__.c..(Camera.startCamera)
        actionStopCamera.t__.c..(Camera.stopCamera)
        ?C...QMetaObject.connectSlotsByName(Camera)

    ___ retranslateUi  Camera):
        _translate _ ?C... ?CA...translate
        Camera.sWT..(_translate("Camera", "Camera"))
        lockButton.sT..(_translate("Camera", "Focus"))
        takeImageButton.sT..(_translate("Camera", "Capture Photo"))
        label.sT..(_translate("Camera", "Exposure Compensation:"))
        captureWidget.setTabText(captureWidget.indexOf(tab_2), _translate("Camera", "Image"))
        recordButton.sT..(_translate("Camera", "Record"))
        pauseButton.sT..(_translate("Camera", "Pause"))
        stopButton.sT..(_translate("Camera", "Stop"))
        muteButton.sT..(_translate("Camera", "Mute"))
        captureWidget.setTabText(captureWidget.indexOf(tab), _translate("Camera", "Video"))
        menuFile.setTitle(_translate("Camera", "File"))
        menuDevices.setTitle(_translate("Camera", "Devices"))
        actionExit.sT..(_translate("Camera", "Exit"))
        actionStartCamera.sT..(_translate("Camera", "Start Camera"))
        actionStopCamera.sT..(_translate("Camera", "Stop Camera"))
        actionSettings.sT..(_translate("Camera", "Settings"))

____ ?.?MW.. ______ QCameraViewfinder
