# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'camera.ui'
#
# Created: Fri Jun 28 12:10:56 2013
#      by: PyQt5 UI code generator 5.0-snapshot-478d7f271b71
#
# WARNING! All changes made in this file will be lost!

____ ? ______ QtCore, ?G.., ?W..

c_ Ui_Camera(object):
    ___ setupUi  Camera):
        Camera.setObjectName("Camera")
        Camera.resize(668, 422)
        self.centralwidget _ ?W...QWidget(Camera)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_3 _ ?W...QGridLayout(self.centralwidget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.stackedWidget _ ?W...QStackedWidget(self.centralwidget)
        sizePolicy _ ?W...QSizePolicy(?W...QSizePolicy.Preferred, ?W...QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stackedWidget.sizePolicy().hasHeightForWidth())
        self.stackedWidget.setSizePolicy(sizePolicy)
        palette _ ?G...QPalette()
        brush _ ?G...QBrush(?G...QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(?G...QPalette.Active, ?G...QPalette.Base, brush)
        brush _ ?G...QBrush(?G...QColor(145, 145, 145))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(?G...QPalette.Active, ?G...QPalette.Window, brush)
        brush _ ?G...QBrush(?G...QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(?G...QPalette.Inactive, ?G...QPalette.Base, brush)
        brush _ ?G...QBrush(?G...QColor(145, 145, 145))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(?G...QPalette.Inactive, ?G...QPalette.Window, brush)
        brush _ ?G...QBrush(?G...QColor(145, 145, 145))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(?G...QPalette.Disabled, ?G...QPalette.Base, brush)
        brush _ ?G...QBrush(?G...QColor(145, 145, 145))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(?G...QPalette.Disabled, ?G...QPalette.Window, brush)
        self.stackedWidget.setPalette(palette)
        self.stackedWidget.setObjectName("stackedWidget")
        self.viewfinderPage _ ?W...QWidget()
        self.viewfinderPage.setObjectName("viewfinderPage")
        self.gridLayout_5 _ ?W...QGridLayout(self.viewfinderPage)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.viewfinder _ QCameraViewfinder(self.viewfinderPage)
        self.viewfinder.setObjectName("viewfinder")
        self.gridLayout_5.addWidget(self.viewfinder, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.viewfinderPage)
        self.previewPage _ ?W...QWidget()
        self.previewPage.setObjectName("previewPage")
        self.gridLayout_4 _ ?W...QGridLayout(self.previewPage)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.lastImagePreviewLabel _ ?W...QLabel(self.previewPage)
        sizePolicy _ ?W...QSizePolicy(?W...QSizePolicy.Preferred, ?W...QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lastImagePreviewLabel.sizePolicy().hasHeightForWidth())
        self.lastImagePreviewLabel.setSizePolicy(sizePolicy)
        self.lastImagePreviewLabel.setFrameShape(?W...QFrame.Box)
        self.lastImagePreviewLabel.sT..("")
        self.lastImagePreviewLabel.setObjectName("lastImagePreviewLabel")
        self.gridLayout_4.addWidget(self.lastImagePreviewLabel, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.previewPage)
        self.gridLayout_3.addWidget(self.stackedWidget, 0, 0, 3, 1)
        self.lockButton _ ?W...?PB..(self.centralwidget)
        self.lockButton.setObjectName("lockButton")
        self.gridLayout_3.addWidget(self.lockButton, 1, 1, 1, 2)
        self.captureWidget _ ?W...QTabWidget(self.centralwidget)
        self.captureWidget.setObjectName("captureWidget")
        self.tab_2 _ ?W...QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout _ ?W...QGridLayout(self.tab_2)
        self.gridLayout.setObjectName("gridLayout")
        self.takeImageButton _ ?W...?PB..(self.tab_2)
        self.takeImageButton.setObjectName("takeImageButton")
        self.gridLayout.addWidget(self.takeImageButton, 0, 0, 1, 1)
        spacerItem _ ?W...QSpacerItem(20, 161, ?W...QSizePolicy.Minimum, ?W...QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 1, 0, 1, 1)
        self.label _ ?W...QLabel(self.tab_2)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 2, 0, 1, 1)
        self.exposureCompensation _ ?W...QSlider(self.tab_2)
        self.exposureCompensation.setMinimum(-4)
        self.exposureCompensation.setMaximum(4)
        self.exposureCompensation.setPageStep(2)
        self.exposureCompensation.setOrientation(QtCore.Qt.Horizontal)
        self.exposureCompensation.setTickPosition(?W...QSlider.TicksAbove)
        self.exposureCompensation.setObjectName("exposureCompensation")
        self.gridLayout.addWidget(self.exposureCompensation, 3, 0, 1, 1)
        self.captureWidget.addTab(self.tab_2, "")
        self.tab _ ?W...QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_2 _ ?W...QGridLayout(self.tab)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.recordButton _ ?W...?PB..(self.tab)
        self.recordButton.setObjectName("recordButton")
        self.gridLayout_2.addWidget(self.recordButton, 0, 0, 1, 1)
        self.pauseButton _ ?W...?PB..(self.tab)
        self.pauseButton.setObjectName("pauseButton")
        self.gridLayout_2.addWidget(self.pauseButton, 1, 0, 1, 1)
        self.stopButton _ ?W...?PB..(self.tab)
        self.stopButton.setObjectName("stopButton")
        self.gridLayout_2.addWidget(self.stopButton, 2, 0, 1, 1)
        spacerItem1 _ ?W...QSpacerItem(20, 76, ?W...QSizePolicy.Minimum, ?W...QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem1, 3, 0, 1, 1)
        self.muteButton _ ?W...?PB..(self.tab)
        self.muteButton.setCheckable(True)
        self.muteButton.setObjectName("muteButton")
        self.gridLayout_2.addWidget(self.muteButton, 4, 0, 1, 1)
        self.captureWidget.addTab(self.tab, "")
        self.gridLayout_3.addWidget(self.captureWidget, 2, 1, 1, 2)
        Camera.sCW..(self.centralwidget)
        self.menubar _ ?W...QMenuBar(Camera)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 668, 29))
        self.menubar.setObjectName("menubar")
        self.menuFile _ ?W...QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuDevices _ ?W...QMenu(self.menubar)
        self.menuDevices.setObjectName("menuDevices")
        Camera.setMenuBar(self.menubar)
        self.statusbar _ ?W...QStatusBar(Camera)
        self.statusbar.setObjectName("statusbar")
        Camera.setStatusBar(self.statusbar)
        self.actionExit _ ?W...?A..(Camera)
        self.actionExit.setObjectName("actionExit")
        self.actionStartCamera _ ?W...?A..(Camera)
        self.actionStartCamera.setObjectName("actionStartCamera")
        self.actionStopCamera _ ?W...?A..(Camera)
        self.actionStopCamera.setObjectName("actionStopCamera")
        self.actionSettings _ ?W...?A..(Camera)
        self.actionSettings.setObjectName("actionSettings")
        self.menuFile.aA..(self.actionStartCamera)
        self.menuFile.aA..(self.actionStopCamera)
        self.menuFile.addSeparator()
        self.menuFile.aA..(self.actionSettings)
        self.menuFile.addSeparator()
        self.menuFile.aA..(self.actionExit)
        self.menubar.aA..(self.menuFile.menuAction())
        self.menubar.aA..(self.menuDevices.menuAction())

        self.retranslateUi(Camera)
        self.stackedWidget.setCurrentIndex(0)
        self.captureWidget.setCurrentIndex(0)
        self.recordButton.c__.c..(Camera.record)
        self.stopButton.c__.c..(Camera.stop)
        self.pauseButton.c__.c..(Camera.pause)
        self.actionExit.t__.c..(Camera.close)
        self.takeImageButton.c__.c..(Camera.takeImage)
        self.lockButton.c__.c..(Camera.toggleLock)
        self.muteButton.toggled['bool'].c..(Camera.setMuted)
        self.exposureCompensation.valueChanged['int'].c..(Camera.setExposureCompensation)
        self.actionSettings.t__.c..(Camera.configureCaptureSettings)
        self.actionStartCamera.t__.c..(Camera.startCamera)
        self.actionStopCamera.t__.c..(Camera.stopCamera)
        QtCore.QMetaObject.connectSlotsByName(Camera)

    ___ retranslateUi  Camera):
        _translate _ QtCore.QCoreApplication.translate
        Camera.setWindowTitle(_translate("Camera", "Camera"))
        self.lockButton.sT..(_translate("Camera", "Focus"))
        self.takeImageButton.sT..(_translate("Camera", "Capture Photo"))
        self.label.sT..(_translate("Camera", "Exposure Compensation:"))
        self.captureWidget.setTabText(self.captureWidget.indexOf(self.tab_2), _translate("Camera", "Image"))
        self.recordButton.sT..(_translate("Camera", "Record"))
        self.pauseButton.sT..(_translate("Camera", "Pause"))
        self.stopButton.sT..(_translate("Camera", "Stop"))
        self.muteButton.sT..(_translate("Camera", "Mute"))
        self.captureWidget.setTabText(self.captureWidget.indexOf(self.tab), _translate("Camera", "Video"))
        self.menuFile.setTitle(_translate("Camera", "File"))
        self.menuDevices.setTitle(_translate("Camera", "Devices"))
        self.actionExit.sT..(_translate("Camera", "Exit"))
        self.actionStartCamera.sT..(_translate("Camera", "Start Camera"))
        self.actionStopCamera.sT..(_translate("Camera", "Stop Camera"))
        self.actionSettings.sT..(_translate("Camera", "Settings"))

____ ?.QtMultimediaWidgets ______ QCameraViewfinder
