# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'videosettings.ui'
#
# Created: Fri Jun 28 11:48:14 2013
#      by: PyQt5 UI code generator 5.0-snapshot-478d7f271b71
#
# WARNING! All changes made in this file will be lost!

____ ? ______ ?C.., ?G.., ?W..

c_ Ui_VideoSettingsUi(object):
    ___ setupUi  VideoSettingsUi):
        VideoSettingsUi.setObjectName("VideoSettingsUi")
        VideoSettingsUi.resize(561, 369)
        self.gridLayout_4 _ ?W...QGridLayout(VideoSettingsUi)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.scrollArea _ ?W...QScrollArea(VideoSettingsUi)
        self.scrollArea.setFrameShape(?W...QFrame.NoFrame)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents _ ?W...QWidget()
        self.scrollAreaWidgetContents.setGeometry(?C...QRect(0, 0, 543, 250))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_3 _ ?W...QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.groupBox _ ?W...QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout _ ?W...QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 _ ?W...QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 2)
        self.audioCodecBox _ ?W...QComboBox(self.groupBox)
        self.audioCodecBox.setObjectName("audioCodecBox")
        self.gridLayout.addWidget(self.audioCodecBox, 1, 0, 1, 2)
        self.label_5 _ ?W...QLabel(self.groupBox)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 2, 0, 1, 2)
        self.audioSampleRateBox _ ?W...QComboBox(self.groupBox)
        self.audioSampleRateBox.setObjectName("audioSampleRateBox")
        self.gridLayout.addWidget(self.audioSampleRateBox, 3, 0, 1, 2)
        self.label_3 _ ?W...QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 4, 0, 1, 1)
        self.audioQualitySlider _ ?W...QSlider(self.groupBox)
        self.audioQualitySlider.setMaximum(4)
        self.audioQualitySlider.setOrientation(?C...__.Horizontal)
        self.audioQualitySlider.setObjectName("audioQualitySlider")
        self.gridLayout.addWidget(self.audioQualitySlider, 4, 1, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox, 0, 0, 1, 1)
        self.groupBox_2 _ ?W...QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_2 _ ?W...QGridLayout(self.groupBox_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_8 _ ?W...QLabel(self.groupBox_2)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 0, 0, 1, 2)
        self.videoResolutionBox _ ?W...QComboBox(self.groupBox_2)
        self.videoResolutionBox.setObjectName("videoResolutionBox")
        self.gridLayout_2.addWidget(self.videoResolutionBox, 1, 0, 1, 2)
        self.label_9 _ ?W...QLabel(self.groupBox_2)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 2, 0, 1, 2)
        self.videoFramerateBox _ ?W...QComboBox(self.groupBox_2)
        self.videoFramerateBox.setObjectName("videoFramerateBox")
        self.gridLayout_2.addWidget(self.videoFramerateBox, 3, 0, 1, 2)
        self.label_6 _ ?W...QLabel(self.groupBox_2)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 4, 0, 1, 2)
        self.videoCodecBox _ ?W...QComboBox(self.groupBox_2)
        self.videoCodecBox.setObjectName("videoCodecBox")
        self.gridLayout_2.addWidget(self.videoCodecBox, 5, 0, 1, 2)
        self.label_7 _ ?W...QLabel(self.groupBox_2)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 6, 0, 1, 1)
        self.videoQualitySlider _ ?W...QSlider(self.groupBox_2)
        self.videoQualitySlider.setMaximum(4)
        self.videoQualitySlider.setOrientation(?C...__.Horizontal)
        self.videoQualitySlider.setObjectName("videoQualitySlider")
        self.gridLayout_2.addWidget(self.videoQualitySlider, 6, 1, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox_2, 0, 1, 3, 1)
        self.label_4 _ ?W...QLabel(self.scrollAreaWidgetContents)
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 1, 0, 1, 1)
        self.containerFormatBox _ ?W...QComboBox(self.scrollAreaWidgetContents)
        self.containerFormatBox.setObjectName("containerFormatBox")
        self.gridLayout_3.addWidget(self.containerFormatBox, 2, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_4.addWidget(self.scrollArea, 0, 0, 1, 1)
        spacerItem _ ?W...QSpacerItem(20, 14, ?W...QSizePolicy.Minimum, ?W...QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem, 1, 0, 1, 1)
        self.buttonBox _ ?W...QDialogButtonBox(VideoSettingsUi)
        self.buttonBox.setOrientation(?C...__.Horizontal)
        self.buttonBox.setStandardButtons(?W...QDialogButtonBox.Cancel|?W...QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout_4.addWidget(self.buttonBox, 2, 0, 1, 1)

        self.retranslateUi(VideoSettingsUi)
        self.buttonBox.accepted.c..(VideoSettingsUi.accept)
        self.buttonBox.rejected.c..(VideoSettingsUi.reject)
        ?C...QMetaObject.connectSlotsByName(VideoSettingsUi)

    ___ retranslateUi  VideoSettingsUi):
        _translate _ ?C...QCoreApplication.translate
        VideoSettingsUi.setWindowTitle(_translate("VideoSettingsUi", "Dialog"))
        self.groupBox.setTitle(_translate("VideoSettingsUi", "Audio"))
        self.label_2.sT..(_translate("VideoSettingsUi", "Audio Codec:"))
        self.label_5.sT..(_translate("VideoSettingsUi", "Sample Rate:"))
        self.label_3.sT..(_translate("VideoSettingsUi", "Quality:"))
        self.groupBox_2.setTitle(_translate("VideoSettingsUi", "Video"))
        self.label_8.sT..(_translate("VideoSettingsUi", "Resolution:"))
        self.label_9.sT..(_translate("VideoSettingsUi", "Framerate:"))
        self.label_6.sT..(_translate("VideoSettingsUi", "Video Codec:"))
        self.label_7.sT..(_translate("VideoSettingsUi", "Quality:"))
        self.label_4.sT..(_translate("VideoSettingsUi", "Container Format:"))

