# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created: Sat Oct 25 13:40:24 2014
#      by: PyQt5 UI code generator 5.2.1
#
# WARNING! All changes made in this file will be lost!

____ ? ______ ?C.., ?G.., QtWidgets

c_ Ui_MainWindow o..
    ___ setupUi  MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(925, 852)
        centralwidget _ QtWidgets.QWidget(MainWindow)
        centralwidget.sE.. T..
        sizePolicy _ QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(centralwidget.sizePolicy().hasHeightForWidth())
        centralwidget.setSizePolicy(sizePolicy)
        centralwidget.setCursor(?G...?C..(?C...__.ArrowCursor))
        centralwidget.setLayoutDirection(?C...__.LeftToRight)
        centralwidget.setAutoFillBackground F..
        centralwidget.setObjectName("centralwidget")
        verticalLayout_5 _ QtWidgets.QVBoxLayout(centralwidget)
        verticalLayout_5.setObjectName("verticalLayout_5")
        verticalLayout_main _ QtWidgets.QVBoxLayout()
        verticalLayout_main.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        verticalLayout_main.setObjectName("verticalLayout_main")
        horizontall_up _ QtWidgets.QHBoxLayout()
        horizontall_up.setObjectName("horizontall_up")
        label _ QtWidgets.QLabel(centralwidget)
        label.setObjectName("label")
        horizontall_up.addWidget(label)
        mongoHost _ QtWidgets.QLineEdit(centralwidget)
        mongoHost.setObjectName("mongoHost")
        horizontall_up.addWidget(mongoHost)
        connectBtn _ QtWidgets.QPushButton(centralwidget)
        cB__.setObjectName("connectBtn")
        horizontall_up.addWidget(cB__)
        spacerItem _ QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        horizontall_up.addItem(spacerItem)
        verticalLayout_main.addLayout(horizontall_up)
        horizontalLayout _ QtWidgets.QHBoxLayout()
        horizontalLayout.setObjectName("horizontalLayout")
        preview1 _ QtWidgets.QLabel(centralwidget)
        preview1.setObjectName("preview1")
        horizontalLayout.addWidget(preview1)
        preview _ QtWidgets.QLineEdit(centralwidget)
        p__.setReadOnly T..
        p__.setObjectName("preview")
        horizontalLayout.addWidget(p__)
        querytime _ QtWidgets.QLabel(centralwidget)
        querytime.setMinimumSize(?C...QSize(200, 0))
        querytime.sT..("")
        querytime.setObjectName("querytime")
        horizontalLayout.addWidget(querytime)
        verticalLayout_main.addLayout(horizontalLayout)
        horizontal_down _ QtWidgets.QHBoxLayout()
        horizontal_down.setObjectName("horizontal_down")
        treeWidget _ QtWidgets.QTreeWidget(centralwidget)
        treeWidget.sE.. T..
        treeWidget.setMaximumSize(?C...QSize(200, 16777215))
        treeWidget.setBaseSize(?C...QSize(0, 0))
        treeWidget.setObjectName("treeWidget")
        horizontal_down.addWidget(treeWidget)
        verticall_down_right _ QtWidgets.QVBoxLayout()
        verticall_down_right.setObjectName("verticall_down_right")
        horizontalLayout_2 _ QtWidgets.QHBoxLayout()
        horizontalLayout_2.setObjectName("horizontalLayout_2")
        query _ QtWidgets.QLineEdit(centralwidget)
        query.setInputMethodHints(?C...__.ImhHiddenText)
        query.sT..("")
        query.setClearButtonEnabled T..
        query.setObjectName("query")
        horizontalLayout_2.addWidget(query)
        label_2 _ QtWidgets.QLabel(centralwidget)
        label_2.setObjectName("label_2")
        horizontalLayout_2.addWidget(label_2)
        sort _ QtWidgets.QLineEdit(centralwidget)
        sizePolicy _ QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(sort.sizePolicy().hasHeightForWidth())
        sort.setSizePolicy(sizePolicy)
        sort.setMinimumSize(?C...QSize(100, 0))
        sort.setInputMethodHints(?C...__.ImhNone)
        sort.sT..("")
        sort.setClearButtonEnabled F..
        sort.setObjectName("sort")
        horizontalLayout_2.addWidget(sort)
        querybtn _ QtWidgets.QPushButton(centralwidget)
        q_b_.setObjectName("querybtn")
        horizontalLayout_2.addWidget(q_b_)
        verticall_down_right.addLayout(horizontalLayout_2)
        viewDetailLabel _ QtWidgets.QLabel(centralwidget)
        viewDetailLabel.setObjectName("viewDetailLabel")
        verticall_down_right.addWidget(viewDetailLabel)
        tableview _ QtWidgets.QTableView(centralwidget)
        t_v_.setObjectName("tableview")
        verticall_down_right.addWidget(t_v_)
        paginationLayoutDown _ QtWidgets.QHBoxLayout()
        paginationLayoutDown.setObjectName("paginationLayoutDown")
        paginationinfo _ QtWidgets.QLabel(centralwidget)
        paginationinfo.sT..("")
        paginationinfo.setObjectName("paginationinfo")
        paginationLayoutDown.addWidget(paginationinfo)
        prevBtn _ QtWidgets.QPushButton(centralwidget)
        prevBtn.sE.. F..
        prevBtn.setMinimumSize(?C...QSize(100, 0))
        prevBtn.setMaximumSize(?C...QSize(100, 100))
        prevBtn.setCheckable F..
        prevBtn.setAutoDefault F..
        prevBtn.setDefault F..
        prevBtn.setFlat F..
        prevBtn.setObjectName("prevBtn")
        paginationLayoutDown.addWidget(prevBtn)
        nextBtn _ QtWidgets.QPushButton(centralwidget)
        nextBtn.sE.. F..
        nextBtn.setMinimumSize(?C...QSize(100, 32))
        nextBtn.setMaximumSize(?C...QSize(100, 100))
        nextBtn.setObjectName("nextBtn")
        paginationLayoutDown.addWidget(nextBtn)
        verticall_down_right.addLayout(paginationLayoutDown)
        horizontal_down.addLayout(verticall_down_right)
        verticalLayout_main.addLayout(horizontal_down)
        verticalLayout_5.addLayout(verticalLayout_main)
        MainWindow.setCentralWidget(centralwidget)
        menubar _ QtWidgets.QMenuBar(MainWindow)
        menubar.setGeometry(?C...QRect(0, 0, 925, 22))
        menubar.setObjectName("menubar")
        MainWindow.setMenuBar(menubar)
        statusbar _ QtWidgets.QStatusBar(MainWindow)
        statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(statusbar)

        retranslateUi(MainWindow)
        ?C...QMetaObject.connectSlotsByName(MainWindow)

    ___ retranslateUi  MainWindow):
        _translate _ ?C...QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Mongo-pyqt"))
        label.sT..(_translate("MainWindow", "mongo host:"))
        cB__.sT..(_translate("MainWindow", "connect"))
        preview1.sT..(_translate("MainWindow", "Preview"))
        tW__.headerItem().sT..(0, _translate("MainWindow", "DB"))
        query.setPlaceholderText(_translate("MainWindow", "{}"))
        label_2.sT..(_translate("MainWindow", "sort"))
        sort.setPlaceholderText(_translate("MainWindow", "{\"field\":1}"))
        q_b_.sT..(_translate("MainWindow", "query"))
        viewDetailLabel.sT..(_translate("MainWindow", "Table Detail:"))
        prevBtn.sT..(_translate("MainWindow", "Prev"))
        nextBtn.sT..(_translate("MainWindow", "Next"))

