# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created: Sat Oct 25 13:40:24 2014
#      by: PyQt5 UI code generator 5.2.1
#
# WARNING! All changes made in this file will be lost!

____ ? ______ ?C.., QtGui, QtWidgets

c_ Ui_MainWindow o..
    ___ setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(925, 852)
        centralwidget = QtWidgets.QWidget(MainWindow)
        centralwidget.setEnabled T..
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(centralwidget.sizePolicy().hasHeightForWidth())
        centralwidget.setSizePolicy(sizePolicy)
        centralwidget.setCursor(QtGui.QCursor(?C...__.ArrowCursor))
        centralwidget.setLayoutDirection(?C...__.LeftToRight)
        centralwidget.setAutoFillBackground(False)
        centralwidget.setObjectName("centralwidget")
        verticalLayout_5 = QtWidgets.QVBoxLayout(centralwidget)
        verticalLayout_5.setObjectName("verticalLayout_5")
        verticalLayout_main = QtWidgets.QVBoxLayout()
        verticalLayout_main.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        verticalLayout_main.setObjectName("verticalLayout_main")
        horizontall_up = QtWidgets.QHBoxLayout()
        horizontall_up.setObjectName("horizontall_up")
        label = QtWidgets.QLabel(centralwidget)
        label.setObjectName("label")
        horizontall_up.addWidget(label)
        mongoHost = QtWidgets.QLineEdit(centralwidget)
        mongoHost.setObjectName("mongoHost")
        horizontall_up.addWidget(mongoHost)
        connectBtn = QtWidgets.QPushButton(centralwidget)
        cB__.setObjectName("connectBtn")
        horizontall_up.addWidget(cB__)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        horizontall_up.addItem(spacerItem)
        verticalLayout_main.addLayout(horizontall_up)
        horizontalLayout = QtWidgets.QHBoxLayout()
        horizontalLayout.setObjectName("horizontalLayout")
        preview1 = QtWidgets.QLabel(centralwidget)
        preview1.setObjectName("preview1")
        horizontalLayout.addWidget(preview1)
        preview = QtWidgets.QLineEdit(centralwidget)
        preview.setReadOnly T..
        preview.setObjectName("preview")
        horizontalLayout.addWidget(preview)
        querytime = QtWidgets.QLabel(centralwidget)
        querytime.setMinimumSize(?C...QSize(200, 0))
        querytime.setText("")
        querytime.setObjectName("querytime")
        horizontalLayout.addWidget(querytime)
        verticalLayout_main.addLayout(horizontalLayout)
        horizontal_down = QtWidgets.QHBoxLayout()
        horizontal_down.setObjectName("horizontal_down")
        treeWidget = QtWidgets.QTreeWidget(centralwidget)
        treeWidget.setEnabled T..
        treeWidget.setMaximumSize(?C...QSize(200, 16777215))
        treeWidget.setBaseSize(?C...QSize(0, 0))
        treeWidget.setObjectName("treeWidget")
        horizontal_down.addWidget(treeWidget)
        verticall_down_right = QtWidgets.QVBoxLayout()
        verticall_down_right.setObjectName("verticall_down_right")
        horizontalLayout_2 = QtWidgets.QHBoxLayout()
        horizontalLayout_2.setObjectName("horizontalLayout_2")
        query = QtWidgets.QLineEdit(centralwidget)
        query.setInputMethodHints(?C...__.ImhHiddenText)
        query.setText("")
        query.setClearButtonEnabled T..
        query.setObjectName("query")
        horizontalLayout_2.addWidget(query)
        label_2 = QtWidgets.QLabel(centralwidget)
        label_2.setObjectName("label_2")
        horizontalLayout_2.addWidget(label_2)
        sort = QtWidgets.QLineEdit(centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(sort.sizePolicy().hasHeightForWidth())
        sort.setSizePolicy(sizePolicy)
        sort.setMinimumSize(?C...QSize(100, 0))
        sort.setInputMethodHints(?C...__.ImhNone)
        sort.setText("")
        sort.setClearButtonEnabled(False)
        sort.setObjectName("sort")
        horizontalLayout_2.addWidget(sort)
        querybtn = QtWidgets.QPushButton(centralwidget)
        q_b_.setObjectName("querybtn")
        horizontalLayout_2.addWidget(q_b_)
        verticall_down_right.addLayout(horizontalLayout_2)
        viewDetailLabel = QtWidgets.QLabel(centralwidget)
        viewDetailLabel.setObjectName("viewDetailLabel")
        verticall_down_right.addWidget(viewDetailLabel)
        tableview = QtWidgets.QTableView(centralwidget)
        t_v_.setObjectName("tableview")
        verticall_down_right.addWidget(t_v_)
        paginationLayoutDown = QtWidgets.QHBoxLayout()
        paginationLayoutDown.setObjectName("paginationLayoutDown")
        paginationinfo = QtWidgets.QLabel(centralwidget)
        paginationinfo.setText("")
        paginationinfo.setObjectName("paginationinfo")
        paginationLayoutDown.addWidget(paginationinfo)
        prevBtn = QtWidgets.QPushButton(centralwidget)
        prevBtn.setEnabled(False)
        prevBtn.setMinimumSize(?C...QSize(100, 0))
        prevBtn.setMaximumSize(?C...QSize(100, 100))
        prevBtn.setCheckable(False)
        prevBtn.setAutoDefault(False)
        prevBtn.setDefault(False)
        prevBtn.setFlat(False)
        prevBtn.setObjectName("prevBtn")
        paginationLayoutDown.addWidget(prevBtn)
        nextBtn = QtWidgets.QPushButton(centralwidget)
        nextBtn.setEnabled(False)
        nextBtn.setMinimumSize(?C...QSize(100, 32))
        nextBtn.setMaximumSize(?C...QSize(100, 100))
        nextBtn.setObjectName("nextBtn")
        paginationLayoutDown.addWidget(nextBtn)
        verticall_down_right.addLayout(paginationLayoutDown)
        horizontal_down.addLayout(verticall_down_right)
        verticalLayout_main.addLayout(horizontal_down)
        verticalLayout_5.addLayout(verticalLayout_main)
        MainWindow.setCentralWidget(centralwidget)
        menubar = QtWidgets.QMenuBar(MainWindow)
        menubar.setGeometry(?C...QRect(0, 0, 925, 22))
        menubar.setObjectName("menubar")
        MainWindow.setMenuBar(menubar)
        statusbar = QtWidgets.QStatusBar(MainWindow)
        statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(statusbar)

        retranslateUi(MainWindow)
        ?C...QMetaObject.connectSlotsByName(MainWindow)

    ___ retranslateUi(self, MainWindow):
        _translate = ?C...QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Mongo-pyqt"))
        label.setText(_translate("MainWindow", "mongo host:"))
        cB__.setText(_translate("MainWindow", "connect"))
        preview1.setText(_translate("MainWindow", "Preview"))
        tW__.headerItem().setText(0, _translate("MainWindow", "DB"))
        query.setPlaceholderText(_translate("MainWindow", "{}"))
        label_2.setText(_translate("MainWindow", "sort"))
        sort.setPlaceholderText(_translate("MainWindow", "{\"field\":1}"))
        q_b_.setText(_translate("MainWindow", "query"))
        viewDetailLabel.setText(_translate("MainWindow", "Table Detail:"))
        prevBtn.setText(_translate("MainWindow", "Prev"))
        nextBtn.setText(_translate("MainWindow", "Next"))

