# ______ s......
#
# sock _ s____.s____(s____.A._I... s____.S..._S...
# s___.b... 127.0.0.1 8888
# s___.l... 5
# s___.s..b.. F..
#
# w____ T___
#     t..
#         client, addr _ s___.ac...
#     e.... s___.e____
#         print no clients
#     e.... K....I....
#         b_
#     e____
#         c____.s..b... T...
#         result _ c___.recv 1024
#         c___.c...
#         print 'Message' r____.d.... utf-8
