# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.10
#
# WARNING! All changes made in this file will be lost!

____ ? ______ ?C.., ?G.., ?W..

c_ Ui_MainWindow(object):
    ___ setupUi  MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(330, 417)
        self.centralwidget _ ?W...QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout _ ?W...QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout _ ?W...QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 _ ?W...QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lineEdit _ ?W...QLineEdit(self.centralwidget)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_3.addWidget(self.lineEdit)
        self.pushButton _ ?W...?PB..(self.centralwidget)
        self.pushButton.sT..("")
        icon _ ?G...QIcon()
        icon.addPixmap(?G...QPixmap("images/arrow-circle-225.png"), ?G...QIcon.Normal, ?G...QIcon.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_3.addWidget(self.pushButton)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 _ ?W...QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.weatherIcon _ ?W...QLabel(self.centralwidget)
        sizePolicy _ ?W...QSizePolicy(?W...QSizePolicy.Maximum, ?W...QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.weatherIcon.sizePolicy().hasHeightForWidth())
        self.weatherIcon.setSizePolicy(sizePolicy)
        self.weatherIcon.setMinimumSize(?C...QSize(16, 16))
        self.weatherIcon.setMaximumSize(?C...QSize(16, 16))
        self.weatherIcon.sT..("")
        self.weatherIcon.setObjectName("weatherIcon")
        self.horizontalLayout_4.addWidget(self.weatherIcon)
        self.weatherLabel _ ?W...QLabel(self.centralwidget)
        self.weatherLabel.sT..("")
        self.weatherLabel.setObjectName("weatherLabel")
        self.horizontalLayout_4.addWidget(self.weatherLabel)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.gridLayout_2 _ ?W...QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.forecastIcon4 _ ?W...QLabel(self.centralwidget)
        sizePolicy _ ?W...QSizePolicy(?W...QSizePolicy.MinimumExpanding, ?W...QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.forecastIcon4.sizePolicy().hasHeightForWidth())
        self.forecastIcon4.setSizePolicy(sizePolicy)
        self.forecastIcon4.setMinimumSize(?C...QSize(16, 16))
        self.forecastIcon4.setMaximumSize(?C...QSize(200, 16))
        self.forecastIcon4.setBaseSize(?C...QSize(0, 0))
        self.forecastIcon4.sT..("")
        self.forecastIcon4.setAlignment(?C...__.AlignCenter)
        self.forecastIcon4.setObjectName("forecastIcon4")
        self.gridLayout_2.addWidget(self.forecastIcon4, 1, 3, 1, 1)
        self.forecastTemp2 _ ?W...QLabel(self.centralwidget)
        self.forecastTemp2.sT..("")
        self.forecastTemp2.setObjectName("forecastTemp2")
        self.gridLayout_2.addWidget(self.forecastTemp2, 2, 1, 1, 1)
        self.forecastTemp5 _ ?W...QLabel(self.centralwidget)
        self.forecastTemp5.sT..("")
        self.forecastTemp5.setObjectName("forecastTemp5")
        self.gridLayout_2.addWidget(self.forecastTemp5, 2, 4, 1, 1)
        self.forecastTemp4 _ ?W...QLabel(self.centralwidget)
        self.forecastTemp4.sT..("")
        self.forecastTemp4.setObjectName("forecastTemp4")
        self.gridLayout_2.addWidget(self.forecastTemp4, 2, 3, 1, 1)
        self.forecastIcon2 _ ?W...QLabel(self.centralwidget)
        sizePolicy _ ?W...QSizePolicy(?W...QSizePolicy.MinimumExpanding, ?W...QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.forecastIcon2.sizePolicy().hasHeightForWidth())
        self.forecastIcon2.setSizePolicy(sizePolicy)
        self.forecastIcon2.setMinimumSize(?C...QSize(16, 16))
        self.forecastIcon2.setMaximumSize(?C...QSize(200, 16))
        self.forecastIcon2.setBaseSize(?C...QSize(0, 0))
        self.forecastIcon2.sT..("")
        self.forecastIcon2.setAlignment(?C...__.AlignCenter)
        self.forecastIcon2.setObjectName("forecastIcon2")
        self.gridLayout_2.addWidget(self.forecastIcon2, 1, 1, 1, 1)
        self.forecastIcon5 _ ?W...QLabel(self.centralwidget)
        sizePolicy _ ?W...QSizePolicy(?W...QSizePolicy.MinimumExpanding, ?W...QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.forecastIcon5.sizePolicy().hasHeightForWidth())
        self.forecastIcon5.setSizePolicy(sizePolicy)
        self.forecastIcon5.setMinimumSize(?C...QSize(16, 16))
        self.forecastIcon5.setMaximumSize(?C...QSize(200, 16))
        self.forecastIcon5.setBaseSize(?C...QSize(0, 0))
        self.forecastIcon5.sT..("")
        self.forecastIcon5.setAlignment(?C...__.AlignCenter)
        self.forecastIcon5.setObjectName("forecastIcon5")
        self.gridLayout_2.addWidget(self.forecastIcon5, 1, 4, 1, 1)
        self.forecastIcon1 _ ?W...QLabel(self.centralwidget)
        sizePolicy _ ?W...QSizePolicy(?W...QSizePolicy.MinimumExpanding, ?W...QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.forecastIcon1.sizePolicy().hasHeightForWidth())
        self.forecastIcon1.setSizePolicy(sizePolicy)
        self.forecastIcon1.setMinimumSize(?C...QSize(16, 16))
        self.forecastIcon1.setMaximumSize(?C...QSize(200, 16))
        self.forecastIcon1.setBaseSize(?C...QSize(0, 0))
        self.forecastIcon1.sT..("")
        self.forecastIcon1.setAlignment(?C...__.AlignCenter)
        self.forecastIcon1.setObjectName("forecastIcon1")
        self.gridLayout_2.addWidget(self.forecastIcon1, 1, 0, 1, 1)
        self.forecastIcon3 _ ?W...QLabel(self.centralwidget)
        sizePolicy _ ?W...QSizePolicy(?W...QSizePolicy.MinimumExpanding, ?W...QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.forecastIcon3.sizePolicy().hasHeightForWidth())
        self.forecastIcon3.setSizePolicy(sizePolicy)
        self.forecastIcon3.setMinimumSize(?C...QSize(16, 16))
        self.forecastIcon3.setMaximumSize(?C...QSize(200, 16))
        self.forecastIcon3.setBaseSize(?C...QSize(0, 0))
        self.forecastIcon3.sT..("")
        self.forecastIcon3.setAlignment(?C...__.AlignCenter)
        self.forecastIcon3.setObjectName("forecastIcon3")
        self.gridLayout_2.addWidget(self.forecastIcon3, 1, 2, 1, 1)
        self.forecastTemp3 _ ?W...QLabel(self.centralwidget)
        self.forecastTemp3.sT..("")
        self.forecastTemp3.setObjectName("forecastTemp3")
        self.gridLayout_2.addWidget(self.forecastTemp3, 2, 2, 1, 1)
        self.forecastTemp1 _ ?W...QLabel(self.centralwidget)
        self.forecastTemp1.sT..("")
        self.forecastTemp1.setObjectName("forecastTemp1")
        self.gridLayout_2.addWidget(self.forecastTemp1, 2, 0, 1, 1)
        self.forecastTime1 _ ?W...QLabel(self.centralwidget)
        self.forecastTime1.setAlignment(?C...__.AlignCenter)
        self.forecastTime1.setObjectName("forecastTime1")
        self.gridLayout_2.addWidget(self.forecastTime1, 0, 0, 1, 1)
        self.forecastTime2 _ ?W...QLabel(self.centralwidget)
        self.forecastTime2.setAlignment(?C...__.AlignCenter)
        self.forecastTime2.setObjectName("forecastTime2")
        self.gridLayout_2.addWidget(self.forecastTime2, 0, 1, 1, 1)
        self.forecastTime3 _ ?W...QLabel(self.centralwidget)
        self.forecastTime3.setAlignment(?C...__.AlignCenter)
        self.forecastTime3.setObjectName("forecastTime3")
        self.gridLayout_2.addWidget(self.forecastTime3, 0, 2, 1, 1)
        self.forecastTime4 _ ?W...QLabel(self.centralwidget)
        self.forecastTime4.setAlignment(?C...__.AlignCenter)
        self.forecastTime4.setObjectName("forecastTime4")
        self.gridLayout_2.addWidget(self.forecastTime4, 0, 3, 1, 1)
        self.forecastTime5 _ ?W...QLabel(self.centralwidget)
        self.forecastTime5.setAlignment(?C...__.AlignCenter)
        self.forecastTime5.setObjectName("forecastTime5")
        self.gridLayout_2.addWidget(self.forecastTime5, 0, 4, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        self.gridLayout _ ?W...QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.formLayout _ ?W...QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label_5 _ ?W...QLabel(self.centralwidget)
        font _ ?G...QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setAlignment(?C...__.AlignRight|?C...__.AlignTrailing|?C...__.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(2, ?W...QFormLayout.LabelRole, self.label_5)
        self.label_6 _ ?W...QLabel(self.centralwidget)
        self.label_6.setAlignment(?C...__.AlignRight|?C...__.AlignTrailing|?C...__.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(3, ?W...QFormLayout.LabelRole, self.label_6)
        self.temperatureLabel _ ?W...QLabel(self.centralwidget)
        self.temperatureLabel.sT..("")
        self.temperatureLabel.setObjectName("temperatureLabel")
        self.formLayout.setWidget(3, ?W...QFormLayout.FieldRole, self.temperatureLabel)
        self.label_7 _ ?W...QLabel(self.centralwidget)
        self.label_7.setAlignment(?C...__.AlignRight|?C...__.AlignTrailing|?C...__.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(4, ?W...QFormLayout.LabelRole, self.label_7)
        self.humidityLabel _ ?W...QLabel(self.centralwidget)
        self.humidityLabel.sT..("")
        self.humidityLabel.setObjectName("humidityLabel")
        self.formLayout.setWidget(4, ?W...QFormLayout.FieldRole, self.humidityLabel)
        self.label_8 _ ?W...QLabel(self.centralwidget)
        self.label_8.setAlignment(?C...__.AlignRight|?C...__.AlignTrailing|?C...__.AlignVCenter)
        self.label_8.setObjectName("label_8")
        self.formLayout.setWidget(5, ?W...QFormLayout.LabelRole, self.label_8)
        self.pressureLabel _ ?W...QLabel(self.centralwidget)
        self.pressureLabel.sT..("")
        self.pressureLabel.setObjectName("pressureLabel")
        self.formLayout.setWidget(5, ?W...QFormLayout.FieldRole, self.pressureLabel)
        self.label _ ?W...QLabel(self.centralwidget)
        font _ ?G...QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(?C...__.AlignRight|?C...__.AlignTrailing|?C...__.AlignVCenter)
        self.label.setObjectName("label")
        self.formLayout.setWidget(6, ?W...QFormLayout.LabelRole, self.label)
        self.label_2 _ ?W...QLabel(self.centralwidget)
        self.label_2.setAlignment(?C...__.AlignRight|?C...__.AlignTrailing|?C...__.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(7, ?W...QFormLayout.LabelRole, self.label_2)
        self.longitudeLabel _ ?W...QLabel(self.centralwidget)
        self.longitudeLabel.sT..("")
        self.longitudeLabel.setObjectName("longitudeLabel")
        self.formLayout.setWidget(7, ?W...QFormLayout.FieldRole, self.longitudeLabel)
        self.label_3 _ ?W...QLabel(self.centralwidget)
        self.label_3.setAlignment(?C...__.AlignRight|?C...__.AlignTrailing|?C...__.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(8, ?W...QFormLayout.LabelRole, self.label_3)
        self.latitudeLabel _ ?W...QLabel(self.centralwidget)
        self.latitudeLabel.sT..("")
        self.latitudeLabel.setObjectName("latitudeLabel")
        self.formLayout.setWidget(8, ?W...QFormLayout.FieldRole, self.latitudeLabel)
        self.label_4 _ ?W...QLabel(self.centralwidget)
        self.label_4.setAlignment(?C...__.AlignRight|?C...__.AlignTrailing|?C...__.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(9, ?W...QFormLayout.LabelRole, self.label_4)
        self.sunriseLabel _ ?W...QLabel(self.centralwidget)
        self.sunriseLabel.sT..("")
        self.sunriseLabel.setObjectName("sunriseLabel")
        self.formLayout.setWidget(9, ?W...QFormLayout.FieldRole, self.sunriseLabel)
        self.label_9 _ ?W...QLabel(self.centralwidget)
        self.label_9.setAlignment(?C...__.AlignRight|?C...__.AlignTrailing|?C...__.AlignVCenter)
        self.label_9.setObjectName("label_9")
        self.formLayout.setWidget(1, ?W...QFormLayout.LabelRole, self.label_9)
        self.label_10 _ ?W...QLabel(self.centralwidget)
        font _ ?G...QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setAlignment(?C...__.AlignRight|?C...__.AlignTrailing|?C...__.AlignVCenter)
        self.label_10.setObjectName("label_10")
        self.formLayout.setWidget(0, ?W...QFormLayout.LabelRole, self.label_10)
        self.windLabel _ ?W...QLabel(self.centralwidget)
        self.windLabel.sT..("")
        self.windLabel.setObjectName("windLabel")
        self.formLayout.setWidget(1, ?W...QFormLayout.FieldRole, self.windLabel)
        self.label_11 _ ?W...QLabel(self.centralwidget)
        self.label_11.sT..("")
        self.label_11.setObjectName("label_11")
        self.formLayout.setWidget(0, ?W...QFormLayout.FieldRole, self.label_11)
        self.label_13 _ ?W...QLabel(self.centralwidget)
        self.label_13.sT..("")
        self.label_13.setObjectName("label_13")
        self.formLayout.setWidget(6, ?W...QFormLayout.FieldRole, self.label_13)
        self.label_12 _ ?W...QLabel(self.centralwidget)
        self.label_12.sT..("")
        self.label_12.setObjectName("label_12")
        self.formLayout.setWidget(2, ?W...QFormLayout.FieldRole, self.label_12)
        self.gridLayout.addLayout(self.formLayout, 1, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.horizontalLayout.addLayout(self.verticalLayout)
        MainWindow.sCW..(self.centralwidget)

        self.retranslateUi(MainWindow)
        ?C...QMetaObject.connectSlotsByName(MainWindow)

    ___ retranslateUi  MainWindow):
        _translate _ ?C...QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Raindar"))
        self.lineEdit.sT..(_translate("MainWindow", "Utrecht,the Netherlands"))
        self.forecastTime1.sT..(_translate("MainWindow", "+3h"))
        self.forecastTime2.sT..(_translate("MainWindow", "+6h"))
        self.forecastTime3.sT..(_translate("MainWindow", "+9h"))
        self.forecastTime4.sT..(_translate("MainWindow", "+12h"))
        self.forecastTime5.sT..(_translate("MainWindow", "+15h"))
        self.label_5.sT..(_translate("MainWindow", "Barometer"))
        self.label_6.sT..(_translate("MainWindow", "Temperature"))
        self.label_7.sT..(_translate("MainWindow", "Humidity"))
        self.label_8.sT..(_translate("MainWindow", "Pressure"))
        self.label.sT..(_translate("MainWindow", "Location"))
        self.label_2.sT..(_translate("MainWindow", "Longitude"))
        self.label_3.sT..(_translate("MainWindow", "Latitude"))
        self.label_4.sT..(_translate("MainWindow", "Sunrise"))
        self.label_9.sT..(_translate("MainWindow", "Speed"))
        self.label_10.sT..(_translate("MainWindow", "Wind"))

