# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.10
#
# WARNING! All changes made in this file will be lost!

____ ? ______ ?C.., ?G.., ?W..

c_ Ui_MainWindow o..
    ___ setupUi  MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.r..(330, 417)
        centralwidget _ ?W...?W..(MainWindow)
        centralwidget.setObjectName("centralwidget")
        horizontalLayout _ ?W...?HBL..(centralwidget)
        horizontalLayout.setObjectName("horizontalLayout")
        verticalLayout _ ?W...?VBL..
        verticalLayout.setObjectName("verticalLayout")
        horizontalLayout_3 _ ?W...?HBL..
        horizontalLayout_3.setObjectName("horizontalLayout_3")
        lineEdit _ ?W...QLineEdit(centralwidget)
        lineEdit.setObjectName("lineEdit")
        horizontalLayout_3.aW..(lineEdit)
        pushButton _ ?W...?PB..(centralwidget)
        pushButton.sT..("")
        icon _ ?G...?I..
        icon.aP..(?G...?P..("images/arrow-circle-225.png"), ?G...?I...Normal, ?G...?I...Off)
        pushButton.sI..(icon)
        pushButton.setObjectName("pushButton")
        horizontalLayout_3.aW..(pushButton)
        verticalLayout.aL..(horizontalLayout_3)
        horizontalLayout_4 _ ?W...?HBL..
        horizontalLayout_4.setObjectName("horizontalLayout_4")
        weatherIcon _ ?W...?L..(centralwidget)
        sizePolicy _ ?W...?SP..(?W...?SP...Maximum, ?W...?SP...Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(weatherIcon.sizePolicy().hasHeightForWidth())
        weatherIcon.sSP..(sizePolicy)
        weatherIcon.sMS..(?C...?S..(16, 16))
        weatherIcon.sMS..(?C...?S..(16, 16))
        weatherIcon.sT..("")
        weatherIcon.setObjectName("weatherIcon")
        horizontalLayout_4.aW..(weatherIcon)
        weatherLabel _ ?W...?L..(centralwidget)
        weatherLabel.sT..("")
        weatherLabel.setObjectName("weatherLabel")
        horizontalLayout_4.aW..(weatherLabel)
        verticalLayout.aL..(horizontalLayout_4)
        gridLayout_2 _ ?W...QGridLayout()
        gridLayout_2.setObjectName("gridLayout_2")
        forecastIcon4 _ ?W...?L..(centralwidget)
        sizePolicy _ ?W...?SP..(?W...?SP...ME.., ?W...?SP...Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(forecastIcon4.sizePolicy().hasHeightForWidth())
        forecastIcon4.sSP..(sizePolicy)
        forecastIcon4.sMS..(?C...?S..(16, 16))
        forecastIcon4.sMS..(?C...?S..(200, 16))
        forecastIcon4.setBaseSize(?C...?S..(0, 0))
        forecastIcon4.sT..("")
        forecastIcon4.setAlignment(?C...__.AlignCenter)
        forecastIcon4.setObjectName("forecastIcon4")
        gridLayout_2.aW..(forecastIcon4, 1, 3, 1, 1)
        forecastTemp2 _ ?W...?L..(centralwidget)
        forecastTemp2.sT..("")
        forecastTemp2.setObjectName("forecastTemp2")
        gridLayout_2.aW..(forecastTemp2, 2, 1, 1, 1)
        forecastTemp5 _ ?W...?L..(centralwidget)
        forecastTemp5.sT..("")
        forecastTemp5.setObjectName("forecastTemp5")
        gridLayout_2.aW..(forecastTemp5, 2, 4, 1, 1)
        forecastTemp4 _ ?W...?L..(centralwidget)
        forecastTemp4.sT..("")
        forecastTemp4.setObjectName("forecastTemp4")
        gridLayout_2.aW..(forecastTemp4, 2, 3, 1, 1)
        forecastIcon2 _ ?W...?L..(centralwidget)
        sizePolicy _ ?W...?SP..(?W...?SP...ME.., ?W...?SP...Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(forecastIcon2.sizePolicy().hasHeightForWidth())
        forecastIcon2.sSP..(sizePolicy)
        forecastIcon2.sMS..(?C...?S..(16, 16))
        forecastIcon2.sMS..(?C...?S..(200, 16))
        forecastIcon2.setBaseSize(?C...?S..(0, 0))
        forecastIcon2.sT..("")
        forecastIcon2.setAlignment(?C...__.AlignCenter)
        forecastIcon2.setObjectName("forecastIcon2")
        gridLayout_2.aW..(forecastIcon2, 1, 1, 1, 1)
        forecastIcon5 _ ?W...?L..(centralwidget)
        sizePolicy _ ?W...?SP..(?W...?SP...ME.., ?W...?SP...Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(forecastIcon5.sizePolicy().hasHeightForWidth())
        forecastIcon5.sSP..(sizePolicy)
        forecastIcon5.sMS..(?C...?S..(16, 16))
        forecastIcon5.sMS..(?C...?S..(200, 16))
        forecastIcon5.setBaseSize(?C...?S..(0, 0))
        forecastIcon5.sT..("")
        forecastIcon5.setAlignment(?C...__.AlignCenter)
        forecastIcon5.setObjectName("forecastIcon5")
        gridLayout_2.aW..(forecastIcon5, 1, 4, 1, 1)
        forecastIcon1 _ ?W...?L..(centralwidget)
        sizePolicy _ ?W...?SP..(?W...?SP...ME.., ?W...?SP...Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(forecastIcon1.sizePolicy().hasHeightForWidth())
        forecastIcon1.sSP..(sizePolicy)
        forecastIcon1.sMS..(?C...?S..(16, 16))
        forecastIcon1.sMS..(?C...?S..(200, 16))
        forecastIcon1.setBaseSize(?C...?S..(0, 0))
        forecastIcon1.sT..("")
        forecastIcon1.setAlignment(?C...__.AlignCenter)
        forecastIcon1.setObjectName("forecastIcon1")
        gridLayout_2.aW..(forecastIcon1, 1, 0, 1, 1)
        forecastIcon3 _ ?W...?L..(centralwidget)
        sizePolicy _ ?W...?SP..(?W...?SP...ME.., ?W...?SP...Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(forecastIcon3.sizePolicy().hasHeightForWidth())
        forecastIcon3.sSP..(sizePolicy)
        forecastIcon3.sMS..(?C...?S..(16, 16))
        forecastIcon3.sMS..(?C...?S..(200, 16))
        forecastIcon3.setBaseSize(?C...?S..(0, 0))
        forecastIcon3.sT..("")
        forecastIcon3.setAlignment(?C...__.AlignCenter)
        forecastIcon3.setObjectName("forecastIcon3")
        gridLayout_2.aW..(forecastIcon3, 1, 2, 1, 1)
        forecastTemp3 _ ?W...?L..(centralwidget)
        forecastTemp3.sT..("")
        forecastTemp3.setObjectName("forecastTemp3")
        gridLayout_2.aW..(forecastTemp3, 2, 2, 1, 1)
        forecastTemp1 _ ?W...?L..(centralwidget)
        forecastTemp1.sT..("")
        forecastTemp1.setObjectName("forecastTemp1")
        gridLayout_2.aW..(forecastTemp1, 2, 0, 1, 1)
        forecastTime1 _ ?W...?L..(centralwidget)
        forecastTime1.setAlignment(?C...__.AlignCenter)
        forecastTime1.setObjectName("forecastTime1")
        gridLayout_2.aW..(forecastTime1, 0, 0, 1, 1)
        forecastTime2 _ ?W...?L..(centralwidget)
        forecastTime2.setAlignment(?C...__.AlignCenter)
        forecastTime2.setObjectName("forecastTime2")
        gridLayout_2.aW..(forecastTime2, 0, 1, 1, 1)
        forecastTime3 _ ?W...?L..(centralwidget)
        forecastTime3.setAlignment(?C...__.AlignCenter)
        forecastTime3.setObjectName("forecastTime3")
        gridLayout_2.aW..(forecastTime3, 0, 2, 1, 1)
        forecastTime4 _ ?W...?L..(centralwidget)
        forecastTime4.setAlignment(?C...__.AlignCenter)
        forecastTime4.setObjectName("forecastTime4")
        gridLayout_2.aW..(forecastTime4, 0, 3, 1, 1)
        forecastTime5 _ ?W...?L..(centralwidget)
        forecastTime5.setAlignment(?C...__.AlignCenter)
        forecastTime5.setObjectName("forecastTime5")
        gridLayout_2.aW..(forecastTime5, 0, 4, 1, 1)
        verticalLayout.aL..(gridLayout_2)
        gridLayout _ ?W...QGridLayout()
        gridLayout.setObjectName("gridLayout")
        formLayout _ ?W...?FL..
        formLayout.setObjectName("formLayout")
        label_5 _ ?W...?L..(centralwidget)
        font _ ?G...?F..()
        font.setBold( st.
        font.sW..(75)
        label_5.sF..(font)
        label_5.setAlignment(?C...__.AlignRight|?C...__.AlignTrailing|?C...__.AlignVCenter)
        label_5.setObjectName("label_5")
        formLayout.setWidget(2, ?W...?FL...LabelRole, label_5)
        label_6 _ ?W...?L..(centralwidget)
        label_6.setAlignment(?C...__.AlignRight|?C...__.AlignTrailing|?C...__.AlignVCenter)
        label_6.setObjectName("label_6")
        formLayout.setWidget(3, ?W...?FL...LabelRole, label_6)
        temperatureLabel _ ?W...?L..(centralwidget)
        temperatureLabel.sT..("")
        temperatureLabel.setObjectName("temperatureLabel")
        formLayout.setWidget(3, ?W...?FL...FieldRole, temperatureLabel)
        label_7 _ ?W...?L..(centralwidget)
        label_7.setAlignment(?C...__.AlignRight|?C...__.AlignTrailing|?C...__.AlignVCenter)
        label_7.setObjectName("label_7")
        formLayout.setWidget(4, ?W...?FL...LabelRole, label_7)
        humidityLabel _ ?W...?L..(centralwidget)
        humidityLabel.sT..("")
        humidityLabel.setObjectName("humidityLabel")
        formLayout.setWidget(4, ?W...?FL...FieldRole, humidityLabel)
        label_8 _ ?W...?L..(centralwidget)
        label_8.setAlignment(?C...__.AlignRight|?C...__.AlignTrailing|?C...__.AlignVCenter)
        label_8.setObjectName("label_8")
        formLayout.setWidget(5, ?W...?FL...LabelRole, label_8)
        pressureLabel _ ?W...?L..(centralwidget)
        pressureLabel.sT..("")
        pressureLabel.setObjectName("pressureLabel")
        formLayout.setWidget(5, ?W...?FL...FieldRole, pressureLabel)
        label _ ?W...?L..(centralwidget)
        font _ ?G...?F..()
        font.setBold( st.
        font.sW..(75)
        label.sF..(font)
        label.setAlignment(?C...__.AlignRight|?C...__.AlignTrailing|?C...__.AlignVCenter)
        label.setObjectName("label")
        formLayout.setWidget(6, ?W...?FL...LabelRole, label)
        label_2 _ ?W...?L..(centralwidget)
        label_2.setAlignment(?C...__.AlignRight|?C...__.AlignTrailing|?C...__.AlignVCenter)
        label_2.setObjectName("label_2")
        formLayout.setWidget(7, ?W...?FL...LabelRole, label_2)
        longitudeLabel _ ?W...?L..(centralwidget)
        longitudeLabel.sT..("")
        longitudeLabel.setObjectName("longitudeLabel")
        formLayout.setWidget(7, ?W...?FL...FieldRole, longitudeLabel)
        label_3 _ ?W...?L..(centralwidget)
        label_3.setAlignment(?C...__.AlignRight|?C...__.AlignTrailing|?C...__.AlignVCenter)
        label_3.setObjectName("label_3")
        formLayout.setWidget(8, ?W...?FL...LabelRole, label_3)
        latitudeLabel _ ?W...?L..(centralwidget)
        latitudeLabel.sT..("")
        latitudeLabel.setObjectName("latitudeLabel")
        formLayout.setWidget(8, ?W...?FL...FieldRole, latitudeLabel)
        label_4 _ ?W...?L..(centralwidget)
        label_4.setAlignment(?C...__.AlignRight|?C...__.AlignTrailing|?C...__.AlignVCenter)
        label_4.setObjectName("label_4")
        formLayout.setWidget(9, ?W...?FL...LabelRole, label_4)
        sunriseLabel _ ?W...?L..(centralwidget)
        sunriseLabel.sT..("")
        sunriseLabel.setObjectName("sunriseLabel")
        formLayout.setWidget(9, ?W...?FL...FieldRole, sunriseLabel)
        label_9 _ ?W...?L..(centralwidget)
        label_9.setAlignment(?C...__.AlignRight|?C...__.AlignTrailing|?C...__.AlignVCenter)
        label_9.setObjectName("label_9")
        formLayout.setWidget(1, ?W...?FL...LabelRole, label_9)
        label_10 _ ?W...?L..(centralwidget)
        font _ ?G...?F..()
        font.setBold( st.
        font.sW..(75)
        label_10.sF..(font)
        label_10.setAlignment(?C...__.AlignRight|?C...__.AlignTrailing|?C...__.AlignVCenter)
        label_10.setObjectName("label_10")
        formLayout.setWidget(0, ?W...?FL...LabelRole, label_10)
        windLabel _ ?W...?L..(centralwidget)
        windLabel.sT..("")
        windLabel.setObjectName("windLabel")
        formLayout.setWidget(1, ?W...?FL...FieldRole, windLabel)
        label_11 _ ?W...?L..(centralwidget)
        label_11.sT..("")
        label_11.setObjectName("label_11")
        formLayout.setWidget(0, ?W...?FL...FieldRole, label_11)
        label_13 _ ?W...?L..(centralwidget)
        label_13.sT..("")
        label_13.setObjectName("label_13")
        formLayout.setWidget(6, ?W...?FL...FieldRole, label_13)
        label_12 _ ?W...?L..(centralwidget)
        label_12.sT..("")
        label_12.setObjectName("label_12")
        formLayout.setWidget(2, ?W...?FL...FieldRole, label_12)
        gridLayout.aL..(formLayout, 1, 0, 1, 1)
        verticalLayout.aL..(gridLayout)
        horizontalLayout.aL..(verticalLayout)
        MainWindow.sCW..(centralwidget)

        retranslateUi(MainWindow)
        ?C...QMetaObject.connectSlotsByName(MainWindow)

    ___ retranslateUi  MainWindow):
        _translate _ ?C... ?CA...translate
        MainWindow.sWT..(_translate("MainWindow", "Raindar"))
        lineEdit.sT..(_translate("MainWindow", "Utrecht,the Netherlands"))
        forecastTime1.sT..(_translate("MainWindow", "+3h"))
        forecastTime2.sT..(_translate("MainWindow", "+6h"))
        forecastTime3.sT..(_translate("MainWindow", "+9h"))
        forecastTime4.sT..(_translate("MainWindow", "+12h"))
        forecastTime5.sT..(_translate("MainWindow", "+15h"))
        label_5.sT..(_translate("MainWindow", "Barometer"))
        label_6.sT..(_translate("MainWindow", "Temperature"))
        label_7.sT..(_translate("MainWindow", "Humidity"))
        label_8.sT..(_translate("MainWindow", "Pressure"))
        label.sT..(_translate("MainWindow", "Location"))
        label_2.sT..(_translate("MainWindow", "Longitude"))
        label_3.sT..(_translate("MainWindow", "Latitude"))
        label_4.sT..(_translate("MainWindow", "Sunrise"))
        label_9.sT..(_translate("MainWindow", "Speed"))
        label_10.sT..(_translate("MainWindow", "Wind"))

