# ______ s......
#
# sock _ s____.s____ s____.A_I..., s____.S..._S...
# s___.b... 127.0.0.1 8888
# s___.l____ 5
# s___.s..b... F...
#
# client addr _ s___.ac...
# result _ c_____.r... 1024
# cl___.c....
#
# print('Message' r___.de___ utf-8)
