______ ?

?.knobDefault('Root.fps', '25')
?.knobDefault("Viewer.fps", "25")
?.knobDefault("Root.format", "1920 1080 0 0 1920 1080 1 FullHD")
?.knobDefault("Read.cached", "1")
?.knobDefault("Read.cacheLocal", "always")
?.knobDefault('Card.rows', '0' );
?.knobDefault('Card.columns', '0' );
?.knobDefault('ShuffleCopy.label', '[value in] -> [value out2]\n[value in2] -> [value out]')
?.knobDefault('Shuffle.label', '[value in] -> [value out]')
?.knobDefault('Blur.label', '[value size]')
?.knobDefault('Blur.channels', 'alpha')
?.knobDefault('IBKColourV3.screen_type', 'green')
?.knobDefault('IBKGizmoV3.st', 'C-green')
?.knobDefault("CheckerBoard.centerlinewidth","0")
?.knobDefault("FilterErode.channels","alpha")
?.knobDefault("Dilate.channels","alpha")
?.knobDefault("Write.bookmark", "True")
?.knobDefault("Merge.label", "[if {[value mix]<1} { value mix }]")
?.knobDefault("Saturation.label", "[if {[value saturation]<1} { value saturation }]")
?.knobDefault("Viewer.freezeGuiWhenPlayBack", "1")
?.knobDefault("Grain2.maskgrain", "False")
?.knobDefault("Card2.rows", "0.0")
?.knobDefault("Card2.columns", "0.0")
?.knobDefault("Viewer.tile_color", "1128481791")
?.knobDefault("Blur.mix", "1.0")
?.knobDefault("Blur.size", "2.0")