# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/lstomsl/PycharmProjects/PyQt5_course/ui/example.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DlgMain(object):
    def setupUi(self, DlgMain):
        DlgMain.setObjectName("DlgMain")
        DlgMain.resize(401, 325)
        self.grbDialog = QtWidgets.QGroupBox(DlgMain)
        self.grbDialog.setGeometry(QtCore.QRect(20, 10, 371, 211))
        self.grbDialog.setAlignment(QtCore.Qt.AlignCenter)
        self.grbDialog.setFlat(False)
        self.grbDialog.setCheckable(True)
        self.grbDialog.setObjectName("grbDialog")
        self.lbl1 = QtWidgets.QLabel(self.grbDialog)
        self.lbl1.setGeometry(QtCore.QRect(10, 30, 171, 16))
        self.lbl1.setObjectName("lbl1")
        self.dateTimeEdit = QtWidgets.QDateTimeEdit(self.grbDialog)
        self.dateTimeEdit.setGeometry(QtCore.QRect(0, 60, 194, 24))
        self.dateTimeEdit.setObjectName("dateTimeEdit")
        self.horizontalSlider = QtWidgets.QSlider(self.grbDialog)
        self.horizontalSlider.setGeometry(QtCore.QRect(0, 110, 171, 22))
        self.horizontalSlider.setMaximum(200)
        self.horizontalSlider.setProperty("value", 50)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.listWidget = QtWidgets.QListWidget(self.grbDialog)
        self.listWidget.setGeometry(QtCore.QRect(210, 30, 151, 181))
        self.listWidget.setObjectName("listWidget")
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        self.lcdNumber = QtWidgets.QLCDNumber(self.grbDialog)
        self.lcdNumber.setGeometry(QtCore.QRect(0, 140, 181, 61))
        self.lcdNumber.setObjectName("lcdNumber")
        self.lineEdit = QtWidgets.QLineEdit(DlgMain)
        self.lineEdit.setGeometry(QtCore.QRect(20, 230, 361, 21))
        self.lineEdit.setObjectName("lineEdit")
        self.label = QtWidgets.QLabel(DlgMain)
        self.label.setGeometry(QtCore.QRect(20, 270, 351, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setText("")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")

        self.retranslateUi(DlgMain)
        self.horizontalSlider.valueChanged['int'].connect(self.lcdNumber.display)
        self.lineEdit.textChanged['QString'].connect(self.label.setText)
        QtCore.QMetaObject.connectSlotsByName(DlgMain)
        DlgMain.setTabOrder(self.grbDialog, self.dateTimeEdit)
        DlgMain.setTabOrder(self.dateTimeEdit, self.horizontalSlider)
        DlgMain.setTabOrder(self.horizontalSlider, self.listWidget)

    def retranslateUi(self, DlgMain):
        _translate = QtCore.QCoreApplication.translate
        DlgMain.setWindowTitle(_translate("DlgMain", "My Gui"))
        self.grbDialog.setTitle(_translate("DlgMain", "My Gui Widgets"))
        self.lbl1.setText(_translate("DlgMain", "First Widget"))
        __sortingEnabled = self.listWidget.isSortingEnabled()
        self.listWidget.setSortingEnabled(False)
        item = self.listWidget.item(0)
        item.setText(_translate("DlgMain", "Item 1"))
        item = self.listWidget.item(1)
        item.setText(_translate("DlgMain", "Item 2"))
        item = self.listWidget.item(2)
        item.setText(_translate("DlgMain", "Item 3"))
        self.listWidget.setSortingEnabled(__sortingEnabled)
        self.lineEdit.setPlaceholderText(_translate("DlgMain", "Type something here"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DlgMain = QtWidgets.QDialog()
    ui = Ui_DlgMain()
    ui.setupUi(DlgMain)
    DlgMain.show()
    sys.exit(app.exec_())
