# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/lstomsl/PycharmProjects/PyQt5_course/ui/sqlAdd.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_sqlAdd(object):
    def setupUi(self, sqlAdd):
        sqlAdd.setObjectName("sqlAdd")
        sqlAdd.resize(240, 320)
        sqlAdd.setModal(True)
        self.formLayoutWidget = QtWidgets.QWidget(sqlAdd)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 40, 221, 221))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.lblId = QtWidgets.QLabel(self.formLayoutWidget)
        self.lblId.setObjectName("lblId")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.lblId)
        self.ledId = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.ledId.setReadOnly(True)
        self.ledId.setObjectName("ledId")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.ledId)
        self.lblFName = QtWidgets.QLabel(self.formLayoutWidget)
        self.lblFName.setObjectName("lblFName")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.lblFName)
        self.ledFName = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.ledFName.setObjectName("ledFName")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.ledFName)
        self.lblLName = QtWidgets.QLabel(self.formLayoutWidget)
        self.lblLName.setObjectName("lblLName")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.lblLName)
        self.ledLName = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.ledLName.setObjectName("ledLName")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.ledLName)
        self.lblEmail = QtWidgets.QLabel(self.formLayoutWidget)
        self.lblEmail.setObjectName("lblEmail")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.lblEmail)
        self.ledEmail = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.ledEmail.setObjectName("ledEmail")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.ledEmail)
        self.lblPhone = QtWidgets.QLabel(self.formLayoutWidget)
        self.lblPhone.setObjectName("lblPhone")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.lblPhone)
        self.ledPhone = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.ledPhone.setObjectName("ledPhone")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.ledPhone)
        self.lblPosition = QtWidgets.QLabel(self.formLayoutWidget)
        self.lblPosition.setObjectName("lblPosition")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.lblPosition)
        self.ledPosition = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.ledPosition.setObjectName("ledPosition")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.ledPosition)
        self.lblSupervisor = QtWidgets.QLabel(self.formLayoutWidget)
        self.lblSupervisor.setObjectName("lblSupervisor")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.lblSupervisor)
        self.cmbSupervisor = QtWidgets.QComboBox(self.formLayoutWidget)
        self.cmbSupervisor.setObjectName("cmbSupervisor")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.cmbSupervisor)
        self.lblHeading = QtWidgets.QLabel(sqlAdd)
        self.lblHeading.setGeometry(QtCore.QRect(9, 10, 221, 20))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.lblHeading.setFont(font)
        self.lblHeading.setAlignment(QtCore.Qt.AlignCenter)
        self.lblHeading.setObjectName("lblHeading")
        self.btnSubmit = QtWidgets.QPushButton(sqlAdd)
        self.btnSubmit.setGeometry(QtCore.QRect(10, 270, 221, 41))
        self.btnSubmit.setObjectName("btnSubmit")

        self.retranslateUi(sqlAdd)
        QtCore.QMetaObject.connectSlotsByName(sqlAdd)

    def retranslateUi(self, sqlAdd):
        _translate = QtCore.QCoreApplication.translate
        sqlAdd.setWindowTitle(_translate("sqlAdd", "Add New Employee"))
        self.lblId.setText(_translate("sqlAdd", "ID:"))
        self.lblFName.setText(_translate("sqlAdd", "First Name:"))
        self.lblLName.setText(_translate("sqlAdd", "Last Name:"))
        self.lblEmail.setText(_translate("sqlAdd", "Email:"))
        self.lblPhone.setText(_translate("sqlAdd", "Phone"))
        self.lblPosition.setText(_translate("sqlAdd", "Position:"))
        self.lblSupervisor.setText(_translate("sqlAdd", "Supervisor"))
        self.lblHeading.setText(_translate("sqlAdd", "New Employee"))
        self.btnSubmit.setText(_translate("sqlAdd", "Add Employee"))
