____ ? _______ ?

expected_lines """02-13 ...........
02-14 ..............
02-15 .................
02-16 ............
02-19 🐍.......🐍
02-20 ...
02-21 ..............🐍
02-22 🐍...................""".s..('\n')

___ test_valid_output(capfd
    create_chart()
    out, _ ?.r..
    ___ line __ expected_lines:
        ... line __ out, f'"{line}" should be in output of create_chart'