# # example 3 (TCP server socket)
# ______ s......
#
# sock _ s____.s____(s____.A._I... s____.S..._S...
# s___.b____ 127.0.0.1 8888
# s___.l_____ 5
#
# w... T..
#     t..
#         client, addr _ s___.a......
#     ex.. K...I....
#         s___.c...
#         b_____
#     e____
#         result _ cl__.r... 1024
#         cl__.cl...
#         print 'Message' r____.de__ utf-8
