# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.10
#
# WARNING! All changes made in this file will be lost!

____ ? ______ ?C.., ?G.., ?W..

c_ Ui_MainWindow o..
    ___ setupUi  MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.r..(549, 452)
        centralWidget _ ?W...?W..(MainWindow)
        sizePolicy _ ?W...?SP..(?W...?SP...Maximum, ?W...?SP...Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(centralWidget.sizePolicy().hasHeightForWidth())
        centralWidget.sSP..(sizePolicy)
        centralWidget.setObjectName("centralWidget")
        verticalLayout _ ?W...?VBL..(centralWidget)
        verticalLayout.sCM..(11, 11, 11, 11)
        verticalLayout.setSpacing(6)
        verticalLayout.setObjectName("verticalLayout")
        horizontalLayout _ ?W...?HBL..
        horizontalLayout.setSizeConstraint(?W...QLayout.SetDefaultConstraint)
        horizontalLayout.setSpacing(6)
        horizontalLayout.setObjectName("horizontalLayout")
        verticalLayout_2 _ ?W...?VBL..()
        verticalLayout_2.setSpacing(6)
        verticalLayout_2.setObjectName("verticalLayout_2")
        widget _ ?W...?W..(centralWidget)
        sizePolicy _ ?W...?SP..(?W...?SP...Maximum, ?W...?SP...Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(widget.sizePolicy().hasHeightForWidth())
        widget.sSP..(sizePolicy)
        widget.setObjectName("widget")
        gridLayout _ ?W...QGridLayout(widget)
        gridLayout.sCM..(11, 11, 11, 11)
        gridLayout.setSpacing(15)
        gridLayout.setObjectName("gridLayout")
        rectButton _ ?W...?PB..(widget)
        rectButton.sMS..(?C...?S..(30, 30))
        rectButton.sMS..(?C...?S..(30, 30))
        rectButton.sT..("")
        icon _ ?G...?I..
        icon.aP..(?G...?P..("images/layer-shape.png"), ?G...?I...Normal, ?G...?I...Off)
        rectButton.sI..(icon)
        rectButton.setCheckable( st.
        rectButton.setObjectName("rectButton")
        gridLayout.aW..(rectButton, 6, 0, 1, 1)
        polylineButton _ ?W...?PB..(widget)
        polylineButton.sMS..(?C...?S..(30, 30))
        polylineButton.sMS..(?C...?S..(30, 30))
        polylineButton.sT..("")
        icon1 _ ?G...?I..
        icon1.aP..(?G...?P..("images/layer-shape-polyline.png"), ?G...?I...Normal, ?G...?I...Off)
        polylineButton.sI..(icon1)
        polylineButton.setCheckable( st.
        polylineButton.setObjectName("polylineButton")
        gridLayout.aW..(polylineButton, 5, 1, 1, 1)
        selectrectButton _ ?W...?PB..(widget)
        sizePolicy _ ?W...?SP..(?W...?SP...Fixed, ?W...?SP...Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(selectrectButton.sizePolicy().hasHeightForWidth())
        selectrectButton.sSP..(sizePolicy)
        selectrectButton.sMS..(?C...?S..(30, 30))
        selectrectButton.sMS..(?C...?S..(30, 30))
        selectrectButton.sT..("")
        icon2 _ ?G...?I..
        icon2.aP..(?G...?P..("images/selection.png"), ?G...?I...Normal, ?G...?I...Off)
        selectrectButton.sI..(icon2)
        selectrectButton.setCheckable( st.
        selectrectButton.setObjectName("selectrectButton")
        gridLayout.aW..(selectrectButton, 0, 1, 1, 1)
        eraserButton _ ?W...?PB..(widget)
        sizePolicy _ ?W...?SP..(?W...?SP...Fixed, ?W...?SP...Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(eraserButton.sizePolicy().hasHeightForWidth())
        eraserButton.sSP..(sizePolicy)
        eraserButton.sMS..(?C...?S..(30, 30))
        eraserButton.sMS..(?C...?S..(30, 30))
        eraserButton.sT..("")
        icon3 _ ?G...?I..
        icon3.aP..(?G...?P..("images/eraser.png"), ?G...?I...Normal, ?G...?I...Off)
        eraserButton.sI..(icon3)
        eraserButton.setCheckable( st.
        eraserButton.setObjectName("eraserButton")
        gridLayout.aW..(eraserButton, 1, 0, 1, 1)
        stampButton _ ?W...?PB..(widget)
        sizePolicy _ ?W...?SP..(?W...?SP...Fixed, ?W...?SP...Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(stampButton.sizePolicy().hasHeightForWidth())
        stampButton.sSP..(sizePolicy)
        stampButton.sMS..(?C...?S..(30, 30))
        stampButton.sMS..(?C...?S..(30, 30))
        stampButton.sT..("")
        icon4 _ ?G...?I..
        icon4.aP..(?G...?P..("images/cake.png"), ?G...?I...Normal, ?G...?I...Off)
        stampButton.sI..(icon4)
        stampButton.setCheckable( st.
        stampButton.setObjectName("stampButton")
        gridLayout.aW..(stampButton, 2, 1, 1, 1)
        dropperButton _ ?W...?PB..(widget)
        sizePolicy _ ?W...?SP..(?W...?SP...Fixed, ?W...?SP...Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(dropperButton.sizePolicy().hasHeightForWidth())
        dropperButton.sSP..(sizePolicy)
        dropperButton.sMS..(?C...?S..(30, 30))
        dropperButton.sMS..(?C...?S..(30, 30))
        dropperButton.sT..("")
        icon5 _ ?G...?I..
        icon5.aP..(?G...?P..("images/pipette.png"), ?G...?I...Normal, ?G...?I...Off)
        dropperButton.sI..(icon5)
        dropperButton.setCheckable( st.
        dropperButton.setObjectName("dropperButton")
        gridLayout.aW..(dropperButton, 2, 0, 1, 1)
        selectpolyButton _ ?W...?PB..(widget)
        sizePolicy _ ?W...?SP..(?W...?SP...Fixed, ?W...?SP...Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(selectpolyButton.sizePolicy().hasHeightForWidth())
        selectpolyButton.sSP..(sizePolicy)
        selectpolyButton.sMS..(?C...?S..(30, 30))
        selectpolyButton.sMS..(?C...?S..(30, 30))
        selectpolyButton.sT..("")
        icon6 _ ?G...?I..
        icon6.aP..(?G...?P..("images/selection-poly.png"), ?G...?I...Normal, ?G...?I...Off)
        selectpolyButton.sI..(icon6)
        selectpolyButton.setCheckable( st.
        selectpolyButton.setObjectName("selectpolyButton")
        gridLayout.aW..(selectpolyButton, 0, 0, 1, 1)
        brushButton _ ?W...?PB..(widget)
        sizePolicy _ ?W...?SP..(?W...?SP...Fixed, ?W...?SP...Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(brushButton.sizePolicy().hasHeightForWidth())
        brushButton.sSP..(sizePolicy)
        brushButton.sMS..(?C...?S..(30, 30))
        brushButton.sMS..(?C...?S..(30, 30))
        brushButton.sT..("")
        icon7 _ ?G...?I..
        icon7.aP..(?G...?P..("images/paint-brush.png"), ?G...?I...Normal, ?G...?I...Off)
        brushButton.sI..(icon7)
        brushButton.setCheckable( st.
        brushButton.setObjectName("brushButton")
        gridLayout.aW..(brushButton, 3, 1, 1, 1)
        penButton _ ?W...?PB..(widget)
        sizePolicy _ ?W...?SP..(?W...?SP...Fixed, ?W...?SP...Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(penButton.sizePolicy().hasHeightForWidth())
        penButton.sSP..(sizePolicy)
        penButton.sMS..(?C...?S..(30, 30))
        penButton.sMS..(?C...?S..(30, 30))
        penButton.sT..("")
        icon8 _ ?G...?I..
        icon8.aP..(?G...?P..("images/pencil.png"), ?G...?I...Normal, ?G...?I...Off)
        penButton.sI..(icon8)
        penButton.setCheckable( st.
        penButton.setObjectName("penButton")
        gridLayout.aW..(penButton, 3, 0, 1, 1)
        fillButton _ ?W...?PB..(widget)
        sizePolicy _ ?W...?SP..(?W...?SP...Fixed, ?W...?SP...Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(fillButton.sizePolicy().hasHeightForWidth())
        fillButton.sSP..(sizePolicy)
        fillButton.sMS..(?C...?S..(30, 30))
        fillButton.sMS..(?C...?S..(30, 30))
        fillButton.sT..("")
        icon9 _ ?G...?I..
        icon9.aP..(?G...?P..("images/paint-can.png"), ?G...?I...Normal, ?G...?I...Off)
        fillButton.sI..(icon9)
        fillButton.setCheckable( st.
        fillButton.setObjectName("fillButton")
        gridLayout.aW..(fillButton, 1, 1, 1, 1)
        textButton _ ?W...?PB..(widget)
        sizePolicy _ ?W...?SP..(?W...?SP...Fixed, ?W...?SP...Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(textButton.sizePolicy().hasHeightForWidth())
        textButton.sSP..(sizePolicy)
        textButton.sMS..(?C...?S..(30, 30))
        textButton.sMS..(?C...?S..(30, 30))
        textButton.sT..("")
        icon10 _ ?G...?I..
        icon10.aP..(?G...?P..("images/edit.png"), ?G...?I...Normal, ?G...?I...Off)
        textButton.sI..(icon10)
        textButton.setCheckable( st.
        textButton.setObjectName("textButton")
        gridLayout.aW..(textButton, 4, 1, 1, 1)
        polygonButton _ ?W...?PB..(widget)
        polygonButton.sMS..(?C...?S..(30, 30))
        polygonButton.sMS..(?C...?S..(30, 30))
        polygonButton.sT..("")
        icon11 _ ?G...?I..
        icon11.aP..(?G...?P..("images/layer-shape-polygon.png"), ?G...?I...Normal, ?G...?I...Off)
        polygonButton.sI..(icon11)
        polygonButton.setCheckable( st.
        polygonButton.setObjectName("polygonButton")
        gridLayout.aW..(polygonButton, 6, 1, 1, 1)
        roundrectButton _ ?W...?PB..(widget)
        roundrectButton.sMS..(?C...?S..(30, 30))
        roundrectButton.sMS..(?C...?S..(30, 30))
        roundrectButton.sT..("")
        icon12 _ ?G...?I..
        icon12.aP..(?G...?P..("images/layer-shape-round.png"), ?G...?I...Normal, ?G...?I...Off)
        roundrectButton.sI..(icon12)
        roundrectButton.setCheckable( st.
        roundrectButton.setObjectName("roundrectButton")
        gridLayout.aW..(roundrectButton, 7, 1, 1, 1)
        ellipseButton _ ?W...?PB..(widget)
        ellipseButton.sMS..(?C...?S..(30, 30))
        ellipseButton.sMS..(?C...?S..(30, 30))
        ellipseButton.sT..("")
        icon13 _ ?G...?I..
        icon13.aP..(?G...?P..("images/layer-shape-ellipse.png"), ?G...?I...Normal, ?G...?I...Off)
        ellipseButton.sI..(icon13)
        ellipseButton.setCheckable( st.
        ellipseButton.setObjectName("ellipseButton")
        gridLayout.aW..(ellipseButton, 7, 0, 1, 1)
        lineButton _ ?W...?PB..(widget)
        lineButton.sMS..(?C...?S..(30, 30))
        lineButton.sMS..(?C...?S..(30, 30))
        lineButton.sT..("")
        icon14 _ ?G...?I..
        icon14.aP..(?G...?P..("images/layer-shape-line.png"), ?G...?I...Normal, ?G...?I...Off)
        lineButton.sI..(icon14)
        lineButton.setCheckable( st.
        lineButton.setObjectName("lineButton")
        gridLayout.aW..(lineButton, 5, 0, 1, 1)
        sprayButton _ ?W...?PB..(widget)
        sizePolicy _ ?W...?SP..(?W...?SP...Minimum, ?W...?SP...Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(sprayButton.sizePolicy().hasHeightForWidth())
        sprayButton.sSP..(sizePolicy)
        sprayButton.sMS..(?C...?S..(30, 30))
        sprayButton.sMS..(?C...?S..(30, 30))
        sprayButton.sT..("")
        icon15 _ ?G...?I..
        icon15.aP..(?G...?P..("images/spray.png"), ?G...?I...Normal, ?G...?I...Off)
        sprayButton.sI..(icon15)
        sprayButton.setCheckable( st.
        sprayButton.setFlat(F..)
        sprayButton.setObjectName("sprayButton")
        gridLayout.aW..(sprayButton, 4, 0, 1, 1)
        verticalLayout_2.aW..(widget)
        spacerItem _ ?W...?SI..(20, 40, ?W...?SP...Minimum, ?W...?SP...E..)
        verticalLayout_2.aI..(spacerItem)
        horizontalLayout.aL..(verticalLayout_2)
        canvas _ ?W...?L..(centralWidget)
        sizePolicy _ ?W...?SP..(?W...?SP...ME.., ?W...?SP...ME..)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(canvas.sizePolicy().hasHeightForWidth())
        canvas.sSP..(sizePolicy)
        canvas.sT..("")
        canvas.setObjectName("canvas")
        horizontalLayout.aW..(canvas)
        verticalLayout.aL..(horizontalLayout)
        horizontalLayout_2 _ ?W...?HBL..
        horizontalLayout_2.setSpacing(6)
        horizontalLayout_2.setObjectName("horizontalLayout_2")
        widget_3 _ ?W...?W..(centralWidget)
        widget_3.sMS..(?C...?S..(78, 0))
        widget_3.sMS..(?C...?S..(78, 16777215))
        widget_3.setObjectName("widget_3")
        secondaryButton _ ?W...?PB..(widget_3)
        secondaryButton.setGeometry(?C...QRect(30, 10, 40, 40))
        secondaryButton.sMS..(?C...?S..(40, 40))
        secondaryButton.sMS..(?C...?S..(40, 40))
        secondaryButton.sT..("")
        secondaryButton.setObjectName("secondaryButton")
        primaryButton _ ?W...?PB..(widget_3)
        primaryButton.setGeometry(?C...QRect(10, 0, 40, 40))
        primaryButton.sMS..(?C...?S..(40, 40))
        primaryButton.sMS..(?C...?S..(40, 40))
        primaryButton.sT..("")
        primaryButton.setObjectName("primaryButton")
        horizontalLayout_2.aW..(widget_3)
        widget_2 _ ?W...?W..(centralWidget)
        widget_2.setObjectName("widget_2")
        gridLayout_2 _ ?W...QGridLayout(widget_2)
        gridLayout_2.sCM..(15, 0, 15, 15)
        gridLayout_2.setSpacing(15)
        gridLayout_2.setObjectName("gridLayout_2")
        colorButton_11 _ ?W...?PB..(widget_2)
        sizePolicy _ ?W...?SP..(?W...?SP...Fixed, ?W...?SP...Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(colorButton_11.sizePolicy().hasHeightForWidth())
        colorButton_11.sSP..(sizePolicy)
        colorButton_11.sMS..(?C...?S..(20, 20))
        colorButton_11.sMS..(?C...?S..(20, 13))
        colorButton_11.sT..("")
        colorButton_11.setObjectName("colorButton_11")
        gridLayout_2.aW..(colorButton_11, 0, 10, 1, 1)
        colorButton_7 _ ?W...?PB..(widget_2)
        sizePolicy _ ?W...?SP..(?W...?SP...Fixed, ?W...?SP...Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(colorButton_7.sizePolicy().hasHeightForWidth())
        colorButton_7.sSP..(sizePolicy)
        colorButton_7.sMS..(?C...?S..(20, 20))
        colorButton_7.sMS..(?C...?S..(20, 13))
        colorButton_7.sT..("")
        colorButton_7.setObjectName("colorButton_7")
        gridLayout_2.aW..(colorButton_7, 0, 6, 1, 1)
        colorButton_9 _ ?W...?PB..(widget_2)
        sizePolicy _ ?W...?SP..(?W...?SP...Fixed, ?W...?SP...Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(colorButton_9.sizePolicy().hasHeightForWidth())
        colorButton_9.sSP..(sizePolicy)
        colorButton_9.sMS..(?C...?S..(20, 20))
        colorButton_9.sMS..(?C...?S..(20, 13))
        colorButton_9.sT..("")
        colorButton_9.setObjectName("colorButton_9")
        gridLayout_2.aW..(colorButton_9, 0, 8, 1, 1)
        colorButton_10 _ ?W...?PB..(widget_2)
        sizePolicy _ ?W...?SP..(?W...?SP...Fixed, ?W...?SP...Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(colorButton_10.sizePolicy().hasHeightForWidth())
        colorButton_10.sSP..(sizePolicy)
        colorButton_10.sMS..(?C...?S..(20, 20))
        colorButton_10.sMS..(?C...?S..(20, 13))
        colorButton_10.sT..("")
        colorButton_10.setObjectName("colorButton_10")
        gridLayout_2.aW..(colorButton_10, 0, 9, 1, 1)
        colorButton_23 _ ?W...?PB..(widget_2)
        sizePolicy _ ?W...?SP..(?W...?SP...Fixed, ?W...?SP...Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(colorButton_23.sizePolicy().hasHeightForWidth())
        colorButton_23.sSP..(sizePolicy)
        colorButton_23.sMS..(?C...?S..(20, 20))
        colorButton_23.sMS..(?C...?S..(20, 13))
        colorButton_23.sT..("")
        colorButton_23.setObjectName("colorButton_23")
        gridLayout_2.aW..(colorButton_23, 1, 8, 1, 1)
        colorButton_18 _ ?W...?PB..(widget_2)
        sizePolicy _ ?W...?SP..(?W...?SP...Fixed, ?W...?SP...Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(colorButton_18.sizePolicy().hasHeightForWidth())
        colorButton_18.sSP..(sizePolicy)
        colorButton_18.sMS..(?C...?S..(20, 20))
        colorButton_18.sMS..(?C...?S..(20, 13))
        colorButton_18.sT..("")
        colorButton_18.setObjectName("colorButton_18")
        gridLayout_2.aW..(colorButton_18, 1, 3, 1, 1)
        colorButton_20 _ ?W...?PB..(widget_2)
        sizePolicy _ ?W...?SP..(?W...?SP...Fixed, ?W...?SP...Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(colorButton_20.sizePolicy().hasHeightForWidth())
        colorButton_20.sSP..(sizePolicy)
        colorButton_20.sMS..(?C...?S..(20, 20))
        colorButton_20.sMS..(?C...?S..(20, 13))
        colorButton_20.sT..("")
        colorButton_20.setObjectName("colorButton_20")
        gridLayout_2.aW..(colorButton_20, 1, 5, 1, 1)
        colorButton_6 _ ?W...?PB..(widget_2)
        sizePolicy _ ?W...?SP..(?W...?SP...Fixed, ?W...?SP...Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(colorButton_6.sizePolicy().hasHeightForWidth())
        colorButton_6.sSP..(sizePolicy)
        colorButton_6.sMS..(?C...?S..(20, 20))
        colorButton_6.sMS..(?C...?S..(20, 13))
        colorButton_6.sT..("")
        colorButton_6.setObjectName("colorButton_6")
        gridLayout_2.aW..(colorButton_6, 0, 5, 1, 1)
        colorButton_3 _ ?W...?PB..(widget_2)
        sizePolicy _ ?W...?SP..(?W...?SP...Fixed, ?W...?SP...Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(colorButton_3.sizePolicy().hasHeightForWidth())
        colorButton_3.sSP..(sizePolicy)
        colorButton_3.sMS..(?C...?S..(20, 20))
        colorButton_3.sMS..(?C...?S..(20, 13))
        colorButton_3.sT..("")
        colorButton_3.setObjectName("colorButton_3")
        gridLayout_2.aW..(colorButton_3, 0, 2, 1, 1)
        colorButton_24 _ ?W...?PB..(widget_2)
        sizePolicy _ ?W...?SP..(?W...?SP...Fixed, ?W...?SP...Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(colorButton_24.sizePolicy().hasHeightForWidth())
        colorButton_24.sSP..(sizePolicy)
        colorButton_24.sMS..(?C...?S..(20, 20))
        colorButton_24.sMS..(?C...?S..(20, 13))
        colorButton_24.sT..("")
        colorButton_24.setObjectName("colorButton_24")
        gridLayout_2.aW..(colorButton_24, 1, 9, 1, 1)
        colorButton_17 _ ?W...?PB..(widget_2)
        sizePolicy _ ?W...?SP..(?W...?SP...Fixed, ?W...?SP...Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(colorButton_17.sizePolicy().hasHeightForWidth())
        colorButton_17.sSP..(sizePolicy)
        colorButton_17.sMS..(?C...?S..(20, 20))
        colorButton_17.sMS..(?C...?S..(20, 13))
        colorButton_17.sT..("")
        colorButton_17.setObjectName("colorButton_17")
        gridLayout_2.aW..(colorButton_17, 1, 2, 1, 1)
        colorButton_1 _ ?W...?PB..(widget_2)
        sizePolicy _ ?W...?SP..(?W...?SP...Fixed, ?W...?SP...Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(colorButton_1.sizePolicy().hasHeightForWidth())
        colorButton_1.sSP..(sizePolicy)
        colorButton_1.sMS..(?C...?S..(20, 20))
        colorButton_1.sMS..(?C...?S..(20, 13))
        colorButton_1.sSS..("")
        colorButton_1.sT..("")
        colorButton_1.setObjectName("colorButton_1")
        gridLayout_2.aW..(colorButton_1, 0, 0, 1, 1)
        colorButton_8 _ ?W...?PB..(widget_2)
        sizePolicy _ ?W...?SP..(?W...?SP...Fixed, ?W...?SP...Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(colorButton_8.sizePolicy().hasHeightForWidth())
        colorButton_8.sSP..(sizePolicy)
        colorButton_8.sMS..(?C...?S..(20, 20))
        colorButton_8.sMS..(?C...?S..(20, 13))
        colorButton_8.sT..("")
        colorButton_8.setObjectName("colorButton_8")
        gridLayout_2.aW..(colorButton_8, 0, 7, 1, 1)
        colorButton_27 _ ?W...?PB..(widget_2)
        sizePolicy _ ?W...?SP..(?W...?SP...Fixed, ?W...?SP...Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(colorButton_27.sizePolicy().hasHeightForWidth())
        colorButton_27.sSP..(sizePolicy)
        colorButton_27.sMS..(?C...?S..(20, 20))
        colorButton_27.sMS..(?C...?S..(20, 13))
        colorButton_27.sT..("")
        colorButton_27.setObjectName("colorButton_27")
        gridLayout_2.aW..(colorButton_27, 1, 12, 1, 1)
        colorButton_22 _ ?W...?PB..(widget_2)
        sizePolicy _ ?W...?SP..(?W...?SP...Fixed, ?W...?SP...Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(colorButton_22.sizePolicy().hasHeightForWidth())
        colorButton_22.sSP..(sizePolicy)
        colorButton_22.sMS..(?C...?S..(20, 20))
        colorButton_22.sMS..(?C...?S..(20, 13))
        colorButton_22.sT..("")
        colorButton_22.setObjectName("colorButton_22")
        gridLayout_2.aW..(colorButton_22, 1, 7, 1, 1)
        colorButton_15 _ ?W...?PB..(widget_2)
        sizePolicy _ ?W...?SP..(?W...?SP...Fixed, ?W...?SP...Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(colorButton_15.sizePolicy().hasHeightForWidth())
        colorButton_15.sSP..(sizePolicy)
        colorButton_15.sMS..(?C...?S..(20, 20))
        colorButton_15.sMS..(?C...?S..(20, 13))
        colorButton_15.sT..("")
        colorButton_15.setObjectName("colorButton_15")
        gridLayout_2.aW..(colorButton_15, 1, 0, 1, 1)
        colorButton_5 _ ?W...?PB..(widget_2)
        sizePolicy _ ?W...?SP..(?W...?SP...Fixed, ?W...?SP...Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(colorButton_5.sizePolicy().hasHeightForWidth())
        colorButton_5.sSP..(sizePolicy)
        colorButton_5.sMS..(?C...?S..(20, 20))
        colorButton_5.sMS..(?C...?S..(20, 13))
        colorButton_5.sT..("")
        colorButton_5.setObjectName("colorButton_5")
        gridLayout_2.aW..(colorButton_5, 0, 4, 1, 1)
        colorButton_2 _ ?W...?PB..(widget_2)
        sizePolicy _ ?W...?SP..(?W...?SP...Fixed, ?W...?SP...Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(colorButton_2.sizePolicy().hasHeightForWidth())
        colorButton_2.sSP..(sizePolicy)
        colorButton_2.sMS..(?C...?S..(20, 20))
        colorButton_2.sMS..(?C...?S..(20, 13))
        colorButton_2.sT..("")
        colorButton_2.setObjectName("colorButton_2")
        gridLayout_2.aW..(colorButton_2, 0, 1, 1, 1)
        colorButton_16 _ ?W...?PB..(widget_2)
        sizePolicy _ ?W...?SP..(?W...?SP...Fixed, ?W...?SP...Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(colorButton_16.sizePolicy().hasHeightForWidth())
        colorButton_16.sSP..(sizePolicy)
        colorButton_16.sMS..(?C...?S..(20, 20))
        colorButton_16.sMS..(?C...?S..(20, 13))
        colorButton_16.sT..("")
        colorButton_16.setObjectName("colorButton_16")
        gridLayout_2.aW..(colorButton_16, 1, 1, 1, 1)
        colorButton_14 _ ?W...?PB..(widget_2)
        sizePolicy _ ?W...?SP..(?W...?SP...Fixed, ?W...?SP...Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(colorButton_14.sizePolicy().hasHeightForWidth())
        colorButton_14.sSP..(sizePolicy)
        colorButton_14.sMS..(?C...?S..(20, 20))
        colorButton_14.sMS..(?C...?S..(20, 13))
        colorButton_14.sT..("")
        colorButton_14.setObjectName("colorButton_14")
        gridLayout_2.aW..(colorButton_14, 0, 13, 1, 1)
        colorButton_4 _ ?W...?PB..(widget_2)
        sizePolicy _ ?W...?SP..(?W...?SP...Fixed, ?W...?SP...Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(colorButton_4.sizePolicy().hasHeightForWidth())
        colorButton_4.sSP..(sizePolicy)
        colorButton_4.sMS..(?C...?S..(20, 20))
        colorButton_4.sMS..(?C...?S..(20, 13))
        colorButton_4.sT..("")
        colorButton_4.setObjectName("colorButton_4")
        gridLayout_2.aW..(colorButton_4, 0, 3, 1, 1)
        colorButton_21 _ ?W...?PB..(widget_2)
        sizePolicy _ ?W...?SP..(?W...?SP...Fixed, ?W...?SP...Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(colorButton_21.sizePolicy().hasHeightForWidth())
        colorButton_21.sSP..(sizePolicy)
        colorButton_21.sMS..(?C...?S..(20, 20))
        colorButton_21.sMS..(?C...?S..(20, 13))
        colorButton_21.sT..("")
        colorButton_21.setObjectName("colorButton_21")
        gridLayout_2.aW..(colorButton_21, 1, 6, 1, 1)
        colorButton_25 _ ?W...?PB..(widget_2)
        sizePolicy _ ?W...?SP..(?W...?SP...Fixed, ?W...?SP...Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(colorButton_25.sizePolicy().hasHeightForWidth())
        colorButton_25.sSP..(sizePolicy)
        colorButton_25.sMS..(?C...?S..(20, 20))
        colorButton_25.sMS..(?C...?S..(20, 13))
        colorButton_25.sT..("")
        colorButton_25.setObjectName("colorButton_25")
        gridLayout_2.aW..(colorButton_25, 1, 10, 1, 1)
        colorButton_12 _ ?W...?PB..(widget_2)
        sizePolicy _ ?W...?SP..(?W...?SP...Fixed, ?W...?SP...Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(colorButton_12.sizePolicy().hasHeightForWidth())
        colorButton_12.sSP..(sizePolicy)
        colorButton_12.sMS..(?C...?S..(20, 20))
        colorButton_12.sMS..(?C...?S..(20, 13))
        colorButton_12.sT..("")
        colorButton_12.setObjectName("colorButton_12")
        gridLayout_2.aW..(colorButton_12, 0, 11, 1, 1)
        colorButton_19 _ ?W...?PB..(widget_2)
        sizePolicy _ ?W...?SP..(?W...?SP...Fixed, ?W...?SP...Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(colorButton_19.sizePolicy().hasHeightForWidth())
        colorButton_19.sSP..(sizePolicy)
        colorButton_19.sMS..(?C...?S..(20, 20))
        colorButton_19.sMS..(?C...?S..(20, 13))
        colorButton_19.sT..("")
        colorButton_19.setObjectName("colorButton_19")
        gridLayout_2.aW..(colorButton_19, 1, 4, 1, 1)
        colorButton_13 _ ?W...?PB..(widget_2)
        sizePolicy _ ?W...?SP..(?W...?SP...Fixed, ?W...?SP...Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(colorButton_13.sizePolicy().hasHeightForWidth())
        colorButton_13.sSP..(sizePolicy)
        colorButton_13.sMS..(?C...?S..(20, 20))
        colorButton_13.sMS..(?C...?S..(20, 13))
        colorButton_13.sT..("")
        colorButton_13.setObjectName("colorButton_13")
        gridLayout_2.aW..(colorButton_13, 0, 12, 1, 1)
        colorButton_26 _ ?W...?PB..(widget_2)
        sizePolicy _ ?W...?SP..(?W...?SP...Fixed, ?W...?SP...Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(colorButton_26.sizePolicy().hasHeightForWidth())
        colorButton_26.sSP..(sizePolicy)
        colorButton_26.sMS..(?C...?S..(20, 20))
        colorButton_26.sMS..(?C...?S..(20, 13))
        colorButton_26.sT..("")
        colorButton_26.setObjectName("colorButton_26")
        gridLayout_2.aW..(colorButton_26, 1, 11, 1, 1)
        colorButton_28 _ ?W...?PB..(widget_2)
        sizePolicy _ ?W...?SP..(?W...?SP...Fixed, ?W...?SP...Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(colorButton_28.sizePolicy().hasHeightForWidth())
        colorButton_28.sSP..(sizePolicy)
        colorButton_28.sMS..(?C...?S..(20, 20))
        colorButton_28.sMS..(?C...?S..(20, 13))
        colorButton_28.sT..("")
        colorButton_28.setObjectName("colorButton_28")
        gridLayout_2.aW..(colorButton_28, 1, 13, 1, 1)
        horizontalLayout_2.aW..(widget_2)
        stampnextButton _ ?W...?PB..(centralWidget)
        stampnextButton.sMS..(?C...?S..(78, 55))
        stampnextButton.sMS..(?C...?S..(78, 55))
        stampnextButton.sT..("")
        stampnextButton.setIconSize(?C...?S..(80, 50))
        stampnextButton.setObjectName("stampnextButton")
        horizontalLayout_2.aW..(stampnextButton)
        spacerItem1 _ ?W...?SI..(40, 20, ?W...?SP...E.., ?W...?SP...Minimum)
        horizontalLayout_2.aI..(spacerItem1)
        verticalLayout.aL..(horizontalLayout_2)
        MainWindow.setCentralWidget(centralWidget)
        menuBar _ ?W...QMenuBar(MainWindow)
        menuBar.setGeometry(?C...QRect(0, 0, 549, 22))
        menuBar.setObjectName("menuBar")
        menuFIle _ ?W...?M..(menuBar)
        menuFIle.setObjectName("menuFIle")
        menuEdit _ ?W...?M..(menuBar)
        menuEdit.setObjectName("menuEdit")
        menuImage _ ?W...?M..(menuBar)
        menuImage.setObjectName("menuImage")
        menuHelp _ ?W...?M..(menuBar)
        menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(menuBar)
        statusBar _ ?W...QStatusBar(MainWindow)
        statusBar.setObjectName("statusBar")
        MainWindow.sSB..(statusBar)
        fileToolbar _ ?W...QToolBar(MainWindow)
        fileToolbar.setIconSize(?C...?S..(16, 16))
        fileToolbar.setObjectName("fileToolbar")
        MainWindow.aTB..(?C...__.TopToolBarArea, fileToolbar)
        drawingToolbar _ ?W...QToolBar(MainWindow)
        drawingToolbar.setIconSize(?C...?S..(16, 16))
        drawingToolbar.setObjectName("drawingToolbar")
        MainWindow.aTB..(?C...__.TopToolBarArea, drawingToolbar)
        fontToolbar _ ?W...QToolBar(MainWindow)
        fontToolbar.setIconSize(?C...?S..(16, 16))
        fontToolbar.setObjectName("fontToolbar")
        MainWindow.aTB..(?C...__.TopToolBarArea, fontToolbar)
        actionCopy _ ?W...?A..(MainWindow)
        actionCopy.setObjectName("actionCopy")
        actionClearImage _ ?W...?A..(MainWindow)
        actionClearImage.setObjectName("actionClearImage")
        actionOpenImage _ ?W...?A..(MainWindow)
        icon16 _ ?G...?I..
        icon16.aP..(?G...?P..("images/blue-folder-open-image.png"), ?G...?I...Normal, ?G...?I...Off)
        actionOpenImage.sI..(icon16)
        actionOpenImage.setObjectName("actionOpenImage")
        actionSaveImage _ ?W...?A..(MainWindow)
        icon17 _ ?G...?I..
        icon17.aP..(?G...?P..("images/disk.png"), ?G...?I...Normal, ?G...?I...Off)
        actionSaveImage.sI..(icon17)
        actionSaveImage.setObjectName("actionSaveImage")
        actionInvertColors _ ?W...?A..(MainWindow)
        actionInvertColors.setObjectName("actionInvertColors")
        actionFlipHorizontal _ ?W...?A..(MainWindow)
        actionFlipHorizontal.setObjectName("actionFlipHorizontal")
        actionFlipVertical _ ?W...?A..(MainWindow)
        actionFlipVertical.setObjectName("actionFlipVertical")
        actionNewImage _ ?W...?A..(MainWindow)
        icon18 _ ?G...?I..
        icon18.aP..(?G...?P..("images/document-image.png"), ?G...?I...Normal, ?G...?I...Off)
        actionNewImage.sI..(icon18)
        actionNewImage.setObjectName("actionNewImage")
        actionBold _ ?W...?A..(MainWindow)
        actionBold.setCheckable( st.
        icon19 _ ?G...?I..
        icon19.aP..(?G...?P..("images/edit-bold.png"), ?G...?I...Normal, ?G...?I...Off)
        actionBold.sI..(icon19)
        actionBold.setObjectName("actionBold")
        actionItalic _ ?W...?A..(MainWindow)
        actionItalic.setCheckable( st.
        icon20 _ ?G...?I..
        icon20.aP..(?G...?P..("images/edit-italic.png"), ?G...?I...Normal, ?G...?I...Off)
        actionItalic.sI..(icon20)
        actionItalic.setObjectName("actionItalic")
        actionUnderline _ ?W...?A..(MainWindow)
        actionUnderline.setCheckable( st.
        icon21 _ ?G...?I..
        icon21.aP..(?G...?P..("images/edit-underline.png"), ?G...?I...Normal, ?G...?I...Off)
        actionUnderline.sI..(icon21)
        actionUnderline.setObjectName("actionUnderline")
        actionFillShapes _ ?W...?A..(MainWindow)
        actionFillShapes.setCheckable( st.
        icon22 _ ?G...?I..
        icon22.aP..(?G...?P..("images/paint-can-color.png"), ?G...?I...Normal, ?G...?I...Off)
        actionFillShapes.sI..(icon22)
        actionFillShapes.setObjectName("actionFillShapes")
        menuFIle.aA..(actionNewImage)
        menuFIle.aA..(actionOpenImage)
        menuFIle.aA..(actionSaveImage)
        menuEdit.aA..(actionCopy)
        menuEdit.aS..)
        menuEdit.aA..(actionClearImage)
        menuImage.aA..(actionInvertColors)
        menuImage.aS..)
        menuImage.aA..(actionFlipHorizontal)
        menuImage.aA..(actionFlipVertical)
        menuBar.aA..(menuFIle.menuAction())
        menuBar.aA..(menuEdit.menuAction())
        menuBar.aA..(menuImage.menuAction())
        menuBar.aA..(menuHelp.menuAction())
        fileToolbar.aA..(actionNewImage)
        fileToolbar.aA..(actionOpenImage)
        fileToolbar.aA..(actionSaveImage)

        retranslateUi(MainWindow)
        ?C...QMetaObject.connectSlotsByName(MainWindow)

    ___ retranslateUi  MainWindow):
        _translate _ ?C... ?CA...translate
        MainWindow.sWT..(_translate("MainWindow", "Piecasso"))
        menuFIle.setTitle(_translate("MainWindow", "FIle"))
        menuEdit.setTitle(_translate("MainWindow", "Edit"))
        menuImage.setTitle(_translate("MainWindow", "Image"))
        menuHelp.setTitle(_translate("MainWindow", "Help"))
        fileToolbar.sWT..(_translate("MainWindow", "toolBar"))
        drawingToolbar.sWT..(_translate("MainWindow", "toolBar"))
        fontToolbar.sWT..(_translate("MainWindow", "toolBar"))
        actionCopy.sT..(_translate("MainWindow", "Copy"))
        actionCopy.setShortcut(_translate("MainWindow", "Ctrl+C"))
        actionClearImage.sT..(_translate("MainWindow", "Clear Image"))
        actionOpenImage.sT..(_translate("MainWindow", "Open Image..."))
        actionSaveImage.sT..(_translate("MainWindow", "Save Image As..."))
        actionInvertColors.sT..(_translate("MainWindow", "Invert Colors"))
        actionFlipHorizontal.sT..(_translate("MainWindow", "Flip Horizontal"))
        actionFlipVertical.sT..(_translate("MainWindow", "Flip Vertical"))
        actionNewImage.sT..(_translate("MainWindow", "New Image"))
        actionBold.sT..(_translate("MainWindow", "Bold"))
        actionBold.setShortcut(_translate("MainWindow", "Ctrl+B"))
        actionItalic.sT..(_translate("MainWindow", "Italic"))
        actionItalic.setShortcut(_translate("MainWindow", "Ctrl+I"))
        actionUnderline.sT..(_translate("MainWindow", "Underline"))
        actionFillShapes.sT..(_translate("MainWindow", "Fill Shapes?"))

