# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created: Sat Oct 25 13:40:24 2014
#      by: PyQt5 UI code generator 5.2.1
#
# WARNING! All changes made in this file will be lost!

____ ? _______ ?C.., ?G.., ?W..

c_ Ui_MainWindow(object):
    ___ setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.r..(925, 852)
        centralwidget = ?W...QWidget(MainWindow)
        centralwidget.setEnabled(True)
        sizePolicy = ?W...QSizePolicy(?W...QSizePolicy.Preferred, ?W...QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(centralwidget.sizePolicy().hasHeightForWidth())
        centralwidget.setSizePolicy(sizePolicy)
        centralwidget.setCursor(?G...QCursor(?C...Qt.ArrowCursor))
        centralwidget.setLayoutDirection(?C...Qt.LeftToRight)
        centralwidget.setAutoFillBackground(False)
        centralwidget.setObjectName("centralwidget")
        verticalLayout_5 = ?W...QVBoxLayout(centralwidget)
        verticalLayout_5.setObjectName("verticalLayout_5")
        verticalLayout_main = ?W...QVBoxLayout()
        verticalLayout_main.setSizeConstraint(?W...QLayout.SetMaximumSize)
        verticalLayout_main.setObjectName("verticalLayout_main")
        horizontall_up = ?W...QHBoxLayout()
        horizontall_up.setObjectName("horizontall_up")
        label = ?W...?L..(centralwidget)
        label.setObjectName("label")
        horizontall_up.aW..(label)
        mongoHost = ?W...?LE..(centralwidget)
        mongoHost.setObjectName("mongoHost")
        horizontall_up.aW..(mongoHost)
        connectBtn = ?W...?PB..(centralwidget)
        connectBtn.setObjectName("connectBtn")
        horizontall_up.aW..(connectBtn)
        spacerItem = ?W...QSpacerItem(40, 20, ?W...QSizePolicy.Expanding, ?W...QSizePolicy.Minimum)
        horizontall_up.aI..(spacerItem)
        verticalLayout_main.addLayout(horizontall_up)
        horizontalLayout = ?W...QHBoxLayout()
        horizontalLayout.setObjectName("horizontalLayout")
        preview1 = ?W...?L..(centralwidget)
        preview1.setObjectName("preview1")
        horizontalLayout.aW..(preview1)
        preview = ?W...?LE..(centralwidget)
        preview.setReadOnly(True)
        preview.setObjectName("preview")
        horizontalLayout.aW..(preview)
        querytime = ?W...?L..(centralwidget)
        querytime.setMinimumSize(?C...QSize(200, 0))
        querytime.sT..("")
        querytime.setObjectName("querytime")
        horizontalLayout.aW..(querytime)
        verticalLayout_main.addLayout(horizontalLayout)
        horizontal_down = ?W...QHBoxLayout()
        horizontal_down.setObjectName("horizontal_down")
        treeWidget = ?W...QTreeWidget(centralwidget)
        treeWidget.setEnabled(True)
        treeWidget.setMaximumSize(?C...QSize(200, 16777215))
        treeWidget.setBaseSize(?C...QSize(0, 0))
        treeWidget.setObjectName("treeWidget")
        horizontal_down.aW..(treeWidget)
        verticall_down_right = ?W...QVBoxLayout()
        verticall_down_right.setObjectName("verticall_down_right")
        horizontalLayout_2 = ?W...QHBoxLayout()
        horizontalLayout_2.setObjectName("horizontalLayout_2")
        query = ?W...?LE..(centralwidget)
        query.setInputMethodHints(?C...Qt.ImhHiddenText)
        query.sT..("")
        query.setClearButtonEnabled(True)
        query.setObjectName("query")
        horizontalLayout_2.aW..(query)
        label_2 = ?W...?L..(centralwidget)
        label_2.setObjectName("label_2")
        horizontalLayout_2.aW..(label_2)
        sort = ?W...?LE..(centralwidget)
        sizePolicy = ?W...QSizePolicy(?W...QSizePolicy.Minimum, ?W...QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(sort.sizePolicy().hasHeightForWidth())
        sort.setSizePolicy(sizePolicy)
        sort.setMinimumSize(?C...QSize(100, 0))
        sort.setInputMethodHints(?C...Qt.ImhNone)
        sort.sT..("")
        sort.setClearButtonEnabled(False)
        sort.setObjectName("sort")
        horizontalLayout_2.aW..(sort)
        querybtn = ?W...?PB..(centralwidget)
        querybtn.setObjectName("querybtn")
        horizontalLayout_2.aW..(querybtn)
        verticall_down_right.addLayout(horizontalLayout_2)
        viewDetailLabel = ?W...?L..(centralwidget)
        viewDetailLabel.setObjectName("viewDetailLabel")
        verticall_down_right.aW..(viewDetailLabel)
        tableview = ?W...QTableView(centralwidget)
        tableview.setObjectName("tableview")
        verticall_down_right.aW..(tableview)
        paginationLayoutDown = ?W...QHBoxLayout()
        paginationLayoutDown.setObjectName("paginationLayoutDown")
        paginationinfo = ?W...?L..(centralwidget)
        paginationinfo.sT..("")
        paginationinfo.setObjectName("paginationinfo")
        paginationLayoutDown.aW..(paginationinfo)
        prevBtn = ?W...?PB..(centralwidget)
        prevBtn.setEnabled(False)
        prevBtn.setMinimumSize(?C...QSize(100, 0))
        prevBtn.setMaximumSize(?C...QSize(100, 100))
        prevBtn.setCheckable(False)
        prevBtn.setAutoDefault(False)
        prevBtn.setDefault(False)
        prevBtn.setFlat(False)
        prevBtn.setObjectName("prevBtn")
        paginationLayoutDown.aW..(prevBtn)
        nextBtn = ?W...?PB..(centralwidget)
        nextBtn.setEnabled(False)
        nextBtn.setMinimumSize(?C...QSize(100, 32))
        nextBtn.setMaximumSize(?C...QSize(100, 100))
        nextBtn.setObjectName("nextBtn")
        paginationLayoutDown.aW..(nextBtn)
        verticall_down_right.addLayout(paginationLayoutDown)
        horizontal_down.addLayout(verticall_down_right)
        verticalLayout_main.addLayout(horizontal_down)
        verticalLayout_5.addLayout(verticalLayout_main)
        MainWindow.sCW..(centralwidget)
        menubar = ?W...QMenuBar(MainWindow)
        menubar.setGeometry(?C...QRect(0, 0, 925, 22))
        menubar.setObjectName("menubar")
        MainWindow.setMenuBar(menubar)
        statusbar = ?W...QStatusBar(MainWindow)
        statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(statusbar)

        retranslateUi(MainWindow)
        ?C...QMetaObject.connectSlotsByName(MainWindow)

    ___ retranslateUi(self, MainWindow):
        _translate = ?C...QCoreApplication.translate
        MainWindow.sWT..(_translate("MainWindow", "Mongo-pyqt"))
        label.sT..(_translate("MainWindow", "mongo host:"))
        connectBtn.sT..(_translate("MainWindow", "connect"))
        preview1.sT..(_translate("MainWindow", "Preview"))
        treeWidget.headerItem().sT..(0, _translate("MainWindow", "DB"))
        query.sPT..(_translate("MainWindow", "{}"))
        label_2.sT..(_translate("MainWindow", "sort"))
        sort.sPT..(_translate("MainWindow", "{\"field\":1}"))
        querybtn.sT..(_translate("MainWindow", "query"))
        viewDetailLabel.sT..(_translate("MainWindow", "Table Detail:"))
        prevBtn.sT..(_translate("MainWindow", "Prev"))
        nextBtn.sT..(_translate("MainWindow", "Next"))

