# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'audiodevicesbase.ui'
#
# Created: Tue Jun 25 12:31:11 2013
#      by: PyQt5 UI code generator 5.0-snapshot-478d7f271b71
#
# WARNING! All changes made in this file will be lost!

____ ? ______ ?C.., ?G.., ?W..

c_ Ui_AudioDevicesBase o..
    ___ setupUi  AudioDevicesBase):
        AudioDevicesBase.setObjectName("AudioDevicesBase")
        AudioDevicesBase.r..(679, 598)
        centralwidget _ ?W...?W..(AudioDevicesBase)
        centralwidget.setObjectName("centralwidget")
        verticalLayout _ ?W...?VBL..(centralwidget)
        verticalLayout.setObjectName("verticalLayout")
        scrollArea _ ?W...QScrollArea(centralwidget)
        sizePolicy _ ?W...?SP..(?W...?SP...E.., ?W...?SP...E..)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(scrollArea.sizePolicy().hasHeightForWidth())
        scrollArea.sSP..(sizePolicy)
        scrollArea.setWidgetResizable( st.
        scrollArea.setObjectName("scrollArea")
        scrollAreaWidgetContents _ ?W...?W..
        scrollAreaWidgetContents.setGeometry(?C...QRect(0, 0, 659, 558))
        scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        gridLayout_4 _ ?W...QGridLayout(scrollAreaWidgetContents)
        gridLayout_4.setObjectName("gridLayout_4")
        gridLayout_2 _ ?W...QGridLayout()
        gridLayout_2.setObjectName("gridLayout_2")
        modeLabel _ ?W...?L..(scrollAreaWidgetContents)
        modeLabel.setObjectName("modeLabel")
        gridLayout_2.aW..(modeLabel, 0, 0, 1, 1)
        deviceLabel _ ?W...?L..(scrollAreaWidgetContents)
        deviceLabel.setObjectName("deviceLabel")
        gridLayout_2.aW..(deviceLabel, 0, 1, 1, 1)
        modeBox _ ?W...?CB(scrollAreaWidgetContents)
        modeBox.setObjectName("modeBox")
        modeBox.aI..("")
        modeBox.aI..("")
        gridLayout_2.aW..(modeBox, 1, 0, 1, 1)
        deviceBox _ ?W...?CB(scrollAreaWidgetContents)
        deviceBox.setObjectName("deviceBox")
        gridLayout_2.aW..(deviceBox, 1, 1, 1, 1)
        tabWidget _ ?W...?TW..(scrollAreaWidgetContents)
        tabWidget.setObjectName("tabWidget")
        testFormatTab _ ?W...?W..
        testFormatTab.setObjectName("testFormatTab")
        gridLayout _ ?W...QGridLayout(testFormatTab)
        gridLayout.setObjectName("gridLayout")
        actualLabel _ ?W...?L..(testFormatTab)
        sizePolicy _ ?W...?SP..(?W...?SP...Preferred, ?W...?SP...Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(actualLabel.sizePolicy().hasHeightForWidth())
        actualLabel.sSP..(sizePolicy)
        actualLabel.setFrameShape(?W...QFrame.NoFrame)
        actualLabel.setFrameShadow(?W...QFrame.Plain)
        actualLabel.setTextFormat(?C...__.RichText)
        actualLabel.setAlignment(?C...__.AlignCenter)
        actualLabel.setObjectName("actualLabel")
        gridLayout.aW..(actualLabel, 0, 1, 1, 1)
        nearestLabel _ ?W...?L..(testFormatTab)
        sizePolicy _ ?W...?SP..(?W...?SP...Preferred, ?W...?SP...Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(nearestLabel.sizePolicy().hasHeightForWidth())
        nearestLabel.sSP..(sizePolicy)
        nearestLabel.setFrameShape(?W...QFrame.NoFrame)
        nearestLabel.setFrameShadow(?W...QFrame.Plain)
        nearestLabel.setTextFormat(?C...__.RichText)
        nearestLabel.setAlignment(?C...__.AlignCenter)
        nearestLabel.setObjectName("nearestLabel")
        gridLayout.aW..(nearestLabel, 0, 2, 1, 1)
        sampleRateBox _ ?W...?CB(testFormatTab)
        sizePolicy _ ?W...?SP..(?W...?SP...E.., ?W...?SP...Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(sampleRateBox.sizePolicy().hasHeightForWidth())
        sampleRateBox.sSP..(sizePolicy)
        sampleRateBox.setObjectName("sampleRateBox")
        gridLayout.aW..(sampleRateBox, 3, 1, 1, 1)
        nearestSampleRate _ ?W...QLineEdit(testFormatTab)
        nearestSampleRate.sE.. F..
        nearestSampleRate.setObjectName("nearestSampleRate")
        gridLayout.aW..(nearestSampleRate, 3, 2, 1, 1)
        channelsBox _ ?W...?CB(testFormatTab)
        channelsBox.setObjectName("channelsBox")
        gridLayout.aW..(channelsBox, 5, 1, 1, 1)
        nearestChannel _ ?W...QLineEdit(testFormatTab)
        nearestChannel.sE.. F..
        nearestChannel.setObjectName("nearestChannel")
        gridLayout.aW..(nearestChannel, 5, 2, 1, 1)
        sampleSizesBox _ ?W...?CB(testFormatTab)
        sampleSizesBox.setObjectName("sampleSizesBox")
        gridLayout.aW..(sampleSizesBox, 9, 1, 1, 1)
        nearestSampleSize _ ?W...QLineEdit(testFormatTab)
        nearestSampleSize.sE.. F..
        nearestSampleSize.setObjectName("nearestSampleSize")
        gridLayout.aW..(nearestSampleSize, 9, 2, 1, 1)
        endianBox _ ?W...?CB(testFormatTab)
        endianBox.setObjectName("endianBox")
        gridLayout.aW..(endianBox, 14, 1, 1, 1)
        nearestEndian _ ?W...QLineEdit(testFormatTab)
        nearestEndian.sE.. F..
        nearestEndian.setObjectName("nearestEndian")
        gridLayout.aW..(nearestEndian, 14, 2, 1, 1)
        testButton _ ?W...?PB..(testFormatTab)
        testButton.setObjectName("testButton")
        gridLayout.aW..(testButton, 15, 1, 1, 1)
        testResult _ ?W...?L..(testFormatTab)
        testResult.sT..("")
        testResult.setObjectName("testResult")
        gridLayout.aW..(testResult, 15, 2, 1, 1)
        actualFreqLabel _ ?W...?L..(testFormatTab)
        actualFreqLabel.setObjectName("actualFreqLabel")
        gridLayout.aW..(actualFreqLabel, 3, 0, 1, 1)
        actualChannelLabel _ ?W...?L..(testFormatTab)
        actualChannelLabel.setObjectName("actualChannelLabel")
        gridLayout.aW..(actualChannelLabel, 5, 0, 1, 1)
        actualSampleSizeLabel _ ?W...?L..(testFormatTab)
        actualSampleSizeLabel.setObjectName("actualSampleSizeLabel")
        gridLayout.aW..(actualSampleSizeLabel, 9, 0, 1, 1)
        actualEndianLabel _ ?W...?L..(testFormatTab)
        actualEndianLabel.setObjectName("actualEndianLabel")
        gridLayout.aW..(actualEndianLabel, 14, 0, 1, 1)
        label _ ?W...?L..(testFormatTab)
        sizePolicy _ ?W...?SP..(?W...?SP...Preferred, ?W...?SP...Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(label.sizePolicy().hasHeightForWidth())
        label.sSP..(sizePolicy)
        label.setWordWrap( st.
        label.setObjectName("label")
        gridLayout.aW..(label, 16, 0, 1, 3)
        actualCodecLabel _ ?W...?L..(testFormatTab)
        actualCodecLabel.setObjectName("actualCodecLabel")
        gridLayout.aW..(actualCodecLabel, 2, 0, 1, 1)
        nearestCodec _ ?W...QLineEdit(testFormatTab)
        nearestCodec.sE.. F..
        nearestCodec.setObjectName("nearestCodec")
        gridLayout.aW..(nearestCodec, 2, 2, 1, 1)
        codecsBox _ ?W...?CB(testFormatTab)
        codecsBox.setObjectName("codecsBox")
        gridLayout.aW..(codecsBox, 2, 1, 1, 1)
        actualSampleTypeLabel _ ?W...?L..(testFormatTab)
        actualSampleTypeLabel.setObjectName("actualSampleTypeLabel")
        gridLayout.aW..(actualSampleTypeLabel, 6, 0, 1, 1)
        sampleTypesBox _ ?W...?CB(testFormatTab)
        sampleTypesBox.setObjectName("sampleTypesBox")
        gridLayout.aW..(sampleTypesBox, 6, 1, 1, 1)
        nearestSampleType _ ?W...QLineEdit(testFormatTab)
        nearestSampleType.sE.. F..
        nearestSampleType.setObjectName("nearestSampleType")
        gridLayout.aW..(nearestSampleType, 6, 2, 1, 1)
        tabWidget.aT..(testFormatTab, "")
        tab _ ?W...?W..
        tab.setObjectName("tab")
        verticalLayout_2 _ ?W...?VBL..(tab)
        verticalLayout_2.setObjectName("verticalLayout_2")
        populateTableButton _ ?W...?PB..(tab)
        populateTableButton.setObjectName("populateTableButton")
        verticalLayout_2.aW..(populateTableButton)
        allFormatsTable _ ?W...?TW..(tab)
        allFormatsTable.setEditTriggers(?W...?AIV...NoEditTriggers)
        allFormatsTable.setDragDropOverwriteMode F..
        allFormatsTable.setSelectionMode(?W...?AIV...NoSelection)
        allFormatsTable.setSelectionBehavior(?W...?AIV...SelectItems)
        allFormatsTable.setTextElideMode(?C...__.ElideNone)
        allFormatsTable.setWordWrap F..
        allFormatsTable.setCornerButtonEnabled F..
        allFormatsTable.setObjectName("allFormatsTable")
        allFormatsTable.sCC..(6)
        allFormatsTable.sRC..(0)
        item _ ?W...?TWI..()
        item.setTextAlignment(?C...__.AlignHCenter|?C...__.AlignVCenter|?C...__.AlignCenter)
        allFormatsTable.setHorizontalHeaderItem(0, item)
        item _ ?W...?TWI..()
        item.setTextAlignment(?C...__.AlignHCenter|?C...__.AlignVCenter|?C...__.AlignCenter)
        allFormatsTable.setHorizontalHeaderItem(1, item)
        item _ ?W...?TWI..()
        item.setTextAlignment(?C...__.AlignHCenter|?C...__.AlignVCenter|?C...__.AlignCenter)
        allFormatsTable.setHorizontalHeaderItem(2, item)
        item _ ?W...?TWI..()
        item.setTextAlignment(?C...__.AlignHCenter|?C...__.AlignVCenter|?C...__.AlignCenter)
        allFormatsTable.setHorizontalHeaderItem(3, item)
        item _ ?W...?TWI..()
        item.setTextAlignment(?C...__.AlignHCenter|?C...__.AlignVCenter|?C...__.AlignCenter)
        allFormatsTable.setHorizontalHeaderItem(4, item)
        item _ ?W...?TWI..()
        item.setTextAlignment(?C...__.AlignHCenter|?C...__.AlignVCenter|?C...__.AlignCenter)
        allFormatsTable.setHorizontalHeaderItem(5, item)
        allFormatsTable.hH.. .setHighlightSections F..
        allFormatsTable.vH.. .setVisible F..
        allFormatsTable.vH.. .setHighlightSections F..
        verticalLayout_2.aW..(allFormatsTable)
        tabWidget.aT..(tab, "")
        gridLayout_2.aW..(tabWidget, 2, 0, 1, 2)
        gridLayout_4.aL..(gridLayout_2, 0, 0, 1, 1)
        scrollArea.setWidget(scrollAreaWidgetContents)
        verticalLayout.aW..(scrollArea)
        AudioDevicesBase.sCW..(centralwidget)
        statusbar _ ?W...QStatusBar(AudioDevicesBase)
        statusbar.setObjectName("statusbar")
        AudioDevicesBase.sSB..(statusbar)

        retranslateUi(AudioDevicesBase)
        tabWidget.sCI..(0)
        ?C...QMetaObject.connectSlotsByName(AudioDevicesBase)

    ___ retranslateUi  AudioDevicesBase):
        _translate _ ?C... ?CA...translate
        AudioDevicesBase.sWT..(_translate("AudioDevicesBase", "Audio Devices"))
        modeLabel.sT..(_translate("AudioDevicesBase", "Mode"))
        deviceLabel.sT..(_translate("AudioDevicesBase", "Device"))
        modeBox.setItemText(0, _translate("AudioDevicesBase", "Input"))
        modeBox.setItemText(1, _translate("AudioDevicesBase", "Output"))
        actualLabel.sT..(_translate("AudioDevicesBase", "<i>Actual Settings</i>"))
        nearestLabel.sT..(_translate("AudioDevicesBase", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-style:italic;\">Nearest Settings</span></p></body></html>"))
        testButton.sT..(_translate("AudioDevicesBase", "Test"))
        actualFreqLabel.sT..(_translate("AudioDevicesBase", "Frequency (Hz)"))
        actualChannelLabel.sT..(_translate("AudioDevicesBase", "Channels"))
        actualSampleSizeLabel.sT..(_translate("AudioDevicesBase", "Sample size (bits)"))
        actualEndianLabel.sT..(_translate("AudioDevicesBase", "Endianess"))
        label.sT..(_translate("AudioDevicesBase", "Note: an invalid codec \'audio/test\' exists in order to allow an invalid format to be constructed, and therefore to trigger a \'nearest format\' calculation."))
        actualCodecLabel.sT..(_translate("AudioDevicesBase", "Codec"))
        actualSampleTypeLabel.sT..(_translate("AudioDevicesBase", "SampleType"))
        tabWidget.setTabText(tabWidget.indexOf(testFormatTab), _translate("AudioDevicesBase", "Test format"))
        populateTableButton.sT..(_translate("AudioDevicesBase", "Populate table"))
        allFormatsTable.setSortingEnabled F..
        item _ allFormatsTable.horizontalHeaderItem(0)
        item.sT..(_translate("AudioDevicesBase", "Codec"))
        item _ allFormatsTable.horizontalHeaderItem(1)
        item.sT..(_translate("AudioDevicesBase", "Frequency (Hz)"))
        item _ allFormatsTable.horizontalHeaderItem(2)
        item.sT..(_translate("AudioDevicesBase", "Channels"))
        item _ allFormatsTable.horizontalHeaderItem(3)
        item.sT..(_translate("AudioDevicesBase", "Sample type"))
        item _ allFormatsTable.horizontalHeaderItem(4)
        item.sT..(_translate("AudioDevicesBase", "Sample size (bits)"))
        item _ allFormatsTable.horizontalHeaderItem(5)
        item.sT..(_translate("AudioDevicesBase", "Endianness"))
        tabWidget.setTabText(tabWidget.indexOf(tab), _translate("AudioDevicesBase", "All formats"))

