"""
Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.

Example:

Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.

"""
____ c.. _______ defaultdict

__author__ = 'Daniel'


c_ Solution(o..
    ___ findTheDifference  s, t
        """
        :type s: str
        :type t: str
        :rtype: str
        """
        d = defaultdict(i..)
        ___ e __ s:
            d[e] += 1

        ___ e __ t:
            __ d[e] __ 0:
                r.. e
            d[e] -= 1

        r.. ''