# ______ i....
# ______ example
#
#
# c___ C o...
#     p...
#
# c___ C_First C ex___.B
#     p...
#
#
# c___ B_First ex_.B C
#     p...
#
#
# print('B_First:')
# ___ c i_ i___.g..m.. B_F...
#     print *  ||*.f.... c.__n___
# print()
# print('C_First:')
# ___ c i_ i___.g..m.. C_Fi...
#     print *  ||*.f.... c.__n...