import io
data = io.StringIO('asdf in memory')
print(data.getvalue())
print(data.tell())
print(len(data.getvalue()))
print(data.read())
print(data.tell())
print(data.read())
data.seek(0)
print(data.tell())
data.write('data')
print(data.tell())
print(data.read())
print(data.getvalue())