# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.10
#
# WARNING! All changes made in this file will be lost!

____ ? ______ ?C.., ?G.., ?W..

c_ Ui_MainWindow(object):
    ___ setupUi  MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(484, 433)
        centralWidget _ ?W...QWidget(MainWindow)
        sizePolicy _ ?W...QSizePolicy(?W...QSizePolicy.Maximum, ?W...QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(centralWidget.sizePolicy().hasHeightForWidth())
        centralWidget.sSP..(sizePolicy)
        centralWidget.setObjectName("centralWidget")
        verticalLayout_2 _ ?W...QVBoxLayout(centralWidget)
        verticalLayout_2.setContentsMargins(11, 11, 11, 11)
        verticalLayout_2.setSpacing(6)
        verticalLayout_2.setObjectName("verticalLayout_2")
        verticalLayout _ ?W...?VBL..
        verticalLayout.setSpacing(6)
        verticalLayout.setObjectName("verticalLayout")
        lcdNumber _ ?W...QLCDNumber(centralWidget)
        lcdNumber.setDigitCount(10)
        lcdNumber.setObjectName("lcdNumber")
        verticalLayout.aW..(lcdNumber)
        gridLayout _ ?W...QGridLayout()
        gridLayout.setSpacing(6)
        gridLayout.setObjectName("gridLayout")
        pushButton_n4 _ ?W...?PB..(centralWidget)
        pushButton_n4.setMinimumSize(?C...QSize(0, 50))
        font _ ?G...QFont()
        font.setPointSize(27)
        font.setBold(True)
        font.setWeight(75)
        pushButton_n4.setFont(font)
        pushButton_n4.setStyleSheet("QPushButton {\n"
"color: #1976D2;\n"
"}")
        pushButton_n4.setObjectName("pushButton_n4")
        gridLayout.aW..(pushButton_n4, 3, 0, 1, 1)
        pushButton_n1 _ ?W...?PB..(centralWidget)
        pushButton_n1.setMinimumSize(?C...QSize(0, 50))
        font _ ?G...QFont()
        font.setPointSize(27)
        font.setBold(True)
        font.setWeight(75)
        pushButton_n1.setFont(font)
        pushButton_n1.setStyleSheet("QPushButton {\n"
"color: #1976D2;\n"
"}")
        pushButton_n1.setObjectName("pushButton_n1")
        gridLayout.aW..(pushButton_n1, 4, 0, 1, 1)
        pushButton_n8 _ ?W...?PB..(centralWidget)
        pushButton_n8.setMinimumSize(?C...QSize(0, 50))
        font _ ?G...QFont()
        font.setPointSize(27)
        font.setBold(True)
        font.setWeight(75)
        pushButton_n8.setFont(font)
        pushButton_n8.setStyleSheet("QPushButton {\n"
"color: #1976D2;\n"
"}")
        pushButton_n8.setObjectName("pushButton_n8")
        gridLayout.aW..(pushButton_n8, 2, 1, 1, 1)
        pushButton_mul _ ?W...?PB..(centralWidget)
        pushButton_mul.setMinimumSize(?C...QSize(0, 50))
        font _ ?G...QFont()
        font.setPointSize(27)
        font.setBold F..
        font.setWeight(50)
        pushButton_mul.setFont(font)
        pushButton_mul.setObjectName("pushButton_mul")
        gridLayout.aW..(pushButton_mul, 2, 3, 1, 1)
        pushButton_n7 _ ?W...?PB..(centralWidget)
        pushButton_n7.setMinimumSize(?C...QSize(0, 50))
        font _ ?G...QFont()
        font.setPointSize(27)
        font.setBold(True)
        font.setWeight(75)
        pushButton_n7.setFont(font)
        pushButton_n7.setStyleSheet("QPushButton {\n"
"color: #1976D2;\n"
"}")
        pushButton_n7.setObjectName("pushButton_n7")
        gridLayout.aW..(pushButton_n7, 2, 0, 1, 1)
        pushButton_n6 _ ?W...?PB..(centralWidget)
        pushButton_n6.setMinimumSize(?C...QSize(0, 50))
        font _ ?G...QFont()
        font.setPointSize(27)
        font.setBold(True)
        font.setWeight(75)
        pushButton_n6.setFont(font)
        pushButton_n6.setStyleSheet("QPushButton {\n"
"color: #1976D2;\n"
"}")
        pushButton_n6.setObjectName("pushButton_n6")
        gridLayout.aW..(pushButton_n6, 3, 2, 1, 1)
        pushButton_n5 _ ?W...?PB..(centralWidget)
        pushButton_n5.setMinimumSize(?C...QSize(0, 50))
        font _ ?G...QFont()
        font.setPointSize(27)
        font.setBold(True)
        font.setWeight(75)
        pushButton_n5.setFont(font)
        pushButton_n5.setStyleSheet("QPushButton {\n"
"color: #1976D2;\n"
"}")
        pushButton_n5.setObjectName("pushButton_n5")
        gridLayout.aW..(pushButton_n5, 3, 1, 1, 1)
        pushButton_n0 _ ?W...?PB..(centralWidget)
        pushButton_n0.setMinimumSize(?C...QSize(0, 50))
        font _ ?G...QFont()
        font.setPointSize(27)
        font.setBold(True)
        font.setWeight(75)
        pushButton_n0.setFont(font)
        pushButton_n0.setStyleSheet("QPushButton {\n"
"color: #1976D2;\n"
"}")
        pushButton_n0.setObjectName("pushButton_n0")
        gridLayout.aW..(pushButton_n0, 5, 0, 1, 1)
        pushButton_n2 _ ?W...?PB..(centralWidget)
        pushButton_n2.setMinimumSize(?C...QSize(0, 50))
        font _ ?G...QFont()
        font.setPointSize(27)
        font.setBold(True)
        font.setWeight(75)
        pushButton_n2.setFont(font)
        pushButton_n2.setStyleSheet("QPushButton {\n"
"color: #1976D2;\n"
"}")
        pushButton_n2.setObjectName("pushButton_n2")
        gridLayout.aW..(pushButton_n2, 4, 1, 1, 1)
        pushButton_n9 _ ?W...?PB..(centralWidget)
        pushButton_n9.setMinimumSize(?C...QSize(0, 50))
        font _ ?G...QFont()
        font.setPointSize(27)
        font.setBold(True)
        font.setWeight(75)
        pushButton_n9.setFont(font)
        pushButton_n9.setStyleSheet("QPushButton {\n"
"color: #1976D2;\n"
"}")
        pushButton_n9.setObjectName("pushButton_n9")
        gridLayout.aW..(pushButton_n9, 2, 2, 1, 1)
        pushButton_n3 _ ?W...?PB..(centralWidget)
        pushButton_n3.setMinimumSize(?C...QSize(0, 50))
        font _ ?G...QFont()
        font.setPointSize(27)
        font.setBold(True)
        font.setWeight(75)
        pushButton_n3.setFont(font)
        pushButton_n3.setStyleSheet("QPushButton {\n"
"color: #1976D2;\n"
"}")
        pushButton_n3.setObjectName("pushButton_n3")
        gridLayout.aW..(pushButton_n3, 4, 2, 1, 1)
        pushButton_div _ ?W...?PB..(centralWidget)
        pushButton_div.setMinimumSize(?C...QSize(0, 50))
        font _ ?G...QFont()
        font.setPointSize(27)
        font.setBold F..
        font.setWeight(50)
        pushButton_div.setFont(font)
        pushButton_div.setObjectName("pushButton_div")
        gridLayout.aW..(pushButton_div, 1, 3, 1, 1)
        pushButton_sub _ ?W...?PB..(centralWidget)
        pushButton_sub.setMinimumSize(?C...QSize(0, 50))
        font _ ?G...QFont()
        font.setPointSize(27)
        font.setBold F..
        font.setWeight(50)
        pushButton_sub.setFont(font)
        pushButton_sub.setObjectName("pushButton_sub")
        gridLayout.aW..(pushButton_sub, 3, 3, 1, 1)
        pushButton_add _ ?W...?PB..(centralWidget)
        pushButton_add.setMinimumSize(?C...QSize(0, 50))
        font _ ?G...QFont()
        font.setPointSize(27)
        font.setBold F..
        font.setWeight(50)
        pushButton_add.setFont(font)
        pushButton_add.setObjectName("pushButton_add")
        gridLayout.aW..(pushButton_add, 4, 3, 1, 1)
        pushButton_ac _ ?W...?PB..(centralWidget)
        pushButton_ac.setMinimumSize(?C...QSize(0, 50))
        font _ ?G...QFont()
        font.setPointSize(27)
        font.setBold F..
        font.setWeight(50)
        pushButton_ac.setFont(font)
        pushButton_ac.setStyleSheet("QPushButton {\n"
"    color: #f44336;\n"
"}")
        pushButton_ac.setObjectName("pushButton_ac")
        gridLayout.aW..(pushButton_ac, 1, 0, 1, 1)
        pushButton_mr _ ?W...?PB..(centralWidget)
        pushButton_mr.setMinimumSize(?C...QSize(0, 50))
        font _ ?G...QFont()
        font.setPointSize(27)
        font.setBold F..
        font.setWeight(50)
        pushButton_mr.setFont(font)
        pushButton_mr.setStyleSheet("QPushButton {\n"
"   color: #FFC107;\n"
"}")
        pushButton_mr.setObjectName("pushButton_mr")
        gridLayout.aW..(pushButton_mr, 1, 2, 1, 1)
        pushButton_m _ ?W...?PB..(centralWidget)
        pushButton_m.setMinimumSize(?C...QSize(0, 50))
        font _ ?G...QFont()
        font.setPointSize(27)
        font.setBold F..
        font.setWeight(50)
        pushButton_m.setFont(font)
        pushButton_m.setStyleSheet("QPushButton {\n"
"   color: #FFC107;\n"
"}")
        pushButton_m.setObjectName("pushButton_m")
        gridLayout.aW..(pushButton_m, 1, 1, 1, 1)
        pushButton_pc _ ?W...?PB..(centralWidget)
        pushButton_pc.setMinimumSize(?C...QSize(0, 50))
        font _ ?G...QFont()
        font.setPointSize(27)
        font.setBold F..
        font.setWeight(50)
        pushButton_pc.setFont(font)
        pushButton_pc.setObjectName("pushButton_pc")
        gridLayout.aW..(pushButton_pc, 5, 1, 1, 1)
        pushButton_eq _ ?W...?PB..(centralWidget)
        pushButton_eq.setMinimumSize(?C...QSize(0, 50))
        font _ ?G...QFont()
        font.setPointSize(27)
        font.setBold(True)
        font.setWeight(75)
        pushButton_eq.setFont(font)
        pushButton_eq.setStyleSheet("QPushButton {\n"
"color: #4CAF50;\n"
"}")
        pushButton_eq.setObjectName("pushButton_eq")
        gridLayout.aW..(pushButton_eq, 5, 2, 1, 2)
        verticalLayout.aL..(gridLayout)
        verticalLayout_2.aL..(verticalLayout)
        MainWindow.sCW..(centralWidget)
        menuBar _ ?W...QMenuBar(MainWindow)
        menuBar.setGeometry(?C...QRect(0, 0, 484, 22))
        menuBar.setObjectName("menuBar")
        menuFile _ ?W...QMenu(menuBar)
        menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(menuBar)
        statusBar _ ?W...QStatusBar(MainWindow)
        statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(statusBar)
        actionExit _ ?W...?A..(MainWindow)
        actionExit.setObjectName("actionExit")
        actionReset _ ?W...?A..(MainWindow)
        actionReset.setObjectName("actionReset")
        menuFile.aA..(actionReset)
        menuFile.aA..(actionExit)
        menuBar.aA..(menuFile.menuAction())

        retranslateUi(MainWindow)
        ?C...QMetaObject.connectSlotsByName(MainWindow)

    ___ retranslateUi  MainWindow):
        _translate _ ?C...QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Calculon"))
        pushButton_n4.sT..(_translate("MainWindow", "4"))
        pushButton_n4.sS..(_translate("MainWindow", "4"))
        pushButton_n1.sT..(_translate("MainWindow", "1"))
        pushButton_n1.sS..(_translate("MainWindow", "1"))
        pushButton_n8.sT..(_translate("MainWindow", "8"))
        pushButton_n8.sS..(_translate("MainWindow", "8"))
        pushButton_mul.sT..(_translate("MainWindow", "x"))
        pushButton_mul.sS..(_translate("MainWindow", "*"))
        pushButton_n7.sT..(_translate("MainWindow", "7"))
        pushButton_n7.sS..(_translate("MainWindow", "7"))
        pushButton_n6.sT..(_translate("MainWindow", "6"))
        pushButton_n6.sS..(_translate("MainWindow", "6"))
        pushButton_n5.sT..(_translate("MainWindow", "5"))
        pushButton_n5.sS..(_translate("MainWindow", "5"))
        pushButton_n0.sT..(_translate("MainWindow", "0"))
        pushButton_n0.sS..(_translate("MainWindow", "0"))
        pushButton_n2.sT..(_translate("MainWindow", "2"))
        pushButton_n2.sS..(_translate("MainWindow", "2"))
        pushButton_n9.sT..(_translate("MainWindow", "9"))
        pushButton_n9.sS..(_translate("MainWindow", "9"))
        pushButton_n3.sT..(_translate("MainWindow", "3"))
        pushButton_n3.sS..(_translate("MainWindow", "3"))
        pushButton_div.sT..(_translate("MainWindow", "÷"))
        pushButton_div.sS..(_translate("MainWindow", "/"))
        pushButton_sub.sT..(_translate("MainWindow", "-"))
        pushButton_sub.sS..(_translate("MainWindow", "-"))
        pushButton_add.sT..(_translate("MainWindow", "+"))
        pushButton_add.sS..(_translate("MainWindow", "+"))
        pushButton_ac.sT..(_translate("MainWindow", "AC"))
        pushButton_ac.sS..(_translate("MainWindow", "Esc"))
        pushButton_mr.sT..(_translate("MainWindow", "MR"))
        pushButton_mr.sS..(_translate("MainWindow", "R"))
        pushButton_m.sT..(_translate("MainWindow", "M"))
        pushButton_m.sS..(_translate("MainWindow", "M"))
        pushButton_pc.sT..(_translate("MainWindow", "%"))
        pushButton_pc.sS..(_translate("MainWindow", "%"))
        pushButton_eq.sT..(_translate("MainWindow", "="))
        pushButton_eq.sS..(_translate("MainWindow", "Return"))
        menuFile.setTitle(_translate("MainWindow", "File"))
        actionExit.sT..(_translate("MainWindow", "Exit"))
        actionExit.sS..(_translate("MainWindow", "Ctrl+Q"))
        actionReset.sT..(_translate("MainWindow", "Reset"))
        actionReset.sS..(_translate("MainWindow", "Ctrl+R"))

