# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.10
#
# WARNING! All changes made in this file will be lost!

____ ? ______ ?C.., ?G.., ?W..

c_ Ui_MainWindow(object):
    ___ setupUi  MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(484, 433)
        self.centralWidget _ ?W...QWidget(MainWindow)
        sizePolicy _ ?W...QSizePolicy(?W...QSizePolicy.Maximum, ?W...QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralWidget.sizePolicy().hasHeightForWidth())
        self.centralWidget.setSizePolicy(sizePolicy)
        self.centralWidget.setObjectName("centralWidget")
        self.verticalLayout_2 _ ?W...QVBoxLayout(self.centralWidget)
        self.verticalLayout_2.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout _ ?W...QVBoxLayout()
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lcdNumber _ ?W...QLCDNumber(self.centralWidget)
        self.lcdNumber.setDigitCount(10)
        self.lcdNumber.setObjectName("lcdNumber")
        self.verticalLayout.addWidget(self.lcdNumber)
        self.gridLayout _ ?W...QGridLayout()
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_n4 _ ?W...?PB..(self.centralWidget)
        self.pushButton_n4.setMinimumSize(?C...QSize(0, 50))
        font _ ?G...QFont()
        font.setPointSize(27)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_n4.setFont(font)
        self.pushButton_n4.setStyleSheet("QPushButton {\n"
"color: #1976D2;\n"
"}")
        self.pushButton_n4.setObjectName("pushButton_n4")
        self.gridLayout.addWidget(self.pushButton_n4, 3, 0, 1, 1)
        self.pushButton_n1 _ ?W...?PB..(self.centralWidget)
        self.pushButton_n1.setMinimumSize(?C...QSize(0, 50))
        font _ ?G...QFont()
        font.setPointSize(27)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_n1.setFont(font)
        self.pushButton_n1.setStyleSheet("QPushButton {\n"
"color: #1976D2;\n"
"}")
        self.pushButton_n1.setObjectName("pushButton_n1")
        self.gridLayout.addWidget(self.pushButton_n1, 4, 0, 1, 1)
        self.pushButton_n8 _ ?W...?PB..(self.centralWidget)
        self.pushButton_n8.setMinimumSize(?C...QSize(0, 50))
        font _ ?G...QFont()
        font.setPointSize(27)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_n8.setFont(font)
        self.pushButton_n8.setStyleSheet("QPushButton {\n"
"color: #1976D2;\n"
"}")
        self.pushButton_n8.setObjectName("pushButton_n8")
        self.gridLayout.addWidget(self.pushButton_n8, 2, 1, 1, 1)
        self.pushButton_mul _ ?W...?PB..(self.centralWidget)
        self.pushButton_mul.setMinimumSize(?C...QSize(0, 50))
        font _ ?G...QFont()
        font.setPointSize(27)
        font.setBold F..
        font.setWeight(50)
        self.pushButton_mul.setFont(font)
        self.pushButton_mul.setObjectName("pushButton_mul")
        self.gridLayout.addWidget(self.pushButton_mul, 2, 3, 1, 1)
        self.pushButton_n7 _ ?W...?PB..(self.centralWidget)
        self.pushButton_n7.setMinimumSize(?C...QSize(0, 50))
        font _ ?G...QFont()
        font.setPointSize(27)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_n7.setFont(font)
        self.pushButton_n7.setStyleSheet("QPushButton {\n"
"color: #1976D2;\n"
"}")
        self.pushButton_n7.setObjectName("pushButton_n7")
        self.gridLayout.addWidget(self.pushButton_n7, 2, 0, 1, 1)
        self.pushButton_n6 _ ?W...?PB..(self.centralWidget)
        self.pushButton_n6.setMinimumSize(?C...QSize(0, 50))
        font _ ?G...QFont()
        font.setPointSize(27)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_n6.setFont(font)
        self.pushButton_n6.setStyleSheet("QPushButton {\n"
"color: #1976D2;\n"
"}")
        self.pushButton_n6.setObjectName("pushButton_n6")
        self.gridLayout.addWidget(self.pushButton_n6, 3, 2, 1, 1)
        self.pushButton_n5 _ ?W...?PB..(self.centralWidget)
        self.pushButton_n5.setMinimumSize(?C...QSize(0, 50))
        font _ ?G...QFont()
        font.setPointSize(27)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_n5.setFont(font)
        self.pushButton_n5.setStyleSheet("QPushButton {\n"
"color: #1976D2;\n"
"}")
        self.pushButton_n5.setObjectName("pushButton_n5")
        self.gridLayout.addWidget(self.pushButton_n5, 3, 1, 1, 1)
        self.pushButton_n0 _ ?W...?PB..(self.centralWidget)
        self.pushButton_n0.setMinimumSize(?C...QSize(0, 50))
        font _ ?G...QFont()
        font.setPointSize(27)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_n0.setFont(font)
        self.pushButton_n0.setStyleSheet("QPushButton {\n"
"color: #1976D2;\n"
"}")
        self.pushButton_n0.setObjectName("pushButton_n0")
        self.gridLayout.addWidget(self.pushButton_n0, 5, 0, 1, 1)
        self.pushButton_n2 _ ?W...?PB..(self.centralWidget)
        self.pushButton_n2.setMinimumSize(?C...QSize(0, 50))
        font _ ?G...QFont()
        font.setPointSize(27)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_n2.setFont(font)
        self.pushButton_n2.setStyleSheet("QPushButton {\n"
"color: #1976D2;\n"
"}")
        self.pushButton_n2.setObjectName("pushButton_n2")
        self.gridLayout.addWidget(self.pushButton_n2, 4, 1, 1, 1)
        self.pushButton_n9 _ ?W...?PB..(self.centralWidget)
        self.pushButton_n9.setMinimumSize(?C...QSize(0, 50))
        font _ ?G...QFont()
        font.setPointSize(27)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_n9.setFont(font)
        self.pushButton_n9.setStyleSheet("QPushButton {\n"
"color: #1976D2;\n"
"}")
        self.pushButton_n9.setObjectName("pushButton_n9")
        self.gridLayout.addWidget(self.pushButton_n9, 2, 2, 1, 1)
        self.pushButton_n3 _ ?W...?PB..(self.centralWidget)
        self.pushButton_n3.setMinimumSize(?C...QSize(0, 50))
        font _ ?G...QFont()
        font.setPointSize(27)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_n3.setFont(font)
        self.pushButton_n3.setStyleSheet("QPushButton {\n"
"color: #1976D2;\n"
"}")
        self.pushButton_n3.setObjectName("pushButton_n3")
        self.gridLayout.addWidget(self.pushButton_n3, 4, 2, 1, 1)
        self.pushButton_div _ ?W...?PB..(self.centralWidget)
        self.pushButton_div.setMinimumSize(?C...QSize(0, 50))
        font _ ?G...QFont()
        font.setPointSize(27)
        font.setBold F..
        font.setWeight(50)
        self.pushButton_div.setFont(font)
        self.pushButton_div.setObjectName("pushButton_div")
        self.gridLayout.addWidget(self.pushButton_div, 1, 3, 1, 1)
        self.pushButton_sub _ ?W...?PB..(self.centralWidget)
        self.pushButton_sub.setMinimumSize(?C...QSize(0, 50))
        font _ ?G...QFont()
        font.setPointSize(27)
        font.setBold F..
        font.setWeight(50)
        self.pushButton_sub.setFont(font)
        self.pushButton_sub.setObjectName("pushButton_sub")
        self.gridLayout.addWidget(self.pushButton_sub, 3, 3, 1, 1)
        self.pushButton_add _ ?W...?PB..(self.centralWidget)
        self.pushButton_add.setMinimumSize(?C...QSize(0, 50))
        font _ ?G...QFont()
        font.setPointSize(27)
        font.setBold F..
        font.setWeight(50)
        self.pushButton_add.setFont(font)
        self.pushButton_add.setObjectName("pushButton_add")
        self.gridLayout.addWidget(self.pushButton_add, 4, 3, 1, 1)
        self.pushButton_ac _ ?W...?PB..(self.centralWidget)
        self.pushButton_ac.setMinimumSize(?C...QSize(0, 50))
        font _ ?G...QFont()
        font.setPointSize(27)
        font.setBold F..
        font.setWeight(50)
        self.pushButton_ac.setFont(font)
        self.pushButton_ac.setStyleSheet("QPushButton {\n"
"    color: #f44336;\n"
"}")
        self.pushButton_ac.setObjectName("pushButton_ac")
        self.gridLayout.addWidget(self.pushButton_ac, 1, 0, 1, 1)
        self.pushButton_mr _ ?W...?PB..(self.centralWidget)
        self.pushButton_mr.setMinimumSize(?C...QSize(0, 50))
        font _ ?G...QFont()
        font.setPointSize(27)
        font.setBold F..
        font.setWeight(50)
        self.pushButton_mr.setFont(font)
        self.pushButton_mr.setStyleSheet("QPushButton {\n"
"   color: #FFC107;\n"
"}")
        self.pushButton_mr.setObjectName("pushButton_mr")
        self.gridLayout.addWidget(self.pushButton_mr, 1, 2, 1, 1)
        self.pushButton_m _ ?W...?PB..(self.centralWidget)
        self.pushButton_m.setMinimumSize(?C...QSize(0, 50))
        font _ ?G...QFont()
        font.setPointSize(27)
        font.setBold F..
        font.setWeight(50)
        self.pushButton_m.setFont(font)
        self.pushButton_m.setStyleSheet("QPushButton {\n"
"   color: #FFC107;\n"
"}")
        self.pushButton_m.setObjectName("pushButton_m")
        self.gridLayout.addWidget(self.pushButton_m, 1, 1, 1, 1)
        self.pushButton_pc _ ?W...?PB..(self.centralWidget)
        self.pushButton_pc.setMinimumSize(?C...QSize(0, 50))
        font _ ?G...QFont()
        font.setPointSize(27)
        font.setBold F..
        font.setWeight(50)
        self.pushButton_pc.setFont(font)
        self.pushButton_pc.setObjectName("pushButton_pc")
        self.gridLayout.addWidget(self.pushButton_pc, 5, 1, 1, 1)
        self.pushButton_eq _ ?W...?PB..(self.centralWidget)
        self.pushButton_eq.setMinimumSize(?C...QSize(0, 50))
        font _ ?G...QFont()
        font.setPointSize(27)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_eq.setFont(font)
        self.pushButton_eq.setStyleSheet("QPushButton {\n"
"color: #4CAF50;\n"
"}")
        self.pushButton_eq.setObjectName("pushButton_eq")
        self.gridLayout.addWidget(self.pushButton_eq, 5, 2, 1, 2)
        self.verticalLayout.addLayout(self.gridLayout)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        MainWindow.sCW..(self.centralWidget)
        self.menuBar _ ?W...QMenuBar(MainWindow)
        self.menuBar.setGeometry(?C...QRect(0, 0, 484, 22))
        self.menuBar.setObjectName("menuBar")
        self.menuFile _ ?W...QMenu(self.menuBar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menuBar)
        self.statusBar _ ?W...QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.actionExit _ ?W...?A..(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionReset _ ?W...?A..(MainWindow)
        self.actionReset.setObjectName("actionReset")
        self.menuFile.aA..(self.actionReset)
        self.menuFile.aA..(self.actionExit)
        self.menuBar.aA..(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        ?C...QMetaObject.connectSlotsByName(MainWindow)

    ___ retranslateUi  MainWindow):
        _translate _ ?C...QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Calculon"))
        self.pushButton_n4.sT..(_translate("MainWindow", "4"))
        self.pushButton_n4.sS..(_translate("MainWindow", "4"))
        self.pushButton_n1.sT..(_translate("MainWindow", "1"))
        self.pushButton_n1.sS..(_translate("MainWindow", "1"))
        self.pushButton_n8.sT..(_translate("MainWindow", "8"))
        self.pushButton_n8.sS..(_translate("MainWindow", "8"))
        self.pushButton_mul.sT..(_translate("MainWindow", "x"))
        self.pushButton_mul.sS..(_translate("MainWindow", "*"))
        self.pushButton_n7.sT..(_translate("MainWindow", "7"))
        self.pushButton_n7.sS..(_translate("MainWindow", "7"))
        self.pushButton_n6.sT..(_translate("MainWindow", "6"))
        self.pushButton_n6.sS..(_translate("MainWindow", "6"))
        self.pushButton_n5.sT..(_translate("MainWindow", "5"))
        self.pushButton_n5.sS..(_translate("MainWindow", "5"))
        self.pushButton_n0.sT..(_translate("MainWindow", "0"))
        self.pushButton_n0.sS..(_translate("MainWindow", "0"))
        self.pushButton_n2.sT..(_translate("MainWindow", "2"))
        self.pushButton_n2.sS..(_translate("MainWindow", "2"))
        self.pushButton_n9.sT..(_translate("MainWindow", "9"))
        self.pushButton_n9.sS..(_translate("MainWindow", "9"))
        self.pushButton_n3.sT..(_translate("MainWindow", "3"))
        self.pushButton_n3.sS..(_translate("MainWindow", "3"))
        self.pushButton_div.sT..(_translate("MainWindow", "÷"))
        self.pushButton_div.sS..(_translate("MainWindow", "/"))
        self.pushButton_sub.sT..(_translate("MainWindow", "-"))
        self.pushButton_sub.sS..(_translate("MainWindow", "-"))
        self.pushButton_add.sT..(_translate("MainWindow", "+"))
        self.pushButton_add.sS..(_translate("MainWindow", "+"))
        self.pushButton_ac.sT..(_translate("MainWindow", "AC"))
        self.pushButton_ac.sS..(_translate("MainWindow", "Esc"))
        self.pushButton_mr.sT..(_translate("MainWindow", "MR"))
        self.pushButton_mr.sS..(_translate("MainWindow", "R"))
        self.pushButton_m.sT..(_translate("MainWindow", "M"))
        self.pushButton_m.sS..(_translate("MainWindow", "M"))
        self.pushButton_pc.sT..(_translate("MainWindow", "%"))
        self.pushButton_pc.sS..(_translate("MainWindow", "%"))
        self.pushButton_eq.sT..(_translate("MainWindow", "="))
        self.pushButton_eq.sS..(_translate("MainWindow", "Return"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionExit.sT..(_translate("MainWindow", "Exit"))
        self.actionExit.sS..(_translate("MainWindow", "Ctrl+Q"))
        self.actionReset.sT..(_translate("MainWindow", "Reset"))
        self.actionReset.sS..(_translate("MainWindow", "Ctrl+R"))

