# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'G:\projects\pyqt\week3\icon_widget\iconWidget.ui'
#
# Created: Wed Oct 15 18:38:43 2014
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

____ PySide _____ ?C.., QtGui

c_ Ui_MainWindow(object
    ___ setupUi , MainWindow
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(237, 369)
        centralwidget = QtGui.?W..(MainWindow)
        centralwidget.setObjectName("centralwidget")
        horizontalLayout_2 = QtGui.QHBoxLayout(centralwidget)
        horizontalLayout_2.setSpacing(0)
        horizontalLayout_2.setObjectName("horizontalLayout_2")
        verticalLayout = QtGui.QVBoxLayout()
        verticalLayout.setObjectName("verticalLayout")
        horizontalLayout = QtGui.QHBoxLayout()
        horizontalLayout.setObjectName("horizontalLayout")
        fill_btn = QtGui.?PB..(centralwidget)
        fill_btn.setObjectName("fill_btn")
        horizontalLayout.addWidget(fill_btn)
        clear_btn = QtGui.?PB..(centralwidget)
        clear_btn.setMinimumSize(?C...QSize(40, 0))
        clear_btn.setObjectName("clear_btn")
        horizontalLayout.addWidget(clear_btn)
        image_lb = QtGui.QLabel(centralwidget)
        image_lb.setObjectName("image_lb")
        horizontalLayout.addWidget(image_lb)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        horizontalLayout.addItem(spacerItem)
        verticalLayout.addLayout(horizontalLayout)
        combo_cbb = QtGui.QComboBox(centralwidget)
        combo_cbb.setObjectName("combo_cbb")
        verticalLayout.addWidget(combo_cbb)
        list_lwd = QtGui.QListWidget(centralwidget)
        list_lwd.setObjectName("list_lwd")
        verticalLayout.addWidget(list_lwd)
        horizontalLayout_2.addLayout(verticalLayout)
        label = QtGui.QLabel(centralwidget)
        label.sT..("")
        label.setObjectName("label")
        horizontalLayout_2.addWidget(label)
        MainWindow.setCentralWidget(centralwidget)
        statusbar = QtGui.QStatusBar(MainWindow)
        statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(statusbar)
        toolBar = QtGui.QToolBar(MainWindow)
        toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(?C...Qt.TopToolBarArea, toolBar)
        menuBar = QtGui.QMenuBar(MainWindow)
        menuBar.setGeometry(?C...QRect(0, 0, 237, 21))
        menuBar.setObjectName("menuBar")
        menuFile = QtGui.QMenu(menuBar)
        menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(menuBar)
        fill_act = QtGui.QAction(MainWindow)
        fill_act.setObjectName("fill_act")
        clear_act = QtGui.QAction(MainWindow)
        clear_act.setObjectName("clear_act")
        open_act = QtGui.QAction(MainWindow)
        open_act.setObjectName("open_act")
        save_act = QtGui.QAction(MainWindow)
        save_act.setObjectName("save_act")
        exit_act = QtGui.QAction(MainWindow)
        exit_act.setObjectName("exit_act")
        toolBar.addAction(fill_act)
        toolBar.addAction(clear_act)
        menuFile.addAction(open_act)
        menuFile.addAction(save_act)
        menuFile.addSeparator()
        menuFile.addAction(exit_act)
        menuBar.addAction(menuFile.menuAction())

        retranslateUi(MainWindow)
        ?C...QMetaObject.connectSlotsByName(MainWindow)

    ___ retranslateUi , MainWindow
        MainWindow.setWindowTitle(QtGui.?A...translate("MainWindow", "MainWindow", None, QtGui.?A...UnicodeUTF8))
        fill_btn.sT..(QtGui.?A...translate("MainWindow", "Fill", None, QtGui.?A...UnicodeUTF8))
        clear_btn.sT..(QtGui.?A...translate("MainWindow", "Clear", None, QtGui.?A...UnicodeUTF8))
        image_lb.sT..(QtGui.?A...translate("MainWindow", "TextLabel", None, QtGui.?A...UnicodeUTF8))
        toolBar.setWindowTitle(QtGui.?A...translate("MainWindow", "toolBar", None, QtGui.?A...UnicodeUTF8))
        menuFile.setTitle(QtGui.?A...translate("MainWindow", "File", None, QtGui.?A...UnicodeUTF8))
        fill_act.sT..(QtGui.?A...translate("MainWindow", "Fill", None, QtGui.?A...UnicodeUTF8))
        clear_act.sT..(QtGui.?A...translate("MainWindow", "Clear", None, QtGui.?A...UnicodeUTF8))
        open_act.sT..(QtGui.?A...translate("MainWindow", "Open", None, QtGui.?A...UnicodeUTF8))
        save_act.sT..(QtGui.?A...translate("MainWindow", "Save", None, QtGui.?A...UnicodeUTF8))
        exit_act.sT..(QtGui.?A...translate("MainWindow", "Exit", None, QtGui.?A...UnicodeUTF8))

