# Generated by Django 2.1 on 2018-08-30 11:27

____ django.db ______ migrations, models


c_ Migration(migrations.Migration):

    initial _ True

    dependencies _ [
    ]

    operations _ [
        migrations.CreateModel(
            name_'Issue',
            fields_[
                ('id', models.AutoField(auto_created_True, primary_key_True, serialize_False, verbose_name_'ID')),
                ('name', models.CharField(max_length_512, verbose_name_'Название')),
                ('description', models.TextField(default_'', verbose_name_'Описание')),
                ('due_date', models.DateField(verbose_name_'Выполнить к дате')),
            ],
            options_{
                'verbose_name': 'Заметка',
                'verbose_name_plural': 'Заметки',
            },
        ),
    ]
