# from urllib _______ r______
#
# response = r______.u..o... http://example.com
#
# print r______.s.....
# print r______.g......
# print r______.m...
# print r______.r....
# # получаем заголовки в виде внутреннего объекта
# print r______.h....
# # получаем словарь всех заголовков
# print r______.g....
# # получение заголовка
# print r______.he___.g.. Content-Type
# print r______.ge___ Content-Type
