# # example 2 (UDP unix socket)
# ______ os
# ______ s......
#
# unix_sock_name _ 'unix.sock'
# sock _ s____.s____(s____.A._U... s____.S..._D...
#
# i_ o_.p___.ex___ u......
#     o_.r... u.....
#
# s___.b____u.....
#
# w____ ....
#     t..
#         result _ s___.r... 1024
#     e___ K.....I....
#         s___.cl....
#         b.....
#     e...
#         print 'Message' r_.d_ utf-8
