# # example 1 (UDP server socket)
# ______ s......
#
# sock _ s____.s____ s____.A._I... s____.S..._D...
# s___.b____ 127.0.0.1 8888
#
# w____ T...
#     t...
#         result _ s___.r... 1024
#     e____ K...I....
#         s___.c___
#         b____
#     e____
#         print 'Message' r___.d___ utf-8
